/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ausbildungskategorie } from './ausbildungskategorie';
import { AbschlussZusatzfrage } from './abschlussZusatzfrage';

export interface AbschlussSlim { 
    id: string;
    bezeichnungDe: string;
    bezeichnungFr: string;
    ausbildungskategorie: Ausbildungskategorie;
    zusatzfrage?: AbschlussZusatzfrage;
}



