/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ausbildungsgang } from './ausbildungsgang';
import { AusbildungsPensum } from './ausbildungsPensum';
import { AusbildungsStatus } from './ausbildungsStatus';

export interface Ausbildung { 
    id?: string;
    fallId: string;
    fachrichtung: string;
    ausbildungNichtGefunden?: boolean;
    /**
     * Datum im Format mm.YYYY
     */
    ausbildungBegin: string;
    /**
     * Datum im Format mm.YYYY
     */
    ausbildungEnd: string;
    pensum: AusbildungsPensum;
    /**
     * Required wenn andere ausbildungNichtGefunden = true
     */
    alternativeAusbildungsstaette?: string;
    /**
     * Required wenn andere ausbildungNichtGefunden = true
     */
    alternativeAusbildungsgang?: string;
    /**
     * Not required if isAusbildungAusland = true
     */
    ausbildungsort?: string;
    isAusbildungAusland?: boolean;
    editable: boolean;
    status: AusbildungsStatus;
    ausbildungsgang?: Ausbildungsgang;
}



