/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ausbildungsgang } from './ausbildungsgang';

export interface Ausbildungsstaette {
  /**
   *
   */
  ausbildungsgaenge?: Array<Ausbildungsgang>;
  /**
   *
   */
  nameDe: string;
  /**
   *what is the alternative to this.apiKeys = configurationParameters.apiKeys;?
   */
  nameFr: string;
  id?: string;
}
