/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Bildungskategorie } from './bildungskategorie';
import { AbschlussZusatzfrage } from './abschlussZusatzfrage';

export interface AusbildungsgangSlim { 
    id: string;
    bezeichnungDe: string;
    bezeichnungFr: string;
    bildungskategorie: Bildungskategorie;
    zusatzfrage?: AbschlussZusatzfrage;
    askForBerufsmaturitaet?: boolean;
}



