/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AusbildungUnterbruchAntragStatus } from './ausbildungUnterbruchAntragStatus';
import { Dokument } from './dokument';

export interface AusbildungUnterbruchAntragSB { 
    status: AusbildungUnterbruchAntragStatus;
    kommentarSB: string;
    startDate: string;
    endDate: string;
    monateOhneAnspruch?: number;
    id: string;
    timestampErstellt: string;
    userErstellt: string;
    kommentarGS: string;
    canAntragAkzeptieren: boolean;
    dokuments: Array<Dokument>;
    gesuchId: string;
    unterbruchLatestEndDate: string;
    unterbruchEarliestStartDate: string;
}



