/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AusbildungsPensum } from './ausbildungsPensum';

export interface AusbildungUpdate { 
    id?: string;
    fallId: string;
    fachrichtung: string;
    ausbildungNichtGefunden?: boolean;
    /**
     * Datum im Format mm.YYYY
     */
    ausbildungBegin: string;
    /**
     * Datum im Format mm.YYYY
     */
    ausbildungEnd: string;
    /**
     * Required bei Ausbildungskategorien 4 oder 5. Kann nur dann auf true gesetzt werden.
     */
    besuchtBMS?: boolean;
    pensum: AusbildungsPensum;
    /**
     * Required wenn andere ausbildungNichtGefunden = true
     */
    alternativeAusbildungsstaette?: string;
    /**
     * Required wenn andere ausbildungNichtGefunden = true
     */
    alternativeAusbildungsgang?: string;
    /**
     * Not required if isAusbildungAusland = true
     */
    ausbildungsort?: string;
    isAusbildungAusland?: boolean;
    ausbildungsgangId?: string;
}



