/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type AusbildungsstaetteSortColumn = 'NAME_DE' | 'NAME_FR' | 'CH_SHIS' | 'BUR_NO' | 'CT_NO' | 'AKTIV';

export const AusbildungsstaetteSortColumn = {
    NAME_DE: 'NAME_DE' as AusbildungsstaetteSortColumn,
    NAME_FR: 'NAME_FR' as AusbildungsstaetteSortColumn,
    CH_SHIS: 'CH_SHIS' as AusbildungsstaetteSortColumn,
    BUR_NO: 'BUR_NO' as AusbildungsstaetteSortColumn,
    CT_NO: 'CT_NO' as AusbildungsstaetteSortColumn,
    AKTIV: 'AKTIV' as AusbildungsstaetteSortColumn
};

