/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type AusbildungCreateErrorType = 'KEINE_AKTIVE_PERIODE_GEFUNDEN' | 'PERIODE_IN_ENTWURF_GEFUNDEN' | 'INAKTIVE_PERIODE_GEFUNDEN';

export const AusbildungCreateErrorType = {
    KEINE_AKTIVE_PERIODE_GEFUNDEN: 'KEINE_AKTIVE_PERIODE_GEFUNDEN' as AusbildungCreateErrorType,
    PERIODE_IN_ENTWURF_GEFUNDEN: 'PERIODE_IN_ENTWURF_GEFUNDEN' as AusbildungCreateErrorType,
    INAKTIVE_PERIODE_GEFUNDEN: 'INAKTIVE_PERIODE_GEFUNDEN' as AusbildungCreateErrorType
};

