/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Ausbildungskategorie = 'UNIVERSITAET_ETH' | 'PAEDAGOGISCHE_HOCHSCHULE' | 'FACHHOCHSCHULE' | 'HOEHERE_FACHSCHULE' | 'BERUFS_UND_HOEHERE_FACHSCHULE' | 'EIDGENOESSISCHE_HOCHSCHULE_FUER_BERUFSBILDUNG' | 'GYMNASIUM' | 'BERUFSFACHSCHULEN' | 'FACHMITTELSCHULE' | 'BERUFSFACHSCHULEN_UEBERBETRIEBLICHE_KURSE' | 'BETRIEBE' | 'OBLIGATORISCHE_SCHULE' | 'BRUECKENANGEBOT';

export const Ausbildungskategorie = {
    UNIVERSITAET_ETH: 'UNIVERSITAET_ETH' as Ausbildungskategorie,
    PAEDAGOGISCHE_HOCHSCHULE: 'PAEDAGOGISCHE_HOCHSCHULE' as Ausbildungskategorie,
    FACHHOCHSCHULE: 'FACHHOCHSCHULE' as Ausbildungskategorie,
    HOEHERE_FACHSCHULE: 'HOEHERE_FACHSCHULE' as Ausbildungskategorie,
    BERUFS_UND_HOEHERE_FACHSCHULE: 'BERUFS_UND_HOEHERE_FACHSCHULE' as Ausbildungskategorie,
    EIDGENOESSISCHE_HOCHSCHULE_FUER_BERUFSBILDUNG: 'EIDGENOESSISCHE_HOCHSCHULE_FUER_BERUFSBILDUNG' as Ausbildungskategorie,
    GYMNASIUM: 'GYMNASIUM' as Ausbildungskategorie,
    BERUFSFACHSCHULEN: 'BERUFSFACHSCHULEN' as Ausbildungskategorie,
    FACHMITTELSCHULE: 'FACHMITTELSCHULE' as Ausbildungskategorie,
    BERUFSFACHSCHULEN_UEBERBETRIEBLICHE_KURSE: 'BERUFSFACHSCHULEN_UEBERBETRIEBLICHE_KURSE' as Ausbildungskategorie,
    BETRIEBE: 'BETRIEBE' as Ausbildungskategorie,
    OBLIGATORISCHE_SCHULE: 'OBLIGATORISCHE_SCHULE' as Ausbildungskategorie,
    BRUECKENANGEBOT: 'BRUECKENANGEBOT' as Ausbildungskategorie
};

