/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TranchenBerechnungsresultat } from './tranchenBerechnungsresultat';

/**
 * Resultat der Berechnung (gesamtes Gesuch)
 */
export interface Berechnungsresultat { 
    year: number;
    /**
     * Die Summe der berechneten Stpendiumansprüche für das Gesuch vor Kürzungen und Teilung des Gesetzlichen Darlehens
     */
    berechnungVorKuerzungUndTeilung: number;
    /**
     * Die Summe der berechneten Stpendiumansprüche für das Gesuch vor Kürzungen abzüglich des Darlehens (wird nur für Vergleiche und debugging verwendet)
     */
    ungekuerztStipendien?: number;
    /**
     * Die Summe des berechneten Darlehens für das Gesuch vor Kürzungen (wird nur für Vergleiche und debugging verwendet)
     */
    ungekuerztDarlehen?: number;
    /**
     * Die Summe nach der Kürzung der verspäteten Eingabe
     */
    totalNachKuerzungNachEinreichefrist?: number;
    /**
     * Die Anzahl Monate der verspäteten Eingabe
     */
    anzahlMonateEinreichefrist?: number;
    /**
     * Die Summe nach der Kürzung des Unterbruchs der Ausbildung
     */
    totalNachKuerzungUnterbruch?: number;
    /**
     * Die Anzahl Monate von dem Unterbruch der Ausbildung
     */
    anzahlMonateUnterbruch?: number;
    /**
     * berechneter stipendienbetrag vor der Teilung in darlehen und stipendium
     */
    berechnungVorTeilungDarlehen: number;
    /**
     * Berechneter Stpendiumsanspruch für das Gesuch
     */
    berechnungStipendium: number;
    /**
     * Berechneter Darlehensanspruch für das Gesuch
     */
    berechnungDarlehen?: number;
    /**
     * Resultate der Berechnung für die Tranchen des Gesuchs
     */
    tranchenBerechnungsresultate: Array<TranchenBerechnungsresultat>;
    /**
     * Die anzahl monate die das Gesuch 36 Monate in Tertiaerausbildung uberschreitet
     */
    monateMitDarlehen: number;
}

