/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TranchenBerechnungsresultat } from './tranchenBerechnungsresultat';

/**
 * Resultat der Berechnung (gesamtes Gesuch)
 */
export interface Berechnungsresultat { 
    year: number;
    /**
     * Die Summe der berechneten Stpendiums- und Darlehensansprüche für das Gesuch
     */
    berechnungTotal: number;
    /**
     * Berechneter Stpendiumsanspruch für das Gesuch
     */
    berechnungStipendium: number;
    /**
     * Berechneter Darlehensanspruch für das Gesuch
     */
    berechnungDarlehen: number;
    /**
     * Berechneter Stpendiumsanspruch für das Gesuch nach allfälligem abzug wegen zuspäteinreichens
     */
    berechnungReduziert?: number;
    /**
     * Resultate der Berechnung für die Tranchen des Gesuchs
     */
    tranchenBerechnungsresultate: Array<TranchenBerechnungsresultat>;
    /**
     * Die Anzahl von Monaten für welche die Berechnung stattfand
     */
    verminderteBerechnungMonate?: number;
}

