/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FamilienBudgetresultat } from './familienBudgetresultat';
import { PersoenlichesBudgetresultat } from './persoenlichesBudgetresultat';

/**
 * Resultat der Berechnung (eine Tranche)
 */
export interface Berechnungsresultat { 
    /**
     * Berechneter Stpendiumsanspruch für diese Tranche
     */
    berechnung: number;
    persoenlichesBudgetresultat: PersoenlichesBudgetresultat;
    /**
     * Berechnungsdaten der Familienbudgets
     */
    familienBudgetresultate: Array<FamilienBudgetresultat>;
}

