/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Bildungsrichtung = 'BERUFLICHE_GRUNDBILDUNG' | 'ALLGEMEINBILDENDE_SCHULE' | 'HOEHERE_BERUFSBILDUNG' | 'HOCHSCHULE' | 'OBLIGATORISCHE_SCHULE';

export const Bildungsrichtung = {
    BERUFLICHE_GRUNDBILDUNG: 'BERUFLICHE_GRUNDBILDUNG' as Bildungsrichtung,
    ALLGEMEINBILDENDE_SCHULE: 'ALLGEMEINBILDENDE_SCHULE' as Bildungsrichtung,
    HOEHERE_BERUFSBILDUNG: 'HOEHERE_BERUFSBILDUNG' as Bildungsrichtung,
    HOCHSCHULE: 'HOCHSCHULE' as Bildungsrichtung,
    OBLIGATORISCHE_SCHULE: 'OBLIGATORISCHE_SCHULE' as Bildungsrichtung
};

