/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type DarlehenDokumentType = 'BETREIBUNGS_AUSZUG' | 'AUFSTELLUNG_KOSTEN_ELTERN' | 'KOPIE_SCHULGELDRECHNUNG' | 'BELEGE_ANSCHAFFUNGEN';

export const DarlehenDokumentType = {
    BETREIBUNGS_AUSZUG: 'BETREIBUNGS_AUSZUG' as DarlehenDokumentType,
    AUFSTELLUNG_KOSTEN_ELTERN: 'AUFSTELLUNG_KOSTEN_ELTERN' as DarlehenDokumentType,
    KOPIE_SCHULGELDRECHNUNG: 'KOPIE_SCHULGELDRECHNUNG' as DarlehenDokumentType,
    BELEGE_ANSCHAFFUNGEN: 'BELEGE_ANSCHAFFUNGEN' as DarlehenDokumentType
};

