/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DarlehenStatus } from './darlehenStatus';
import { DarlehenGrund } from './darlehenGrund';

export interface Darlehen { 
    id: string;
    fallId?: string;
    relatedGesuchId?: string;
    status?: DarlehenStatus;
    gewaehren?: boolean;
    betrag?: number;
    kommentar?: string;
    betragGewuenscht?: number;
    schulden?: number;
    anzahlBetreibungen?: number;
    gruende?: Array<DarlehenGrund>;
    isDelegiert?: boolean;
    timestampErstellt?: string;
}



