/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SozialdienstSlim } from './sozialdienstSlim';
import { PersoenlicheAngaben } from './persoenlicheAngaben';
import { SozialdienstBenutzer } from './sozialdienstBenutzer';

export interface Delegierung { 
    id: string;
    sozialdienst?: SozialdienstSlim;
    delegierterMitarbeiter?: SozialdienstBenutzer;
    delegierungAngenommen?: boolean;
    persoenlicheAngaben?: PersoenlicheAngaben;
}

