/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DemoSteuerdaten { 
    totalEinkuenfte: number;
    eigenmietwert: number;
    arbeitsverhaeltnis: string;
    saeule3a: number;
    saeule2: number;
    vermoegen: number;
    steuernKantonGemeinde: number;
    steuernBund: number;
    fahrkosten: number;
    fahrkostenPartner: number;
    verpflegung: number;
    verpflegungPartner: number;
    steuerjahr: number;
    veranlagungsStatus: string;
}

