/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DemoBudgettyp } from './demoBudgettyp';
import { DemoDataTestBudget } from './demoDataTestBudget';
import { DemoDataTestElternBudget } from './demoDataTestElternBudget';

export interface DemoDataTestBerechnungDetails { 
    budgetArt?: DemoBudgettyp;
    elternBudget1?: DemoDataTestElternBudget;
    elternBudget2?: DemoDataTestElternBudget;
    persoenlichesBudget?: DemoDataTestBudget;
    fehlbetrag?: number;
    proKopfteilung?: number;
    anzahlMonateEinreichefrist?: number;
    totalNachKuerzungNachEinreichefrist?: number;
}



