/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ausbildungssituation } from './ausbildungssituation';

export interface DemoKind { 
    nachname: string;
    vorname: string;
    geburtsdatum: string;
    wohnsitzAnteilPia: number;
    ausbildungssituation: Ausbildungssituation;
    unterhaltsbeitraege: number;
    kinderUndAusbildungszulagen: number;
    renten: number;
    ergaenzungsleistungen: number;
    andereEinnahmen: number;
}



