/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ElternUnbekanntheitsGrund } from './elternUnbekanntheitsGrund';
import { Elternschaftsteilung } from './elternschaftsteilung';

export interface DemoFamiliensituation { 
    elternVerheiratetZusammen: boolean;
    gerichtlicheAlimentenregelung?: boolean;
    werZahltAlimente?: Elternschaftsteilung;
    mutterWiederverheiratetAlimente?: boolean;
    vaterWiederverheiratetAlimente?: boolean;
    elternteilUnbekanntVerstorben?: boolean;
    mutterVerstorben?: boolean;
    mutterUnbekannt?: boolean;
    mutterUnbekanntGrund?: ElternUnbekanntheitsGrund;
    mutterKeineOptionen?: boolean;
    mutterWiederverheiratetUnbekannt?: boolean;
    vaterVerstorben?: boolean;
    vaterUnbekannt?: boolean;
    vaterUnbekanntGrund?: ElternUnbekanntheitsGrund;
    vaterKeineOptionen?: boolean;
    vaterWiederverheiratetUnbekannt?: boolean;
    mutterWiederverheiratetUngewiss?: boolean;
    vaterWiederverheiratetUngewiss?: boolean;
}



