/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type DruckauftragStatus = 'DRUCKBEREIT' | 'IN_GENERIERUNG' | 'VERSANDBEREIT';

export const DruckauftragStatus = {
    DRUCKBEREIT: 'DRUCKBEREIT' as DruckauftragStatus,
    IN_GENERIERUNG: 'IN_GENERIERUNG' as DruckauftragStatus,
    VERSANDBEREIT: 'VERSANDBEREIT' as DruckauftragStatus
};

