/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { ElternTyp } from './elternTyp';

export interface Eltern { 
    vorname: string;
    adresse: Adresse;
    identischerZivilrechtlicherWohnsitz: boolean;
    /**
     * Required wenn identischerZivilrechtlicherWohnsitz = false
     */
    identischerZivilrechtlicherWohnsitzOrt?: string;
    /**
     * Required wenn identischerZivilrechtlicherWohnsitz = false
     */
    identischerZivilrechtlicherWohnsitzPLZ?: string;
    telefonnummer: string;
    sozialversicherungsnummer?: string;
    /**
     * dd.MM.yyyy
     */
    geburtsdatum: string;
    ausweisbFluechtling: boolean;
    id?: string;
    elternTyp: ElternTyp;
    nachname: string;
    /**
     * \'Falls steuerdatenTyp = Familie: Ergaenzungsleistungen Vater\' \'Falls steuerdatenTyp != Famile: Ergaenzungsleistungen steuerdatenTyp\' 
     */
    ergaenzungsleistungen?: number;
    sozialhilfebeitraege: boolean;
    /**
     * Die Wohnkosten vom Elternteil, werden gespiegelt auf den anderen falls Sie zusammen wohnen
     */
    wohnkosten?: number;
}



