/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SteuerdatenTyp } from './steuerdatenTyp';

/**
 * Familien Budget daten fuer und von der Berechnung
 */
export interface FamilienBudgetresultat { 
    familienBudgetTyp: SteuerdatenTyp;
    selbststaendigErwerbend: boolean;
    anzahlPersonenImHaushalt: number;
    anzahlGeschwisterInAusbildung: number;
    totalEinkuenfte: number;
    ergaenzungsleistungen: number;
    steuerbaresVermoegen: number;
    anrechenbaresVermoegen: number;
    saeule2: number;
    saeule3a: number;
    eigenmietwert: number;
    alimente: number;
    einnahmenBGSA?: number;
    andereEinnahmen?: number;
    einnahmenFamilienbudget: number;
    grundbedarf: number;
    effektiveWohnkosten: number;
    medizinischeGrundversorgung: number;
    integrationszulage: number;
    steuernBund: number;
    steuernKantonGemeinde: number;
    fahrkostenPerson1: number;
    fahrkostenPerson2: number;
    essenskostenPerson1: number;
    essenskostenPerson2: number;
    ausgabenFamilienbudget: number;
    familienbudgetBerechnet: number;
}



