/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ElternAbwesenheitsGrund } from './elternAbwesenheitsGrund';
import { ElternUnbekanntheitsGrund } from './elternUnbekanntheitsGrund';
import { Elternschaftsteilung } from './elternschaftsteilung';

export interface FamiliensituationUpdate { 
    elternVerheiratetZusammen: boolean;
    elternteilUnbekanntVerstorben?: boolean;
    gerichtlicheAlimentenregelung?: boolean;
    mutterUnbekanntVerstorben?: ElternAbwesenheitsGrund;
    mutterUnbekanntGrund?: ElternUnbekanntheitsGrund;
    mutterWiederverheiratet?: boolean;
    vaterUnbekanntVerstorben?: ElternAbwesenheitsGrund;
    vaterUnbekanntGrund?: ElternUnbekanntheitsGrund;
    vaterWiederverheiratet?: boolean;
    werZahltAlimente?: Elternschaftsteilung;
}



