/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FamilienBudgetresultatEinnahmen { 
    total: number;
    totalEinkuenfte: number;
    einnahmenBGSA: number;
    ergaenzungsleistungen: number;
    andereEinnahmen: number;
    eigenmietwert: number;
    unterhaltsbeitraege: number;
    sauele3: number;
    sauele2: number;
    renten: number;
    einkommensfreibetrag: number;
    zwischentotal: number;
    anrechenbaresVermoegen: number;
    steuerbaresVermoegen: number;
}

