/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationReport } from './validationReport';
import { GesuchTrancheStatus } from './gesuchTrancheStatus';
import { Gesuchstatus } from './gesuchstatus';

export interface GesuchHeaderInfo { 
    gesuchStatus: Gesuchstatus;
    trancheStatus: GesuchTrancheStatus;
    canGetBerechnung: boolean;
    canTriggerManuellPruefen: boolean;
    canBearbeitungAbschliessen: boolean;
    canChangeGesuchsperiode: boolean;
    validationReport?: ValidationReport;
}



