/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GesuchAenderungs } from './gesuchAenderungs';
import { VerfuegtGesuch } from './verfuegtGesuch';
import { GesuchInfo } from './gesuchInfo';
import { GesuchTrancheSlim } from './gesuchTrancheSlim';
import { InitialGesuchs } from './initialGesuchs';

export interface GesuchHeader { 
    initial?: InitialGesuchs;
    versions: Array<VerfuegtGesuch>;
    aenderungs: GesuchAenderungs;
    currentTranches: Array<GesuchTrancheSlim>;
    latestVerfuegungId?: string;
    latestVerfuegtAt?: string;
    gesuchInfo: GesuchInfo;
}

