/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InBearbeitungSbReason } from './inBearbeitungSbReason';
import { Gesuchstatus } from './gesuchstatus';

export interface GesuchStateInfo { 
    gesuchStatus: Gesuchstatus;
    beschwerdeHaengig: boolean;
    canGSGetBerechnung: boolean;
    canSBGetBerechnung: boolean;
    canChangeGesuchsperiode: boolean;
    canTriggerManuellPruefen: boolean;
    canBearbeitungAbschliessen: boolean;
    canSBInitAenderung: boolean;
    inBearbeitungSbReason?: InBearbeitungSbReason;
}



