/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Dokumentstatus } from './dokumentstatus';
import { DokumentTyp } from './dokumentTyp';

/**
 * Kommentar zu einem (abgelehnten) GesuchDokument
 */
export interface GesuchDokumentKommentar { 
    gesuchId: string;
    dokumentTyp: DokumentTyp;
    dokumentStatus?: Dokumentstatus;
    kommentar?: string;
    user_erstellt?: string;
    timestampErstellt?: string;
}



