/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TranchenWithVerfuegung } from './tranchenWithVerfuegung';
import { AenderungenWithVerfuegung } from './aenderungenWithVerfuegung';
import { GesuchTrancheSlim } from './gesuchTrancheSlim';

export interface GesuchHeaderGsHistorized { 
    initial?: TranchenWithVerfuegung;
    offeneAenderung?: GesuchTrancheSlim;
    akzeptierteAenderungen?: Array<AenderungenWithVerfuegung>;
    abgelehnteAenderungen?: Array<GesuchTrancheSlim>;
}

