/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GesuchTranche } from './gesuchTranche';
import { Gesuchstatus } from './gesuchstatus';
import { Gesuchsperiode } from './gesuchsperiode';
import { DelegierungSlim } from './delegierungSlim';

export interface GesuchWithChanges { 
    fallId: string;
    fallNummer: string;
    ausbildungId: string;
    gesuchsperiode: Gesuchsperiode;
    gesuchStatus: Gesuchstatus;
    gesuchNummer: string;
    id: string;
    aenderungsdatum: string;
    /**
     * Zuständiger Sachbearbeiter des Gesuchs
     */
    bearbeiter?: string;
    gesuchTrancheToWorkWith: GesuchTranche;
    einreichedatum?: string;
    delegierung?: DelegierungSlim;
    nachfristDokumente?: string;
    verfuegt: boolean;
    changes?: Array<GesuchTranche>;
    isInitial?: boolean;
}



