/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GueltigkeitStatus } from './gueltigkeitStatus';

export interface Gesuchsperiode { 
    id: string;
    bezeichnungDe: string;
    bezeichnungFr: string;
    gueltigkeitStatus: GueltigkeitStatus;
    gesuchsperiodeStart: string;
    gesuchsperiodeStopp: string;
    /**
     * dd.MM.YYYY
     */
    aufschaltterminStart: string;
    einreichefristNormal?: string;
    einreichefristReduziert?: string;
    gesuchsjahrId: string;
}



