/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GesuchTranche } from './gesuchTranche';
import { Gesuchstatus } from './gesuchstatus';
import { Fall } from './fall';
import { Gesuchsperiode } from './gesuchsperiode';

/**
 * 1 or 2 Aenderungstranche in relation to another Tranche
 */
export interface GesuchWithChanges { 
    changes?: Array<GesuchTranche>;
    fall: Fall;
    gesuchsperiode: Gesuchsperiode;
    gesuchStatus: Gesuchstatus;
    gesuchNummer: number;
    id: string;
    aenderungsdatum: string;
    /**
     * Zuständiger Sachbearbeiter des Gesuchs
     */
    bearbeiter?: string;
    gesuchTrancheToWorkWith: GesuchTranche;
}



