/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Gesuchstatus = 'IN_BEARBEITUNG_GS' | 'KOMPLETT_EINGEREICHT' | 'BEREIT_FUER_BEARBEITUNG' | 'FEHLERHAFT' | 'IN_BEARBEITUNG_SB' | 'IN_REVIEW' | 'FEHLENDE_DOKUMENTE' | 'FEHLENDE_DOKUMENTE_NACHFRIST' | 'ZURUECKGEZOGEN' | 'ABKLAERUNG_MIT_GS' | 'IN_FREIGABE' | 'ZURUECKGEWIESEN' | 'WARTEN_AUF_UNTERSCHRIFTENBLATT' | 'NEGATIVER_ENTSCHEID' | 'VERFUEGT' | 'STIPENDIUM_AKZEPTIERT' | 'STIPENDIUM_AUSBEZAHLT';

export const Gesuchstatus = {
    IN_BEARBEITUNG_GS: 'IN_BEARBEITUNG_GS' as Gesuchstatus,
    KOMPLETT_EINGEREICHT: 'KOMPLETT_EINGEREICHT' as Gesuchstatus,
    BEREIT_FUER_BEARBEITUNG: 'BEREIT_FUER_BEARBEITUNG' as Gesuchstatus,
    FEHLERHAFT: 'FEHLERHAFT' as Gesuchstatus,
    IN_BEARBEITUNG_SB: 'IN_BEARBEITUNG_SB' as Gesuchstatus,
    IN_REVIEW: 'IN_REVIEW' as Gesuchstatus,
    FEHLENDE_DOKUMENTE: 'FEHLENDE_DOKUMENTE' as Gesuchstatus,
    FEHLENDE_DOKUMENTE_NACHFRIST: 'FEHLENDE_DOKUMENTE_NACHFRIST' as Gesuchstatus,
    ZURUECKGEZOGEN: 'ZURUECKGEZOGEN' as Gesuchstatus,
    ABKLAERUNG_MIT_GS: 'ABKLAERUNG_MIT_GS' as Gesuchstatus,
    IN_FREIGABE: 'IN_FREIGABE' as Gesuchstatus,
    ZURUECKGEWIESEN: 'ZURUECKGEWIESEN' as Gesuchstatus,
    WARTEN_AUF_UNTERSCHRIFTENBLATT: 'WARTEN_AUF_UNTERSCHRIFTENBLATT' as Gesuchstatus,
    NEGATIVER_ENTSCHEID: 'NEGATIVER_ENTSCHEID' as Gesuchstatus,
    VERFUEGT: 'VERFUEGT' as Gesuchstatus,
    STIPENDIUM_AKZEPTIERT: 'STIPENDIUM_AKZEPTIERT' as Gesuchstatus,
    STIPENDIUM_AUSBEZAHLT: 'STIPENDIUM_AUSBEZAHLT' as Gesuchstatus
};

