/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GueltigkeitStatus } from './gueltigkeitStatus';

export interface Gesuchsperiode { 
    id: string;
    bezeichnungDe: string;
    bezeichnungFr: string;
    gueltigAb: string;
    gueltigBis: string;
    einreichfrist?: string;
    aufschaltdatum?: string;
    status: GueltigkeitStatus;
}



