/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GesuchDashboardItemMissingDocuments } from './gesuchDashboardItemMissingDocuments';
import { Gesuchstatus } from './gesuchstatus';
import { Gesuchsperiode } from './gesuchsperiode';
import { GesuchTrancheSlim } from './gesuchTrancheSlim';

export interface GesuchDashboardItem { 
    gesuchsperiode: Gesuchsperiode;
    gesuchStatus: Gesuchstatus;
    id: string;
    offeneAenderung?: GesuchTrancheSlim;
    missingDocuments?: GesuchDashboardItemMissingDocuments;
}



