/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type GesuchNotizTyp = 'PENDENZ_NOTIZ' | 'GESUCH_NOTIZ' | 'JURISTISCHE_NOTIZ';

export const GesuchNotizTyp = {
    PENDENZ_NOTIZ: 'PENDENZ_NOTIZ' as GesuchNotizTyp,
    GESUCH_NOTIZ: 'GESUCH_NOTIZ' as GesuchNotizTyp,
    JURISTISCHE_NOTIZ: 'JURISTISCHE_NOTIZ' as GesuchNotizTyp
};

