/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type GetDarlehenSBQueryType = 'ALLE_DARLEHEN' | 'MEINE_DARLEHEN';

export const GetDarlehenSBQueryType = {
    ALLE_DARLEHEN: 'ALLE_DARLEHEN' as GetDarlehenSBQueryType,
    MEINE_DARLEHEN: 'MEINE_DARLEHEN' as GetDarlehenSBQueryType
};

