/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type GetDelegierungSozQueryTypeMa = 'ALLE_BEARBEITBAR_MEINE' | 'ALLE';

export const GetDelegierungSozQueryTypeMa = {
    ALLE_BEARBEITBAR_MEINE: 'ALLE_BEARBEITBAR_MEINE' as GetDelegierungSozQueryTypeMa,
    ALLE: 'ALLE' as GetDelegierungSozQueryTypeMa
};

