/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersoenlichesBudgetresultatKosten } from './persoenlichesBudgetresultatKosten';
import { PersoenlichesBudgetresultatEinnahmen } from './persoenlichesBudgetresultatEinnahmen';

/**
 * Persoenliche Budget daten fuer und von der Berechnung
 */
export interface PersoenlichesBudgetresultat { 
    vorname: string;
    nachname: string;
    vornamePartner?: string;
    nachnamePartner?: string;
    sozialversicherungsnummer: string;
    /**
     * dd.MM.yyyy
     */
    geburtsdatum: string;
    total: number;
    einnahmenMinusKosten: number;
    fehlbetrag: number;
    proKopfTeilung: number;
    eigenerHaushalt: boolean;
    budgetTranche: number;
    anzahlMonate: number;
    gesetzlichesDarlehen: number;
    gesetzlichesDarlehenStipendium: number;
    anzahlPersonenImHaushalt: number;
    einnahmen: PersoenlichesBudgetresultatEinnahmen;
    kosten: PersoenlichesBudgetresultatKosten;
}

