/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Persoenliche Budget daten fuer und von der Berechnung
 */
export interface PersoenlichesBudgetresultat { 
    anzahlPersonenImHaushalt: number;
    eigenerHaushalt: boolean;
    anteilLebenshaltungskosten: number;
    einkommen: number;
    leistungenEO: number;
    rente: number;
    kinderAusbildungszulagen: number;
    ergaenzungsleistungen: number;
    gemeindeInstitutionen: number;
    vermoegen: number;
    anteilFamilienbudget: number;
    einkommenPartner: number;
    einnahmenPersoenlichesBudget: number;
    grundbedarf: number;
    wohnkosten: number;
    medizinischeGrundversorgung: number;
    steuernKantonGemeinde: number;
    fahrkosten: number;
    fahrkostenPartner: number;
    verpflegung: number;
    verpflegungPartner: number;
    fremdbetreuung: number;
    ausbildungskosten: number;
    ausgabenPersoenlichesBudget: number;
    persoenlichesbudgetBerechnet: number;
}

