/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonValueItem } from './personValueItem';

/**
 * Persoenliche Budget daten fuer und von der Berechnung
 */
export interface PersoenlichesBudgetresultatKosten { 
    total: number;
    ausbildungskosten: number;
    fahrkosten: number;
    verpflegungskosten: number;
    grundbedarf: number;
    wohnkosten: number;
    medizinischeGrundversorgung: Array<PersonValueItem>;
    medizinischeGrundversorgungTotal: number;
    fahrkostenPartner: number;
    verpflegungPartner: number;
    betreuungskostenKinder: number;
    kantonsGemeindesteuern: number;
    bundessteuern: number;
    anteilLebenshaltungskosten: number;
}

