/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type SapStatus = 'SUCCESS' | 'FAILURE' | 'IN_PROGRESS';

export const SapStatus = {
    SUCCESS: 'SUCCESS' as SapStatus,
    FAILURE: 'FAILURE' as SapStatus,
    IN_PROGRESS: 'IN_PROGRESS' as SapStatus
};

