/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type SbDarlehenDashboardColumn = 'FALLNUMMER' | 'PIA_NACHNAME' | 'PIA_VORNAME' | 'PIA_GEBURTSDATUM' | 'STATUS' | 'BEARBEITER' | 'LETZTE_AKTIVITAET';

export const SbDarlehenDashboardColumn = {
    FALLNUMMER: 'FALLNUMMER' as SbDarlehenDashboardColumn,
    PIA_NACHNAME: 'PIA_NACHNAME' as SbDarlehenDashboardColumn,
    PIA_VORNAME: 'PIA_VORNAME' as SbDarlehenDashboardColumn,
    PIA_GEBURTSDATUM: 'PIA_GEBURTSDATUM' as SbDarlehenDashboardColumn,
    STATUS: 'STATUS' as SbDarlehenDashboardColumn,
    BEARBEITER: 'BEARBEITER' as SbDarlehenDashboardColumn,
    LETZTE_AKTIVITAET: 'LETZTE_AKTIVITAET' as SbDarlehenDashboardColumn
};

