/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type SbGesucheDashboardColumn = 'FALLNUMMER' | 'TYP' | 'PIA_NACHNAME' | 'PIA_VORNAME' | 'PIA_GEBURTSDATUM' | 'STATUS' | 'BEARBEITER' | 'LETZTE_AKTIVITAET';

export const SbGesucheDashboardColumn = {
    FALLNUMMER: 'FALLNUMMER' as SbGesucheDashboardColumn,
    TYP: 'TYP' as SbGesucheDashboardColumn,
    PIA_NACHNAME: 'PIA_NACHNAME' as SbGesucheDashboardColumn,
    PIA_VORNAME: 'PIA_VORNAME' as SbGesucheDashboardColumn,
    PIA_GEBURTSDATUM: 'PIA_GEBURTSDATUM' as SbGesucheDashboardColumn,
    STATUS: 'STATUS' as SbGesucheDashboardColumn,
    BEARBEITER: 'BEARBEITER' as SbGesucheDashboardColumn,
    LETZTE_AKTIVITAET: 'LETZTE_AKTIVITAET' as SbGesucheDashboardColumn
};

