/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type SozDashboardColumn = 'FALLNUMMER' | 'NACHNAME' | 'VORNAME' | 'GEBURTSDATUM' | 'WOHNORT' | 'DELEGIERUNG_ANGENOMMEN' | 'LETZTE_AKTIVITAET';

export const SozDashboardColumn = {
    FALLNUMMER: 'FALLNUMMER' as SozDashboardColumn,
    NACHNAME: 'NACHNAME' as SozDashboardColumn,
    VORNAME: 'VORNAME' as SozDashboardColumn,
    GEBURTSDATUM: 'GEBURTSDATUM' as SozDashboardColumn,
    WOHNORT: 'WOHNORT' as SozDashboardColumn,
    DELEGIERUNG_ANGENOMMEN: 'DELEGIERUNG_ANGENOMMEN' as SozDashboardColumn,
    LETZTE_AKTIVITAET: 'LETZTE_AKTIVITAET' as SozDashboardColumn
};

