/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Zahlungsverbindung } from './zahlungsverbindung';
import { SozialdienstBenutzer } from './sozialdienstBenutzer';

export interface Sozialdienst { 
    id: string;
    name: string;
    aktiv: boolean;
    sozialdienstAdmin: SozialdienstBenutzer;
    zahlungsverbindung: Zahlungsverbindung;
}

