/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Statistik { 
    id: string;
    timestampErstellt: string;
    valid: boolean;
    userTriggeredCreation: string;
    year: number;
    error?: string;
    filename?: string;
    filesize?: string;
}

