/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Taetigkeitsart = 'ERWERBSTAETIGKEIT' | 'ANDERE_TAETIGKEIT' | 'BETREUUNG_FAMILIENMITGLIEDER_EIGENER_HAUSHALT';

export const Taetigkeitsart = {
    ERWERBSTAETIGKEIT: 'ERWERBSTAETIGKEIT' as Taetigkeitsart,
    ANDERE_TAETIGKEIT: 'ANDERE_TAETIGKEIT' as Taetigkeitsart,
    BETREUUNG_FAMILIENMITGLIEDER_EIGENER_HAUSHALT: 'BETREUUNG_FAMILIENMITGLIEDER_EIGENER_HAUSHALT' as Taetigkeitsart
};

