/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BerechnungsStammdaten } from './berechnungsStammdaten';
import { FamilienBudgetresultat } from './familienBudgetresultat';
import { PersoenlichesBudgetresultat } from './persoenlichesBudgetresultat';

/**
 * Resultat der Berechnung (eine Tranche)
 */
export interface TranchenBerechnungsresultat { 
    /**
     * Berechneter Stpendiumsanspruch für diese Tranche
     */
    berechnungAnteilStipendium: number;
    /**
     * Berechneter Darlehensanspruch für diese Tranche
     */
    berechnungAnteilDarlehen: number;
    gueltigAb: string;
    gueltigBis: string;
    ausbildungAb: string;
    ausbildungBis: string;
    gesuchTrancheId: string;
    /**
     * Anteil dieser Berechnung am Berechnungstotal. Für Tranchen welche nur eine Berechnung haben ist dieser wert == 1.
     */
    berechnungsanteilKinder: number;
    berechnungsStammdaten: BerechnungsStammdaten;
    persoenlichesBudgetresultat: PersoenlichesBudgetresultat;
    /**
     * Berechnungsdaten der Familienbudgets
     */
    familienBudgetresultate: Array<FamilienBudgetresultat>;
}

