/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BerechnungsStammdaten } from './berechnungsStammdaten';
import { FamilienBudgetresultat } from './familienBudgetresultat';
import { PersoenlichesBudgetresultat } from './persoenlichesBudgetresultat';
import { PersonenHaushaltGruppe } from './personenHaushaltGruppe';

/**
 * Resultat der Berechnung (eine Tranche)
 */
export interface TranchenBerechnungsresultat { 
    /**
     * Die Summe der berechneten Stpendiums- und Darlehensansprüche für diese Tranche
     */
    total: number;
    /**
     * Die ungekürzte Summe der berechneten Stpendiums- und Darlehensansprüche für diese Tranche
     */
    ungekuerztTotal: number;
    gueltigAb: string;
    gueltigBis: string;
    ausbildungAb: string;
    ausbildungBis: string;
    yearRange: string;
    gesuchTrancheId: string;
    /**
     * Anteil dieser Berechnung am Berechnungstotal. Für Tranchen welche nur eine Berechnung haben ist dieser Wert null.
     */
    berechnungsanteilKinder?: number;
    /**
     * Werden kinder der PiA bei der berechnung dieser Tranche dem Budget der PiA angerechnet
     */
    teilzeitKinderBeiPiaAnrechnen: boolean;
    /**
     * Anteil dieser Berechnung am Berechnungstotal. Für Tranchen welche nur eine Berechnung haben ist dieser Wert null.
     */
    berechnungsanteilKinderPia?: number;
    berechnungsStammdaten: BerechnungsStammdaten;
    persoenlichesBudgetresultat: PersoenlichesBudgetresultat;
    /**
     * Berechnungsdaten der Familienbudgets
     */
    familienBudgetresultate: Array<FamilienBudgetresultat>;
    /**
     * Enthällt eine Liste aller relevanten Personen für die jeweiligen Personen Haushalt Gruppen
     */
    personenHaushaltGroups: Array<PersonenHaushaltGruppe>;
}

