/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationMessage } from './validationMessage';

export interface ValidationReport { 
    validationErrors: Array<ValidationMessage>;
    validationWarnings: Array<ValidationMessage>;
    /**
     * Whether or not the Gesuch validated has one or more GesuchDokument attached
     */
    hasDocuments?: boolean;
}

