/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type VerfuegungDokumentTyp = 'BERECHNUNGSBLATT_PIA' | 'BERECHNUNGSBLATT_MUTTER' | 'BERECHNUNGSBLATT_VATER' | 'BERECHNUNGSBLATT_FAMILIE' | 'BERECHNUNGSBLATT_ALLE' | 'VERSENDETE_VERFUEGUNG' | 'VERFUEGUNGSBRIEF';

export const VerfuegungDokumentTyp = {
    BERECHNUNGSBLATT_PIA: 'BERECHNUNGSBLATT_PIA' as VerfuegungDokumentTyp,
    BERECHNUNGSBLATT_MUTTER: 'BERECHNUNGSBLATT_MUTTER' as VerfuegungDokumentTyp,
    BERECHNUNGSBLATT_VATER: 'BERECHNUNGSBLATT_VATER' as VerfuegungDokumentTyp,
    BERECHNUNGSBLATT_FAMILIE: 'BERECHNUNGSBLATT_FAMILIE' as VerfuegungDokumentTyp,
    BERECHNUNGSBLATT_ALLE: 'BERECHNUNGSBLATT_ALLE' as VerfuegungDokumentTyp,
    VERSENDETE_VERFUEGUNG: 'VERSENDETE_VERFUEGUNG' as VerfuegungDokumentTyp,
    VERFUEGUNGSBRIEF: 'VERFUEGUNGSBRIEF' as VerfuegungDokumentTyp
};

