/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type VerfuegungStatus = 'AUSSTEHEND' | 'ANSPRUCH' | 'KEIN_ANSPRUCH' | 'NEGATIV';

export const VerfuegungStatus = {
    AUSSTEHEND: 'AUSSTEHEND' as VerfuegungStatus,
    ANSPRUCH: 'ANSPRUCH' as VerfuegungStatus,
    KEIN_ANSPRUCH: 'KEIN_ANSPRUCH' as VerfuegungStatus,
    NEGATIV: 'NEGATIV' as VerfuegungStatus
};

