ARG TYPST_VERSION=0.15.1

FROM docker-registry.dvbern.ch/ghcr/typst/typst:$TYPST_VERSION AS typst

FROM docker-registry.dvbern.ch/redhat/ubi8/openjdk-21:1.18

ENV LANGUAGE='en_US:en'
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

COPY --from=typst --chmod=0755 /bin/typst /usr/local/bin/typst

# Typst templates and fonts must be on the filesystem (Typst can't read from inside a JAR)
COPY --chown=185 target/classes/typst/ /deployments/typst/
COPY --chown=185 target/classes/fonts/ /deployments/fonts/

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

USER 185

EXPOSE 8080
