apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: identity-secrets
  namespace: stip-dev
spec:
  encryptedData:
    password: AgCBTTIUtcdDCzaT5MTVDcGu+ydunIkIWRd5Mnz/PisQY891T8OLUX6NI4KbPRT9LQ2CLQtJSJzL840AerDGTNMXWvuRB91adiEE8nU9BfrXa5Uw2OOkdfYpHwPsjsAJlA2lOCcVMy7I21TIdli/DQdnjMRkfe5hQQbJ7blBN6qJN9WGXKjtZ6Yzlel2BazvN7+4IgljdxC5CKTFi8I3VhKD+crHnEYLUXsnd+XkaBPd1B3NlGTj4+0R3VtEcoOaQpzOnS7kMrqTH0andhcFgrDooM2ZQ6aKvVliiKIFW5M8DUpUJO3FgMEXZG5wJhbLK2YJ5jJlAkK2Hr2KWkRBgZjJcJA0aW3FOudZLokHz88zbCuw/bVJ2qSM/NWheMW/xuGQyJE3jq6hv/JOoVHkvTanGixNSYApXVPznwhcCV9OFbcL7w8FrfO2uX5q/PiukpMwhu+CZrTrsoyM6xDI0rf4DLDst8IeegMhYaWhlIJI4+V6kfDXd2a5wKrowmMhm3TJzImCfex2NgbGr5p97t62E/U1MWXxqj8nNJBtIlj8IU7RD43ueh+GWFhvxoiYhxgwDPXnMcU9AbFrIJaVZ9miImQ6oqU+GWqwO+VbDlQjZTxPFA8rayF9g3ILkOdxTrpFa+ZtrjsQNIyYOsKy7WQyLaiQ2V/2a7d8F5VkToHFAfXkJ+qXIg0EyVt30/67Ie9jn3jyegjut4NUJkyg8TgHy2jk0Q==
    username: AgABvGuuNskYXwmQiLCkTeuGa+rkHyQV0OllmOo1Q6CyG8c1RabNtMWQphqkiFkcCC1/+Ry5Rf28zviooc7Pg7dyQBD2F7Qq17x1o/xOOrvzj4JngXc9CqfQdg2ULhtDJaEH6VgZzSX2y6hXbYuvai2sW1GTNKD27oYd+U1+I6Qde7P5c9SbbUBEblbfvOx19nd57NIOOv975w4P5F9pYjjbai/gtTKbNCxjZtbDLZ39xcT46kGjEr95xr0al1DrOx+MTOj+notAYZ7l+Dl5RoPrTss6FgAoLb7S03EURyJ7Lgn3Rd3R/4kQqDiqc68gq3GZt+AusbdbPiJGiYVAb20tdWzu3UQf/t0rRouTJTudUQenyYNOo57a25Yg0mZDaqg9eBZyTy+Zh599Msj5RIrl5vK9sF5QnENcwT+1lstdcEbwZU3i3CeBNj42Xh0m2R07+uXL56Q4hHQoxn/vM9x5QgM9OVaeqTPnlcLhby9iLwf78sinLbucJqnnET5MaU42XSCX6wU+KpSK+Mro/9bLKb8RsJuk+qBC2safAJMInm/wTPvoeBqappvysS94sfL9ONH/hTcCBKp8freAiqNWou/60KwiTb0YxjLOQjhW+ZhhTQGNvL3EQ0kZH8jLItCn5T4zXlm1dqPFki0errlWueXZVcuO3g220yAgJ2Hwab4SMPBKCkMsSg0RaDc9jBlAIM2Hfw==
  template:
    metadata:
      creationTimestamp: null
      name: identity-secrets
      namespace: stip-dev
    type: Opaque

