package ch.dvbern.stip.api.dokument.type;

public enum DokumentTyp {
    PERSON_NIEDERLASSUNGSSTATUS_C,
    PERSON_NIEDERLASSUNGSSTATUS_B,
    PERSON_NIEDERLASSUNGSSTATUS_COMPLETE,
    PERSON_KESB_ERNENNUNG,
    PERSON_MIETVERTRAG,
    PERSON_VERMOEGENSNACHWEIS_VORJAHR,
    PERSON_SOZIALHILFEBUDGET,
    PERSON_TRENNUNG_ODER_UNTERHALTS_BELEG,
    PERSON_AUSWEIS,
    PERSON_VERMOEGENSNACHWEIS,
    AUSBILDUNG_DOK,
    ELTERN_DOK,
    PARTNER_DOK
}
