/*
 * Copyright (C) 2023 DV Bern AG, Switzerland
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package ch.dvbern.stip.api.dokument.type;

public enum DokumentTyp {
    AUSBILDUNG_BESTAETIGUNG_AUSBILDUNGSSTAETTE,
    PERSON_NIEDERLASSUNGSSTATUS_C,
    PERSON_NIEDERLASSUNGSSTATUS_B,
    PERSON_NIEDERLASSUNGSSTATUS_SAISONARBEITEND_A,
    PERSON_NIEDERLASSUNGSSTATUS_PARTNER_ERWERBSTAETIG_UND_KIND_CI,
    PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_OHNE_FLUECHTLINGSSTATUS,
    PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ZUESTAENDIGER_KANTON_MANDANT,
    PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ANDERER_ZUESTAENDIGER_KANTON,
    PERSON_NIEDERLASSUNGSSTATUS_GRENZGAENGIG_G,
    PERSON_NIEDERLASSUNGSSTATUS_KURZAUFENTHALT_L,
    PERSON_NIEDERLASSUNGSSTATUS_ASYLSUCHEND_N,
    PERSON_NIEDERLASSUNGSSTATUS_SCHUTZBEDUERFTIG_S,
    PERSON_NIEDERLASSUNGSSTATUS_MELDEPFLICHTIG,
    PERSON_NIEDERLASSUNGSSTATUS_DIPLOMATISCHE_FUNKTION,
    PERSON_NIEDERLASSUNGSSTATUS_INTERNATIONALE_FUNKTION,
    PERSON_NIEDERLASSUNGSSTATUS_NICHT_ZUGETEILT,
    PERSON_BEGRUENDUNGSSCHREIBEN_ALTER_AUSBILDUNGSBEGIN,
    PERSON_KESB_ERNENNUNG,
    PERSON_MIETVERTRAG,
    PERSON_SOZIALHILFEBUDGET,
    PERSON_TRENNUNG_ODER_UNTERHALTS_BELEG,
    PERSON_AUSWEIS,
    FAMILIENSITUATION_GEBURTSSCHEIN,
    FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_VATER,
    FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_MUTTER,
    FAMILIENSITUATION_TRENNUNGSKONVENTION,
    ELTERN_SOZIALHILFEBUDGET_VATER,
    ELTERN_SOZIALHILFEBUDGET_MUTTER,
    ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_VATER,
    ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_MUTTER,
    ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_FAMILIE,
    GESCHWISTER_BESTAETIGUNG_AUSBILDUNGSSTAETTE,
    KINDER_UNTERHALTSVERTRAG_TRENNUNGSKONVENTION,
    KINDER_ALIMENTENVERORDUNG,
    KINDER_ERGAENZUNGSLEISTUNGEN,
    KINDER_UND_AUSBILDUNGSZULAGEN,
    KINDER_RENTEN,
    KINDER_ANDERE_EINNAHMEN,
    EK_BELEG_UNTERHALTSBEITRAEGE,
    EK_BELEG_EINNAHMEN_BGSA,
    EK_BELEG_TAGGELDER_AHV_IV,
    EK_BELEG_ANDERE_EINNAHMEN,
    EK_BELEG_KINDERZULAGEN,
    EK_VERFUEGUNG_GEMEINDE_INSTITUTION,
    EK_BELEG_BEZAHLTE_RENTEN,
    EK_VERFUEGUNG_ERGAENZUNGSLEISTUNGEN,
    EK_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO,
    EK_BELEG_OV_ABONNEMENT,
    EK_MIETVERTRAG,
    EK_BELEG_BETREUUNGSKOSTEN_KINDER,
    EK_LOHNABRECHNUNG,
    EK_VERMOEGEN,
    EK_PARTNER_BELEG_UNTERHALTSBEITRAEGE,
    EK_PARTNER_BELEG_EINNAHMEN_BGSA,
    EK_PARTNER_BELEG_TAGGELDER_AHV_IV,
    EK_PARTNER_BELEG_ANDERE_EINNAHMEN,
    EK_PARTNER_BELEG_KINDERZULAGEN,
    EK_PARTNER_VERFUEGUNG_GEMEINDE_INSTITUTION,
    EK_PARTNER_BELEG_BEZAHLTE_RENTEN,
    EK_PARTNER_VERFUEGUNG_ERGAENZUNGSLEISTUNGEN,
    EK_PARTNER_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO,
    EK_PARTNER_BELEG_OV_ABONNEMENT,
    EK_PARTNER_BELEG_BETREUUNGSKOSTEN_KINDER,
    EK_PARTNER_LOHNABRECHNUNG,
    EK_PARTNER_VERMOEGEN,
    DARLEHEN_BETREIBUNGSREGISTERAUSZUG,
    DARLEHEN_AUFSTELLUNG_KOSTEN_ELTERN,
    DARLEHEN_KOPIE_SCHULGELDRECHNUNG,
    DARLEHEN_BELEGE_ANSCHAFFUNGEN,
    STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_VATER,
    STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_MUTTER,
    STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_FAMILIE,
    STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_VATER,
    STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_MUTTER,
    STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_FAMILIE,
    STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_VATER,
    STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_MUTTER,
    STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_FAMILIE,
    STEUERERKLAERUNG_RENTEN_VATER,
    STEUERERKLAERUNG_RENTEN_MUTTER,
    STEUERERKLAERUNG_RENTEN_FAMILIE,
    STEUERERKLAERUNG_EINNAHMEN_BGSA_VATER,
    STEUERERKLAERUNG_EINNAHMEN_BGSA_MUTTER,
    STEUERERKLAERUNG_EINNAHMEN_BGSA_FAMILIE,
    STEUERERKLAERUNG_ANDERE_EINNAHMEN_VATER,
    STEUERERKLAERUNG_ANDERE_EINNAHMEN_MUTTER,
    STEUERERKLAERUNG_ANDERE_EINNAHMEN_FAMILIE
}
