/*
 * Copyright (C) 2023 DV Bern AG, Switzerland
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package ch.dvbern.stip.api.dokument.type;

public enum DokumentTyp {
    AUSBILDUNG_BESTAETIGUNG_AUSBILDUNGSSTAETTE,
    PERSON_NIEDERLASSUNGSSTATUS_C,
    PERSON_NIEDERLASSUNGSSTATUS_B,
    PERSON_NIEDERLASSUNGSSTATUS_COMPLETE,
    PERSON_KESB_ERNENNUNG,
    PERSON_MIETVERTRAG,
    PERSON_SOZIALHILFEBUDGET,
    PERSON_TRENNUNG_ODER_UNTERHALTS_BELEG,
    PERSON_AUSWEIS,
    FAMILIENSITUATION_GEBURTSSCHEIN,
    FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_VATER,
    FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_MUTTER,
    FAMILIENSITUATION_TRENNUNGSKONVENTION,
    ELTERN_ERGAENZUNGSLEISTUNGEN_VATER,
    ELTERN_ERGAENZUNGSLEISTUNGEN_MUTTER,
    ELTERN_SOZIALHILFEBUDGET_VATER,
    ELTERN_SOZIALHILFEBUDGET_MUTTER,
    ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_VATER,
    ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_MUTTER,
    ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_FAMILIE,
    GESCHWISTER_BESTAETIGUNG_AUSBILDUNGSSTAETTE,
    KINDER_BESTAETIGUNG_AUSBILDUNGSSTAETTE,
    KINDER_UNTERHALTSVERTRAG_TRENNUNGSKONVENTION,
    KINDER_ALIMENTENVERORDUNG,
    PARTNER_AUSBILDUNG_LOHNABRECHNUNG,
    PARTNER_BELEG_OV_ABONNEMENT,
    AUSZAHLUNG_ABTRETUNGSERKLAERUNG,
    EK_BELEG_ALIMENTE,
    EK_BELEG_KINDERZULAGEN,
    EK_VERFUEGUNG_GEMEINDE_INSTITUTION,
    EK_BELEG_BEZAHLTE_RENTEN,
    EK_VERFUEGUNG_ERGAENZUNGSLEISTUNGEN,
    EK_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO,
    EK_BELEG_OV_ABONNEMENT,
    EK_MIETVERTRAG,
    EK_BELEG_BETREUUNGSKOSTEN_KINDER,
    EK_LOHNABRECHNUNG,
    EK_VERDIENST,
    EK_VERMOEGEN,
    DARLEHEN_BETREIBUNGSREGISTERAUSZUG,
    DARLEHEN_AUFSTELLUNG_KOSTEN_ELTERN,
    DARLEHEN_KOPIE_SCHULGELDRECHNUNG,
    DARLEHEN_BELEGE_ANSCHAFFUNGEN,
    STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_VATER,
    STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_MUTTER,
    STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_FAMILIE,
}
