#!/bin/sh
contract="$(git rev-parse --show-toplevel)/contract"
backend="$(git rev-parse --show-toplevel)/backend"
frontend="$(git rev-parse --show-toplevel)/frontend"

export NX_TUI=false

hasChanges() {
    ! git diff --quiet --stat HEAD -- $1
}

if hasChanges $contract; then
    echo "[hooks] contract has unstaged changes, running linting"
    cd $contract

    npm run build:no-output -- -o .temp_openapi.yaml
    SUM=$(cat .temp_openapi.yaml | md5)
    SUM_GENERATED=$(cat openapi.yaml | md5)
    rm .temp_openapi.yaml
    if [ "$SUM" = "$SUM_GENERATED" ]; then
        echo "[hooks] contract is up to date, running lint"
    else
        echo "[hooks] ERROR: contract build has not been generated, please run 'npm run build' to generate the contract"
        exit 1
    fi
    npm run lint
fi

if hasChanges $frontend; then
    echo "[hooks] frontend has unstaged changes, linting, validating and running tests"
    cd $frontend

    npx lint-staged
    npm run validate
    npm run lint:without-progress
    npm run test:changed
    npm run build
fi

if hasChanges $backend; then
    echo "[hooks] backend has unstaged changes, running spotless:check"
    cd $backend

    if command -v mvnd 2>&1 >/dev/null
    then
        echo "[hooks] maven daemon found, using that"
        mvnd spotless:check
    else
        echo "[hooks] maven daemon not found, using wrapper"
        ./mvnw spotless:check
    fi
fi
