stages:
  - publish

npm:
  image: node:lts
  tags: [ "zone:tz", "type:docker", "os:linux" ]
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish