include:
  - project: 'devops/gitlab/templates'
    file:
      - '/maven/maven-3-jdk-17.gitlab-ci.yml'
      - '/maven/maven-base.gitlab-ci.yml'
      - '/docker/docker.gitlab-ci.yml'

stages:
  - build
  - analyze
  - deploy
  - mirror

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
      variables:
        VERSION: $CI_COMMIT_SHORT_SHA
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: $CI_COMMIT_TAG


variables:
  IMAGE: ${DVB_PUBLIC_DOCKER_REGISTRY}/${CI_PROJECT_ROOT_NAMESPACE}/stip/api:${VERSION}


maven-build:
  variables:
    MAVEN_ARGS: -Pcoverage
  rules: 
  - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  - if: "$CI_COMMIT_TAG"
  - if: "$CI_COMMIT_BRANCH"

sonarqube-check:
  image: "${DVB_DOCKER_REGISTRY}/dockerhub/library/maven:3.8-eclipse-temurin-17"
  stage: analyze
  tags: [ "os:linux", "type:docker", "zone:tz" ]
  extends: .maven-build-base
  variables:
    MAVEN_IMAGE_TAG: 3.8-eclipse-temurin-11
    SONAR_PROJECT_KEY: kibon_stip-api_AYkrwku6SZqri_oH9Xle
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_ARGS sonar:sonar -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.qualitygate.wait=true
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH
  needs:
    - job: maven-build
      artifacts: true

build-image:
  extends: .docker-build
  variables:
    IMAGE_PATH: $IMAGE
    DOCKERFILE_PATH: src/main/docker/Dockerfile.jvm
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
      variables:
        KANIKO_ARGS: '--no-push'
  needs:
    - job: maven-build
      artifacts: true


.default-clone: &default-clone
  before_script:
    - rm -rf ./*
    - git clone --branch $CI_DEFAULT_BRANCH --single-branch https://deploy:$DEPLOYMENT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git .
    - git checkout $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  image: "${DVB_DOCKER_REGISTRY}/devops/docker/tools/k8s/main"
  tags: [ "os:linux", "type:docker", "zone:tz" ]
  variables:
    GIT_STRATEGY: none
    STAGE: dev
  <<: *default-clone
  script:
    - cd deploy/$STAGE
    - kustomize edit set image $IMAGE
    - "git commit -a -m \"ci($STAGE): deploy image $IMAGE\""
    - git push -o ci.skip origin HEAD:$CI_DEFAULT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        STAGE: dev
    - if: $CI_COMMIT_TAG
      when: manual
      variables:
        STAGE: uat
  
mirror:
  stage: mirror
  image: 
    name: "${DVB_DOCKER_REGISTRY}/dockerhub/alpine/git:2.40.1"
    entrypoint: [""]
  tags: [ "os:linux", "type:docker", "zone:tz" ]
  variables:
    GIT_STRATEGY: none
  <<: *default-clone
  script:
    - git push -u https://token:${GITHUB_MIRROR_TOKEN}@github.com/dvbern/stip-api.git $CI_DEFAULT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
  needs:
    - job: deploy
