# WIP

include:
  - project: 'devops/gitlab/templates'
    file:
      - '/docker/docker.gitlab-ci.yml'

stages:
  - build
  - deploy

variables:
  IMAGE: ${DVB_DOCKER_REGISTRY}/${CI_PROJECT_ROOT_NAMESPACE}/stip/gesuch-app:${CI_COMMIT_SHORT_SHA}

.base:
  image: docker-registry.dvbern.ch/devops/docker/buildenvs/node/18
  tags: ['os:linux', 'zone:tz', 'type:docker']
  variables:
    HUSKY_SKIP_INSTALL: 1
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --legacy-peer-deps --cache=".npm" --ignore-scripts

build:gesuch-app:
  stage: build
  extends: .base
  script:
    - npm run build:gesuch-app
  artifacts:
    paths:
      - 'dist/apps/gesuch-app'
    when: on_success
    expire_in: '1 day'

build:gesuch-app:image:
  extends: .docker-build
  variables:
    IMAGE_PATH: $IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH
      variables:
        KANIKO_ARGS: '--no-push'
  needs:
    - job: build:gesuch-app
      artifacts: true

deploy:
  stage: deploy
  image: '${DVB_DOCKER_REGISTRY}/devops/docker/tools/k8s/main'
  tags: ['os:linux', 'type:docker', 'zone:tz']
  variables:
    STAGE: dev
  script:
    - git fetch origin $CI_COMMIT_BRANCH
    - cd deploy/$STAGE
    - kustomize edit set image $IMAGE
    - 'git commit --no-verify -a -m "ci($STAGE): deploy image $IMAGE [ci skip]"'
    - git push -o ci.skip https://deploy:$DEPLOYMENT_TOKEN@github.com/dvbern/stip-frontend.git HEAD:$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
