include:
  - project: 'devops/gitlab/templates'
    file:
      - '/maven/maven-3-jdk-17.gitlab-ci.yml'
      - '/docker/docker.gitlab-ci.yml'

stages:
  - build
  - deploy

variables:
  IMAGE: ${DVB_DOCKER_REGISTRY}/${CI_PROJECT_ROOT_NAMESPACE}/stip/api:${CI_COMMIT_SHORT_SHA}

build-image:
  extends: .docker-build
  variables:
    IMAGE_PATH: $IMAGE
    DOCKERFILE_PATH: src/main/docker/Dockerfile.jvm
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH
      variables:
        KANIKO_ARGS: '--no-push'
  needs:
    - job: maven-build
      artifacts: true


# WIP
deploy:
  stage: deploy
  image: "${DVB_DOCKER_REGISTRY}/devops/docker/tools/k8s/main"
  tags: ["os:linux", "type:docker", "zone:tz"]
  variables:
    STAGE: dev
  script:
    - git fetch origin $CI_COMMIT_BRANCH
    - cd deploy/$STAGE
    - kustomize edit set image $IMAGE
    - "git commit -a -m \"ci($STAGE): deploy image $IMAGE\""
    - git push -o ci.skip https://deploy:$DEPLOYMENT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH