stages: [build, deploy, mirror]

variables:
  ARGOCD_APP: stip
  ARGOCD_IMAGES: api,gesuch-app,sachbearbeitung-app
  STIP_OVERLAYS_DIR: manifests/stip/overlays

backend:
  stage: build
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend

frontend:
  stage: build
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend

include:
  - component: 'gitlab.dvbern.ch/devops/gitlab/components/workflow@5ee978eeededdc1275eb9f200743ba14dfaf2c30'
  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.1.4'
    inputs:
      name: "deploy:dev"
      deployment-overlay-path: "$STIP_OVERLAYS_DIR/dev"
      deployment-environment: "dev"
      deployment-environment-url: "https://dev-stip.$DVB_OCP_MERCURY_ROUTER"
      deployment-image-names: "$ARGOCD_IMAGES"
      deployment-on: "default"
      deployment-mode: "on_success"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "$ARGOCD_APP"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.1.4'
    inputs:
      name: "deploy:uat"
      deployment-overlay-path: "$STIP_OVERLAYS_DIR/uat"
      deployment-environment: "uat"
      deployment-environment-url: "https://uat-stip.$DVB_OCP_APOLLO_ROUTER"
      deployment-image-names: "$ARGOCD_IMAGES"
      deployment-on: "tag"
      deployment-mode: "manual"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "$ARGOCD_APP"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.1.4'
    inputs:
      name: "deploy:prod"
      deployment-overlay-path: "$STIP_OVERLAYS_DIR/prod"
      deployment-environment: "prod"
      deployment-environment-url: "https://stip.$DVB_OCP_APOLLO_ROUTER"
      deployment-image-names: "$ARGOCD_IMAGES"
      deployment-on: "tag"
      deployment-mode: "manual"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "$ARGOCD_APP"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-review-app@v0.1.4'
    inputs:
      review-app-url: "https://${CI_COMMIT_REF_SLUG}-stip.$DVB_OCP_MERCURY_ROUTER"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/github-mirror@f59b6bfce107fe606d8fd6685044e61a1dcf53a5'
    inputs:
      git-mirror-target: "dvbern/stip"
      mirror-on: "tag"
      mirror-when: "always"
