stages: [build, validate, test, package, deploy, e2e, review-e2e, mirror]

include:
  - component: "gitlab.dvbern.ch/components/setup/workflow@1.5.0"
    inputs:
      mr-version: "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"

  - component: "gitlab.dvbern.ch/components/build/maven@1.13.0"
    inputs:
      name: build-api
      context-dir: backend
      java-image-version: 21-jdk-alpine
      maven-goal: >-
        -Drevision=$VERSION
        -Pcoverage
        -Dci.disableConsole=true
        -Dci.logLevel=WARN  
        install    

  - component: 'gitlab.dvbern.ch/components/build/nx@1.13.0'
    inputs:
      app-name: '*-app'
      test-app-name: '*'
      context-dir: 'frontend'
      component-test-on: 'never'
      allow-test-failure: false
      allow-e2e-test-failure: false
      install-e2e-test-package: false
      e2e-artifacts-dir: 'dist/.playwright/'
      e2e-on: 'default'
      e2e-test-package-version: '13.6.2'
      e2e-test-image: docker-registry.dvbern.ch/microsoft/playwright
      e2e-test-image-version: v1.49.1-jammy
      lint-on: '(branch|mr|default)'
      test-on: '(branch|mr|default)'
      build-additional-args: '--verbose'
      node-image: '$DVB_DOCKER_REGISTRY/dockerhub/library/node'
      node-version: ':22'

  - component: 'gitlab.dvbern.ch/components/package/buildah@2.3.0'
    inputs:
      name: package:api
      context-dir: backend
      image-name: 'api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'
      build-latest: false

  - component: 'gitlab.dvbern.ch/components/package/buildah@2.3.0'
    inputs:
      name: package:sachbearbeitung-app
      context-dir: frontend
      image-name: 'sachbearbeitung-app'
      version: '$VERSION'
      build-latest: false
      build-args: |
        APP=sachbearbeitung-app

  - component: 'gitlab.dvbern.ch/components/package/buildah@2.3.0'
    inputs:
      name: package:gesuch-app
      context-dir: frontend
      image-name: 'gesuch-app'
      version: '$VERSION'
      build-latest: false
      build-args: |
        APP=gesuch-app

  - component: 'gitlab.dvbern.ch/components/package/buildah@2.3.0'
    inputs:
      name: package:sozialdienst-app
      context-dir: frontend
      image-name: 'sozialdienst-app'
      version: '$VERSION'
      build-latest: false
      build-args: |
        APP=sozialdienst-app

  - component: 'gitlab.dvbern.ch/components/package/buildah@2.3.0'
    inputs:
      name: package:demo-app
      context-dir: frontend
      image-name: 'demo-app'
      version: '$VERSION'
      build-latest: false
      build-args: |
        APP=demo-data-app

  - component: 'gitlab.dvbern.ch/components/deploy/argocd-helm@1.14.1'
    inputs:
      name: 'deploy:dev'
      deployment-environment: 'dev'
      deployment-environment-url: 'https://dev-stip.$DVB_OCP_MERCURY_ROUTER'
      deployment-environment-values-path: 'charts/stip/environments/dev/values.yaml'
      deployment-on: 'default'
      deployment-mode: 'on_success'
      argocd-server: '$ARGOCD_SERVER'
      argocd-token: '$ARGOCD_TOKEN'
      argocd-app-name: '$ARGOCD_APP'

  - component: 'gitlab.dvbern.ch/components/deploy/argocd-helm@1.14.1'
    inputs:
      name: 'deploy:uat'
      deployment-environment: 'uat'
      deployment-environment-url: 'https://uat-stip.kibon.ch'
      deployment-environment-values-path: 'charts/stip/environments/uat/values.yaml'
      deployment-on: 'tag'
      deployment-mode: 'manual'
      argocd-server: '$ARGOCD_SERVER'
      argocd-token: '$ARGOCD_TOKEN'
      argocd-app-name: '$ARGOCD_APP'

  - component: 'gitlab.dvbern.ch/components/deploy/argocd-helm@1.14.1'
    inputs:
      name: 'deploy:schulung'
      deployment-environment: 'schulung'
      deployment-environment-url: 'https://schulung-stip.kibon.ch'
      deployment-environment-values-path: 'charts/stip/environments/schulung/values.yaml'
      deployment-on: 'tag'
      deployment-mode: 'manual'
      argocd-server: '$ARGOCD_SERVER'
      argocd-token: '$ARGOCD_TOKEN'
      argocd-app-name: '$ARGOCD_APP'

  - component: 'gitlab.dvbern.ch/components/deploy/argocd-helm@1.14.1'
    inputs:
      name: "deploy:prod"
      deployment-environment: "prod"
      deployment-environment-url: "https://myproject.$DVB_OCP_MERCURY_ROUTER"
      deployment-environment-values-path: "charts/stip/environments/prod/values.yaml"
      deployment-on: "tag"
      deployment-mode: "manual"
      deployment-config-tracking-mode: "release"  # Enable release mode
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "$ARGOCD_APP"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-review-app@v0.8.0'
    inputs:
      review-app-url: 'https://${CI_COMMIT_REF_SLUG}-stip.$DVB_OCP_MERCURY_ROUTER'
      review-app-auto-stop: '7 days'

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/github-mirror@v0.8.0'
    inputs:
      git-mirror-clone-token: '$GITLAB_STIP_PULL_TOKEN'
      git-mirror-target: 'dvbern/stip'
      mirror-on: 'tag'
      mirror-when: 'always'

  - component: 'gitlab.dvbern.ch/components/build/nx@1.13.0'
    inputs:
      name: '.nx'
      e2e-test-package-version: '13.6.2'
      context-dir: 'frontend'
      e2e-test-image: docker-registry.dvbern.ch/microsoft/playwright
      e2e-test-image-version: v1.49.1-jammy
      install-e2e-test-package: false
      e2e-artifacts-dir: 'dist/.playwright/'
      e2e-on: 'default'
      node-image: '$DVB_DOCKER_REGISTRY/dockerhub/library/node'
      node-version: ':22'


### Component Extensions
build-api:
  needs: []

package:api:
  needs:
    - job: build-api
      artifacts: true

package:gesuch-app:
  needs:
    - job: nx-build
      artifacts: true

package:sachbearbeitung-app:
  needs:
    - job: nx-build
      artifacts: true

package:sozialdienst-app:
  needs:
    - job: nx-build
      artifacts: true      

package:demo-app:
  needs:
    - job: nx-build
      artifacts: true

### E2E
.install-argocd:
  tags: ['zone:tz', 'os:linux', 'type:docker']
  image:
    name: docker-registry.dvbern.ch/devops/docker/tools/k8s/main
    entrypoint: ['']
  variables:
    ARGOCD_SERVER: '$ARGOCD_SERVER'
    ARGOCD_AUTH_TOKEN: '$ARGOCD_TOKEN'
  before_script:
    - |
      echo "Using ArgoCD Server at $ARGOCD_SERVER"
      curl -ksSL -o /usr/local/bin/argocd https://$ARGOCD_SERVER/download/argocd-linux-amd64

start-e2e:
  stage: e2e
  resource_group: 'argocd:dev'
  extends: .install-argocd
  script:
    - argocd app sync stip-e2e
    - argocd app set stip-e2e --helm-set image.tag=$VERSION
    - argocd app set stip-e2e --helm-set api.replicaCount=1
    - argocd app set stip-e2e --helm-set frontends.gesuch-app.replicaCount=1
    - argocd app set stip-e2e --helm-set frontends.sachbearbeitung-app.replicaCount=1
    - argocd app set stip-e2e --helm-set stip-database.enabled=true
    - argocd app sync stip-e2e
    - argocd app wait stip-e2e
  environment:
    name: e2e
    url: 'https://e2e-stip.$DVB_OCP_MERCURY_ROUTER'
    action: start
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip e2e\]/
      when: never
    - if: $PIPELINE_TYPE == "default"
      when: on_success
  allow_failure: true

nx-e2e-test:
  stage: e2e
  resource_group: 'e2e'
  variables:
    E2E_BASEURL_GS: 'https://e2e-stip.$DVB_OCP_MERCURY_ROUTER'
    E2E_BASEURL_SB: 'https://e2e-sb-stip.$DVB_OCP_MERCURY_ROUTER'
    E2E_BASEURL_SOZ: 'https://e2e-sozialdienst-stip.$DVB_OCP_MERCURY_ROUTER'
  needs:
    - start-e2e

wait-for-review:
  tags: [ "zone:tz", "os:linux", "type:docker" ]
  image:
    name: '${DVB_DOCKER_REGISTRY}/dockerhub/alpine/curl'
    entrypoint: ['']
  stage: review-e2e
  needs:
    - argocd:review-app:start
  script: |
    curl --insecure \
    --max-time $REVIEW_MAX_TIME \
    --retry $REVIEW_RETRY \
    --retry-delay $REVIEW_RETRY_DELAY \
    --retry-max-time $REVIEW_RETRY_MAX_TIME \
    https://${CI_COMMIT_REF_SLUG}-stip.apps.mercury.ocp.dvbern.ch/q/health
  environment:
    name: review/$CI_COMMIT_REF_SLUG
  rules:
    - if: $CI_MERGE_REQUEST_IID

nx-e2e-test:review:
  extends: nx-e2e-test
  stage: review-e2e
  needs:
    - wait-for-review
  variables:
    E2E_BASEURL_GS: 'https://$CI_COMMIT_REF_SLUG-stip.$DVB_OCP_MERCURY_ROUTER'
    E2E_BASEURL_SB: 'https://$CI_COMMIT_REF_SLUG-sb-stip.$DVB_OCP_MERCURY_ROUTER'
    E2E_BASEURL_SOZ: 'https://$CI_COMMIT_REF_SLUG-sozialdienst-stip.$DVB_OCP_MERCURY_ROUTER'
  rules:
    - if: $PIPELINE_TYPE == "mr"

stop-e2e:
  when: always
  stage: e2e
  needs:
    - nx-e2e-test
  resource_group: 'argocd:dev'
  extends: .install-argocd
  script:
    - argocd app set stip-e2e --helm-set api.replicaCount=0
    - argocd app set stip-e2e --helm-set frontends.gesuch-app.replicaCount=0
    - argocd app set stip-e2e --helm-set frontends.sachbearbeitung-app.replicaCount=0
    - argocd app set stip-e2e --helm-set stip-database.enabled=false
    - argocd app sync stip-e2e --prune
    - argocd app wait stip-e2e
  environment:
    name: e2e
    url: 'https://e2e-stip.$DVB_OCP_MERCURY_ROUTER'
    action: stop
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip e2e\]/
      when: never
    - if: $PIPELINE_TYPE == "default"
      when: always
  allow_failure: true

