stages: [ build, validate, test, analyze, package, deploy, mirror ]

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID || '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        VERSION: $CI_COMMIT_REF_SLUG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        VERSION: $CI_COMMIT_SHA
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: $CI_COMMIT_TAG

include:
  - component: "gitlab.dvbern.ch/components/nx@v0.0.1"
    inputs:
      app-name: "*-app"
      test-app-name: "*-app-e2e"

  - component: 'gitlab.dvbern.ch/components/sonarqube@v0.1.0'
    inputs:
      sonar-scanner: cli
      sonar-project-key: kibon_stip-frontend_AYkrwt88SZqri_oH9Xlq

  - component: 'gitlab.dvbern.ch/components/buildah@v0.2.0'
    inputs:
      name: package:sachbearbeitung-app
      image-name: sachbearbeitung-app
      version: "$VERSION"
      build-args: |
        APP=sachbearbeitung-app

  - component: 'gitlab.dvbern.ch/components/buildah@v0.2.0'
    inputs:
      name: package:gesuch-app
      image-name: gesuch-app
      version: "$VERSION"
      build-args: |
        APP=gesuch-app

  - component: 'gitlab.dvbern.ch/components/flux@v0.2.0'
    inputs:
      environment: dev
      image-names: "sachbearbeitung-app,gesuch-app"
      version: "latest"
      review-apps-enabled: "false"
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_ID

  - component: 'gitlab.dvbern.ch/components/flux@v0.2.0'
    inputs:
      environment: uat
      image-names: "sachbearbeitung-app,gesuch-app"
      version: "$VERSION"
    rules:
      - if: $CI_COMMIT_TAG

  - component: 'gitlab.dvbern.ch/components/flux@v0.2.0'
    inputs:
      environment: prod
      image-names: "sachbearbeitung-app,gesuch-app"
      version: "$VERSION"
    rules:
      - if: $CI_COMMIT_TAG

mirror:
  stage: mirror
  image:
    name: '${DVB_DOCKER_REGISTRY}/dockerhub/alpine/git:2.40.1'
    entrypoint: ['']
  tags: ['os:linux', 'type:docker', 'zone:tz']
  variables:
    GIT_STRATEGY: none
  before_script:
    - rm -rf ./*
    - git clone --branch $CI_DEFAULT_BRANCH --single-branch https://deploy:$DEPLOYMENT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git .
    - git checkout $CI_DEFAULT_BRANCH
  script:
    - git push -u https://token:${GITHUB_MIRROR_TOKEN}@github.com/dvbern/stip-frontend.git $CI_DEFAULT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
