include:
  - local: '.gitlab/common.gitlab-ci.yml'

image: docker-registry.dvbern.ch/devops/docker/buildenvs/node/18

stages:
  - validate
  - build
  - deploy

install:
  stage: .pre
  extends: .base
  before_script: []
  script:
    - '[ ! -d node_modules ] && npm ci --legacy-peer-deps --cache=".npm" --ignore-scripts ||
      echo "Skipping npm ci because a cached version is available"'

lint:
  stage: validate
  extends: .base
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3

format-check:
  stage: validate
  extends: .base
  script:
    - npx nx format:check --base=$NX_BASE --head=$NX_HEAD

build:pipeline:
  stage: build
  extends: .base
  script:
    - node ./tools/pipeline/generate.js "$(npx nx print-affected --type=app --base=$NX_BASE --head=$NX_HEAD)"
    - cat affected-apps.gitlab-ci.template.yml
  artifacts:
    expire_in: 30 days
    paths:
      - affected-apps.gitlab-ci.yml

trigger:affected-apps:
  stage: build
  trigger:
    include:
      - artifact: affected-apps.gitlab-ci.template.yml
        job: build:pipeline
  needs:
    - job: 'build:pipeline'
