include:
  - project: 'devops/gitlab/templates'
    file:
      - '/docker/docker.gitlab-ci.yml'

image: docker-registry.dvbern.ch/devops/docker/buildenvs/node/18

stages:
  - validate
  - build
  - deploy

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  GIT_DEPTH: 0

.node-cache: &node-cache
  key:
    files:
      - package.json
      - package-lock.json
  paths:
    - node_modules/
  policy: pull-push

.npm-cache: &npm-cache
  key:
    files:
      - package-lock.json
  paths:
    - .npm
  policy: pull-push

.base:
  tags: ['os:linux', 'zone:tz', 'type:docker']
  cache:
    - <<: *node-cache
    - <<: *npm-cache
  before_script:
    - '[ ! -d node_modules ] && npm ci --legacy-peer-deps --cache=".npm" --ignore-scripts ||
      echo "Skipping npm ci because a cached version is available"'
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

install:
  stage: .pre
  extends: .base
  before_script: []
  script:
    - '[ ! -d node_modules ] && npm ci --legacy-peer-deps --cache=".npm" --ignore-scripts ||
      echo "Skipping npm ci because a cached version is available"'

lint:
  stage: validate
  extends: .base
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3

format-check:
  stage: validate
  extends: .base
  script:
    - npx nx format:check --base=$NX_BASE --head=$NX_HEAD

build:affected:
  stage: build
  extends: .base
  script:
    - node ./tools/pipeline/generate.js "$(npx nx print-affected --type=app --base=$NX_BASE --head=$NX_HEAD)"
    - cat affected-apps.gitlab-ci.yml
  artifacts:
    expire_in: 30 days
    paths:
      - affected-apps.gitlab-ci.yml

trigger:apps:
  stage: build
  trigger:
    include:
      - artifact: affected-apps.gitlab-ci.yml
        job: build:affected
  needs:
    - job: 'build:affected'

build:gesuch-app:
  stage: build
  extends: .base
  script:
    - npm run build:gesuch-app
  artifacts:
    paths:
      - 'dist/apps/gesuch-app'
    when: on_success
    expire_in: '1 day'

build:gesuch-app:image:
  extends: .docker-build
  variables:
    IMAGE_PATH: $IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH
      variables:
        KANIKO_ARGS: '--no-push'
  needs:
    - job: build:gesuch-app
      artifacts: true

deploy:
  stage: deploy
  image: '${DVB_DOCKER_REGISTRY}/devops/docker/tools/k8s/main'
  tags: ['os:linux', 'type:docker', 'zone:tz']
  variables:
    STAGE: dev
  script:
    - git fetch origin $CI_COMMIT_BRANCH
    - cd deploy/$STAGE
    - kustomize edit set image $IMAGE
    - 'git commit --no-verify -a -m "ci($STAGE): deploy image $IMAGE [ci skip]"'
    - git push -o ci.skip https://deploy:$DEPLOYMENT_TOKEN@github.com/dvbern/stip-frontend.git HEAD:$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
