stages: [build, validate, test, analyze, package, deploy, mirror]

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        VERSION: $CI_COMMIT_SHA
    - if: $CI_MERGE_REQUEST_ID || '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        VERSION: $CI_COMMIT_REF_SLUG
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: $CI_COMMIT_TAG

include:
  - component: 'gitlab.dvbern.ch/devops/gitlab/components/workflow@b7dc4b95'


  - component: 'gitlab.dvbern.ch/components/maven@v0.0.2'
    inputs:
      name: build-api
      maven-args: -Pcoverage

  - component: 'gitlab.dvbern.ch/components/sonarqube@v0.2.0'
    inputs:
      sonar-scanner: maven
      sonar-project-key: kibon_stip-api_AYkrwku6SZqri_oH9Xle

  - component: 'gitlab.dvbern.ch/components/buildah@v0.2.1'
    inputs:
      registry: $DVB_PUBLIC_DOCKER_REGISTRY
      registry-user: $DVB_PUBLIC_DOCKER_REGISTRY_USER
      registry-token: $DVB_PUBLIC_DOCKER_REGISTRY_TOKEN
      name: api-image
      image-name: 'stip/api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@b7dc4b95'
    inputs:
      name: "deploy:dev"
      deployment-overlay-path: "manifests/stip/overlays/dev"
      deployment-environment: "dev"
      deployment-environment-url: "https://dev-stip-auth.apps.apollo.ocp.dvbern.ch/"
      deployment-image-names: "api"
      deployment-on: "default"

.default-clone: &default-clone
  before_script:
    - rm -rf ./*
    - git clone --branch $CI_DEFAULT_BRANCH --single-branch https://deploy:$DEPLOYMENT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git .
    - git checkout $CI_DEFAULT_BRANCH

mirror:
  stage: mirror
  image:
    name: '${DVB_DOCKER_REGISTRY}/dockerhub/alpine/git:2.40.1'
    entrypoint: ['']
  tags: ['os:linux', 'type:docker', 'zone:tz']
  variables:
    GIT_STRATEGY: none
  <<: *default-clone
  script:
    - git push -u https://token:${GITHUB_MIRROR_TOKEN}@github.com/dvbern/stip-api.git $CI_DEFAULT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
