include:
  - project: 'devops/gitlab/templates'
    file:
      - '/maven/maven-3-jdk-17.gitlab-ci.yml'
      - '/docker/docker.gitlab-ci.yml'

stages:
  - build

build-image:
  extends: .docker-build
  variables:
    IMAGE_PATH: "${IMAGE_REGISTRY}/${CI_PROJECT_ROOT_NAMESPACE}/stip/api/${IMAGE_NAME_SUFFIX}:${IMAGE_TAG}"
    DOCKERFILE_PATH: src/main/docker/Dockerfile.jvm
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'develop'
      variables:
        IMAGE_NAME_SUFFIX: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH
      variables:
        KANIKO_ARGS: '--no-push'
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_NAME_SUFFIX: ''
        IMAGE_TAG: $CI_COMMIT_TAG
  needs:
    - job: maven-build
      artifacts: true
