include:
  - local: '.gitlab/common.gitlab-ci.yml'

stages:
  - validate
  - test
  - analyze
  - build
  - deploy
  - mirror

install:
  stage: .pre
  extends: .base
  before_script: []
  script:
    - '[ ! -d node_modules ] && npm ci --legacy-peer-deps --cache=".npm" --ignore-scripts ||
      echo "Skipping npm ci because a cached version is available"'

lint:
  stage: validate
  extends: .base
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3

# Temporarily disabled
# format-check:
#   stage: validate
#   extends: .base
#   script:
#     - npx nx format:check --base=$NX_BASE --head=$NX_HEAD

test:
  extends: .base
  stage: test
  script:
    - npm run test:ci
  allow_failure: true
  artifacts:
    when: always
    paths:
      - coverage
    reports:
      junit:
        - junit.xml
    expire_in: 1 day

sonarqube-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  stage: analyze
  tags: ['os:linux', 'type:docker', 'zone:tz']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: '0'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH
  needs:
    - job: test
      artifacts: true

build:pipeline:
  stage: build
  extends: .base
  variables:
    FORCE: 'false'
  script:
    - echo "Force Mode [${FORCE:-false}]"
    - node ./tools/pipeline/generate.js "$([ "$FORCE" = true ] && npx nx print-affected --type=app --base=dad9f00e4eb515c5bffcde425fc2c78c42e77857 || npx nx print-affected --type=app --base=$NX_BASE --head=$NX_HEAD)"
    - cat affected-apps.gitlab-ci.yml
  rules:
    - if: $CI_COMMIT_BRANCH || $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
      variables:
        FORCE: 'true'
  artifacts:
    expire_in: 30 days
    paths:
      - affected-apps.gitlab-ci.yml

trigger:affected-apps:
  stage: build
  trigger:
    strategy: depend
    include:
      - artifact: affected-apps.gitlab-ci.yml
        job: build:pipeline
  needs:
    - job: 'build:pipeline'

mirror:
  stage: mirror
  image:
    name: '${DVB_DOCKER_REGISTRY}/dockerhub/alpine/git:2.40.1'
    entrypoint: ['']
  tags: ['os:linux', 'type:docker', 'zone:tz']
  variables:
    GIT_STRATEGY: none
  before_script:
    - rm -rf ./*
    - git clone --branch $CI_DEFAULT_BRANCH --single-branch https://deploy:$DEPLOYMENT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git .
    - git checkout $CI_DEFAULT_BRANCH
  script:
    - git push -u https://token:${GITHUB_MIRROR_TOKEN}@github.com/dvbern/stip-frontend.git $CI_DEFAULT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
