version: '3'

services:
  stip-database:
    image: docker-registry.dvbern.ch/dockerhub/library/postgres:15.3
    env_file:
      - '.env'
    volumes:
      - 'stip-database-data:/var/lib/postgresql/data'
    networks:
      - stip-net
    ports:
      - "${STIP_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${STIP_DB_USERNAME}
      POSTGRES_DB: ${STIP_DB}
      POSTGRES_PASSWORD: ${STIP_DB_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 2G
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "${STIP_LOCALSTACK_PORT}:4566"
    volumes:
      - "./s3/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

networks:
  stip-net:

volumes:
  stip-database-data:
    external: true

