stages: [build, analyze, package]
variables:
  GIT_DEPTH: 0

include:
  - component: 'gitlab.dvbern.ch/components/build/maven@1.5.0'
    inputs:
      name: build-api
      context-dir: backend
      java-image-version: 17-jdk-alpine
      maven-goal: -Drevision=$VERSION -Pcoverage install

  - component: 'gitlab.dvbern.ch/components/verify/sonarqube@1.2.0'
    inputs:
      enforce-quality-gate: "false"
      sonar-scanner: maven
      context-dir: backend
      sonar-project-key: "$SONAR_PROJECT_KEY_BACKEND"
      sonar-token: "$SONAR_TOKEN_BACKEND"
      needs:
        - "build-api"

  - component: 'gitlab.dvbern.ch/components/package/buildah@1.3.0'
    inputs:
      name: api-image
      context-dir: backend
      image-name: 'api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'
      build-latest: false
