stages: [build, analyze, package]
variables:
  GIT_DEPTH: 0

include:
  - component: 'gitlab.dvbern.ch/fuju/build/maven@ffa6c4686776f53730c3c439719c5b2a7c8ce391'
    inputs:
      name: build-api
      context-dir: backend
      java-image-version: 17-jdk-alpine
      maven-goal: install
      maven-cli-opts-extend: >-
        -DskipTests
        -Drevision=$VERSION
        -Pcoverage
        -Dci.disableConsole=true
        -Dci.logLevel=WARN

  - component: 'gitlab.dvbern.ch/components/verify/sonarqube@1.2.0'
    inputs:
      sonar-scanner: maven
      context-dir: backend
      sonar-project-key: "$SONAR_PROJECT_KEY_BACKEND"
      sonar-token: "$SONAR_TOKEN_BACKEND"
      enforce-quality-gate: 'false'
      needs:
        - "build-api"

  - component: 'gitlab.dvbern.ch/components/package/buildah@1.3.0'
    inputs:
      name: api-image
      context-dir: backend
      image-name: 'api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'
      build-latest: false
