stages: [build, analyze, package]

include:
  - component: 'gitlab.dvbern.ch/components/build/maven@1.5.0'
    inputs:
      name: build-api
      context-dir: backend
      java-image-version: 17-jdk-alpine
      maven-goal: -Drevision=$VERSION -Pcoverage install

  - component: 'gitlab.dvbern.ch/components/verify/sonarqube@1.1.0'
    inputs:
      sonar-scanner: maven
      context-dir: backend
      sonar-project-key: "$SONAR_PROJECT_KEY_BACKEND"
      sonar-token: "$SONAR_TOKEN_BACKEND"

  - component: 'gitlab.dvbern.ch/components/package/buildah@1.3.0'
    inputs:
      name: api-image
      context-dir: backend
      image-name: 'api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'
      build-latest: 'false'
