stages: [ build, validate, test, analyze, package, deploy, mirror ]

include:
  - component: 'gitlab.dvbern.ch/devops/gitlab/components/workflow@3327a9a092d74bb4745d5da7c10ff8a4e8eefe1d'

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/maven@v0.7.2'
    inputs:
      name: build-api
      context-dir: backend
      java-image-version: 17-jdk-alpine
      maven-goal: -Pcoverage install

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/sonarqube@v0.7.2'
    inputs:
      sonar-scanner: maven
      context-dir: backend
      sonar-project-key: "$SONAR_PROJECT_KEY_BACKEND"
      sonar-token: "$SONAR_TOKEN_BACKEND"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/buildah@v0.7.2'
    inputs:
      name: api-image
      context-dir: backend
      image-name: 'api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'
      build-latest: 'false'
