stages: [build, validate, test, analyze, package, deploy, mirror]


include:
  - component: 'gitlab.dvbern.ch/devops/gitlab/components/workflow@v0.0.3'

  - component: 'gitlab.dvbern.ch/components/maven@v0.0.2'
    inputs:
      name: build-api
      maven-args: -Pcoverage

  - component: 'gitlab.dvbern.ch/components/sonarqube@v0.2.0'
    inputs:
      sonar-scanner: maven
      sonar-project-key: kibon_stip-api

  - component: 'gitlab.dvbern.ch/components/buildah@v0.2.1'
    inputs:
      name: api-image
      image-name: 'stip/api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.0.5'
    inputs:
      name: "deploy:dev"
      deployment-overlay-path: "manifests/stip/overlays/dev"
      deployment-environment: "dev"
      deployment-environment-url: "https://dev-stip.apps.apollo.ocp.dvbern.ch"
      deployment-image-names: "api"
      deployment-on: "default"
      deployment-mode: "always"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "stip"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.0.5'
    inputs:
      name: "deploy:uat"
      deployment-overlay-path: "manifests/stip/overlays/uat"
      deployment-environment: "uat"
      deployment-environment-url: "https://uat-stip.apps.apollo.ocp.dvbern.ch"
      deployment-image-names: "api"
      deployment-on: "tag"
      deployment-mode: "manual"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "stip"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.0.5'
    inputs:
      name: "deploy:prod"
      deployment-overlay-path: "manifests/stip/overlays/prod"
      deployment-environment: "prod"
      deployment-environment-url: "https://stip.apps.apollo.ocp.dvbern.ch"
      deployment-image-names: "api"
      deployment-on: "tag"
      deployment-mode: "manual"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "stip"

.default-clone: &default-clone
  before_script:
    - rm -rf ./*
    - git clone --branch $CI_DEFAULT_BRANCH --single-branch https://deploy:$DEPLOYMENT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git .
    - git checkout $CI_DEFAULT_BRANCH

mirror:
  stage: mirror
  image:
    name: '${DVB_DOCKER_REGISTRY}/dockerhub/alpine/git:2.40.1'
    entrypoint: ['']
  tags: ['os:linux', 'type:docker', 'zone:tz']
  variables:
    GIT_STRATEGY: none
  <<: *default-clone
  script:
    - git push -u https://token:${GITHUB_MIRROR_TOKEN}@github.com/dvbern/stip-api.git $CI_DEFAULT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
