stages: [build, validate, test, analyze, package, deploy, mirror]


include:
  - component: 'gitlab.dvbern.ch/devops/gitlab/components/workflow@v0.0.7'

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/maven@v0.0.7'
    inputs:
      name: build-api
      context-dir: backend
      java-image-version: 17-jdk-alpine
      maven-goal: -Pcoverage install

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/sonarqube@2de39183'
    inputs:
      sonar-scanner: maven
      context-dir: backend
      sonar-project-key: kibon_stip-api

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/buildah@91f6083e'
    inputs:
      name: api-image
      context-dir: backend
      image-name: 'stip/api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.0.5'
    inputs:
      name: "deploy:dev"
      deployment-overlay-path: "manifests/stip/overlays/dev"
      deployment-environment: "dev"
      deployment-environment-url: "https://dev-stip.apps.apollo.ocp.dvbern.ch"
      deployment-image-names: "api"
      deployment-on: "default"
      deployment-mode: "always"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "stip"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.0.5'
    inputs:
      name: "deploy:uat"
      deployment-overlay-path: "manifests/stip/overlays/uat"
      deployment-environment: "uat"
      deployment-environment-url: "https://uat-stip.apps.apollo.ocp.dvbern.ch"
      deployment-image-names: "api"
      deployment-on: "tag"
      deployment-mode: "manual"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "stip"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/argocd-deploy@v0.0.5'
    inputs:
      name: "deploy:prod"
      deployment-overlay-path: "manifests/stip/overlays/prod"
      deployment-environment: "prod"
      deployment-environment-url: "https://stip.apps.apollo.ocp.dvbern.ch"
      deployment-image-names: "api"
      deployment-on: "tag"
      deployment-mode: "manual"
      argocd-server: "$ARGOCD_SERVER"
      argocd-token: "$ARGOCD_TOKEN"
      argocd-app-name: "stip"
