stages: [build, validate, test, analyze, package, deploy, mirror]


include:
  - component: 'gitlab.dvbern.ch/devops/gitlab/components/workflow@v0.1.1'

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/maven@v0.1.1'
    inputs:
      name: build-api
      context-dir: backend
      java-image-version: 17-jdk-alpine
      maven-goal: -Pcoverage install

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/sonarqube@v0.1.1'
    inputs:
      sonar-scanner: maven
      context-dir: backend
      sonar-project-key: "$SONAR_PROJECT_KEY_BACKEND"
      sonar-token: "$SONAR_TOKEN_BACKEND"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/buildah@6120775a65b6bb2eb2634da545a84a2cd62a3518'
    inputs:
      name: api-image
      context-dir: backend
      image-name: 'api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'
      build-latest: 'false'
