stages: [build, analyze, package]

include:
  - component: 'gitlab.dvbern.ch/devops/gitlab/components/maven@v0.8.0'
    inputs:
      name: build-api
      context-dir: backend
      java-image-version: 17-jdk-alpine
      maven-goal: -Drevision=$VERSION -Pcoverage install

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/sonarqube@v0.7.2'
    inputs:
      sonar-scanner: maven
      context-dir: backend
      sonar-project-key: "$SONAR_PROJECT_KEY_BACKEND"
      sonar-token: "$SONAR_TOKEN_BACKEND"

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/buildah@v0.8.0'
    inputs:
      build-on: '^(?!mr).*$'
      name: api-image
      context-dir: backend
      image-name: 'api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION'
      build-latest: 'false'

  - component: 'gitlab.dvbern.ch/devops/gitlab/components/buildah@v0.8.0'
    inputs:
      build-on: 'mr'
      name: api-image
      context-dir: backend
      image-name: 'api'
      dockerfile-path: ./src/main/docker/Dockerfile.jvm
      version: '$VERSION-$CI_COMMIT_SHORT_SHA'
      build-latest: 'false'