apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress-config.yml
- api-secrets.yml

images:
- name: docker-registry.public.dvbern.ch/kibon/stip/api
  newTag: v0.3.1

patchesStrategicMerge:
- cluster.yml

configMapGenerator:
- behavior: merge
  envs:
  - api.env
  name: app-config
- behavior: merge
  envs:
  - identity.env
  name: identity-config

replacements:
- source:
    fieldPath: data.host
    kind: ConfigMap
    name: ingress-config
  targets:
  - fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
    select:
      kind: Ingress
      name: api
- source:
    fieldPath: data.identityHost
    kind: ConfigMap
    name: ingress-config
  targets:
  - fieldPaths:
    - spec.rules.1.host
    - spec.tls.0.hosts.1
    select:
      kind: Ingress
      name: api
