/*
 * Copyright (C) 2023 DV Bern AG, Switzerland
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package ch.dvbern.stip.api.stammdaten.type;

import lombok.Getter;

@Getter
public enum Land {
    CH("Schweiz", "Suisse"),
    AF("Afghanistan", "Afghanistan"),
    EG("Ägypten", "Égypte"),
    AL("Albanien", "Albanie"),
    DZ("Algerien", "Algérie"),
    AD("Andorra", "Andorre"),
    AO("Angola", "Angola"),
    AG("Antigua und Barbuda", "Antigua-et-Barbuda"),
    GQ("Äquatorialguinea", "Guinée équatoriale"),
    AR("Argentinien", "Argentine"),
    AM("Armenien", "Arménie"),
    AZ("Aserbaidschan", "Azerbaïdjan"),
    ET("Äthiopien", "Éthiopie"),
    AU("Australien", "Australie"),
    BS("Bahamas", "Bahamas"),
    BH("Bahrain", "Bahreïn"),
    BD("Bangladesh", "Bangladesh"),
    BB("Barbados", "Barbade"),
    BY("Belarus", "Bélarus"),
    BE("Belgien", "Belgique"),
    BZ("Belize", "Belize"),
    BJ("Benin", "Bénin"),
    BT("Bhutan", "Bouthan"),
    BO("Bolivien, Plurinationaler Staat", "Bolivie (État plurinational)"),
    BA("Botswana", "Botswana"),
    BR("Brasilien", "Brésil"),
    BN("Brunei Darussalam", "Brunéi Darussalam "),
    BG("Bulgarien", "Bulgarie"),
    BF("Burkina Faso", "Burkina Faso"),
    BI("Burundi", "Burundi"),
    CV("Cabo Verde", "Cabo Verde"),
    CL("Chile", "Chili"),
    CN("China", "Chine"),
    CK("Cookinseln", "Cook (les Îles)"),
    CR("Costa Rica", "Costa Rica"),
    CI("Côte d'Ivoire", "Côte d'Ivoire"),
    DK("Dänemark", "Danemark"),
    DE("Deutschland", "Allemagne"),
    DM("Dominica", "Dominique"),
    DO("Dominikanische Republik", "dominicaine (la République)"),
    DJ("Dschibuti", "Djibouti"),
    EC("Ecuador", "Équateur"),
    SV("El Salvador", "El Salvador"),
    ER("Eritrea", "Érythrée"),
    EE("Estland", "Estonie"),
    SZ("Eswatini", "Eswatini"),
    FJ("Fidschi", "Fidji"),
    FI("Finnland", "Finlande"),
    FR("Frankreich", "France"),
    GA("Gabun", "Gabon"),
    GM("Gambia", "Gambie"),
    GE("Georgien", "Géorgie"),
    GH("Ghana", "Ghana"),
    GD("Grenada", "Grenade"),
    GR("Griechenland", "Grèce"),
    GT("Guatemala", "Guatemala"),
    GN("Guinea", "Guinée"),
    GW("Guinea-Bissau", "Guinée-Bissau"),
    GF("Guyana", "Guyane"),
    HT("Haiti", "Haiti"),
    VA("Heiliger Stuhl", "Saint-Siège"),
    HN("Honduras", "Honduras"),
    IN("Indien", "Inde"),
    ID("Indonesien", "Indonésie"),
    IQ("Irak", "Iraq"),
    IR("Iran, Islamische Republik", "Iran, République Islamique"),
    IE("Irland", "Irlande"),
    IS("Island", "Islande"),
    IL("Israel", "Israel"),
    IT("Italien", "Italie"),
    JM("Jamaika", "Jamaïque"),
    JP("Japan", "Japon"),
    YE("Jemen", "Yémen"),
    JO("Jordanien", "Jordanie"),
    KH("Kambodscha", "Cambodge"),
    CM("Kamerun", "Cameroun"),
    CA("Kanada", "Canada"),
    KZ("Kasachstan", "Kazakhstan"),
    QA("Katar", "Qatar"),
    KE("Kenia", "Kenya"),
    KG("Kirgisistan", "Kirghizistan"),
    KI("Kiribati", "Kiribati"),
    CO("Kolumbien", "Colombie"),
    KM("Komoren", "Comores"),
    CG("Kongo", "Congo"),
    CD("Kongo, Demokratische Republik", "Congo, République démocratique"),
    KR("Korea, Demokratische Volksrepublik", "Corée, République démocratique"),
    KP("Korea, Republik", "Corée, République"),
    XK("Kosovo", "Kosovo"),
    HR("Kroatien", "Croatie"),
    CU("Kuba", "Cuba"),
    KW("Kuwait", "Koweït"),
    LA("Laos, Demokratische Volksrepublik", "Laos, République démocratique populaire"),
    LS("Lesotho", "Lesotho"),
    LV("Lettland", "Lettonie"),
    LB("Libanon", "Liban"),
    LR("Liberia", "Libéria"),
    LY("Libyen", "Libye"),
    LI("Liechtenstein", "Liechtenstein"),
    LT("Litauen", "Lituanie"),
    LU("Luxemburg", "Luxembourg"),
    MG("Madagaskar", "Madagascar"),
    MW("Malawi", "Malawi"),
    MY("Malaysia", "Malaisie"),
    MV("Malediven", ""),
    ML("Mali", "Mali"),
    MT("Malta", "Malte"),
    MA("Marokko", "Maroc"),
    MH("Marshallinseln", "les Îles Marshall"),
    MR("Mauretanien", "Mauritanie"),
    MU("Mauritius", "Maurice"),
    MX("Mexiko", "Mexique"),
    FM("Mikronesien, Föderierte Staaten von", "Micronésie, (États fédérés de)"),
    MO("Moldau, Republik", "Moldavie"),
    MC("Monaco", "Monaco"),
    MN("Mongolei", "Mongolie"),
    ME("Montenegro", "Montenegro"),
    MZ("Mosambik", "Mozambique"),
    MM("Myanmar", "Myanmar"),
    NA("Namibia", "Namibie"),
    NR("Nauru", "Nauru"),
    NP("Nepal", "Népal"),
    NZ("Neuseeland", "Nouvelle-Zélande"),
    NI("Nicaragua", "Nicaragua"),
    NL("Niederlande", "Pays-Bas"),
    NE("Niger", "Niger"),
    NG("Nigeria", "Nigeria"),
    NU("Niue", "Niue"),
    MK("Nordmazedonien", "Macédoine du Nord"),
    NO("Norwegen", "Norvège"),
    OM("Oman", "Oman"),
    AT("Österreich", "Autriche"),
    PK("Pakistan", "Pakistan"),
    PW("Palau", "Palaos"),
    PA("Panama", "Panama"),
    PG("Papua-Neuguinea", "Papouasie-Nouvelle-Guinée"),
    PY("Paraguay", "Paraguay"),
    PE("Peru", "Pérou"),
    PH("Philippinen", "Philippines"),
    PL("Polen", "Pologne"),
    PT("Portugal", "Portugal"),
    RW("Ruanda", "Rwanda"),
    RO("Rumänien", "Roumanie"),
    RU("Russische Föderation", "Russie"),
    SB("Salomonen", "Salomon"),
    ZM("Sambia", "Zambie"),
    WS("Samoa", "Samoa"),
    SM("San Marino", "Saint-Marin"),
    ST("São Tomé und Príncipe", "Sao Tomé-et-Principe"),
    SA("Saudi-Arabien", "Arabie saoudite"),
    SE("Schweden", "Suède"),
    SN("Senegal", "Sénégal"),
    RS("Serbien", "Serbie"),
    SC("Seychellen", "Seychelles"),
    SL("Sierra Leone", "Sierra Leone"),
    ZW("Simbabwe", "Zimbabwe"),
    SG("Singapur", "Singapour"),
    SK("Slowakei", "Slovaquie"),
    SI("Slowenien", "Slovénie"),
    SO("Somalia", "Somalie"),
    ES("Spanien", "Espagne"),
    LK("Sri Lanka", "Sri Lanka"),
    KN("St.Kitts und Nevis", "Saint-Kitts-et-Nevis"),
    LC("St.Lucia", "Sainte-Lucie"),
    VC("St.Vincent und die Grenadinen", "Saint-Vincent-et-les-Grenadines"),
    ZA("Südafrika", "Afrique du Sud"),
    SD("Sudan", "Soudan"),
    SS("Südsudan", "Soudan du Sud"),
    SR("Suriname", "Suriname"),
    SY("Syrien, Arabische Republik", "République arabe syrienne"),
    TJ("Tadschikistan", "Tadjikistan"),
    TZ("Tansania, Vereinigte Republik", "Tanzanie"),
    TH("Thailand", "Thaïlande"),
    TL("Timor-Leste", "Timor-Leste"),
    TG("Togo", "Togo"),
    TO("Tonga", "Tonga"),
    TT("Trinidad und Tobago", "Trinité-et-Tobago"),
    TD("Tschad", "Tchad"),
    CZ("Tschechien", "Tchéquie"),
    TN("Tunesien", "Tunisie"),
    TR("Türkei", "Turquie"),
    TM("Turkmenistan", "Turkménistan"),
    TV("Tuvalu", "Tuvalu"),
    UG("Uganda", "Uganda"),
    UA("Ukraine", "Ukraine"),
    HU("Ungarn", "Hongrie"),
    UY("Uruguay", "Uruguay"),
    UZ("Usbekistan", "Ouzbékistan"),
    VU("Vanuatu", "Vanuatu"),
    VE("Venezuela, Bolivarische Republik", "Venezuela, République bolivarienne"),
    AE("Vereinigte Arabische Emirate", "Émirats arabes unis"),
    US("Vereinigte Staaten", "États-Unis"),
    GB("Vereinigtes Königreich", "Royaume-Uni"),
    VN("Vietnam", "Vietnam"),
    CF("Zentralafrikanische Republik", "République centrafricaine"),
    CY("Zypern", "Chypre");

    private final String landDE;
    private final String landFR;

    Land(final String landDE, final String landFR) {
        this.landDE = landDE;
        this.landFR = landFR;
    }
}
