apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: stip-dev
spec:
  encryptedData:
    auth: AgAHczE+P5DE58uGMNuk0CkhLzcaE3hENi7J/VTXPPhEefhj1D15zbkhZJRI02GQ10E/QcuzJfP2ICDmD7JwD0I1UCIFQLZVTvOQcstMpG1YleX7ZZm9iS9lEX+qDKRCNoOxTeuR2F7Qb/h66O+kkzo0F5Xs1K8Xn5dfKfeX9u2LwtE5ZXFwTtO8BZlx5taTaNJ5GghfyiK66wxV6/oXBrpe+x1qurfYQmXyrJJqIqJ1H6ZnpGz4cmxsMHV85TSfWR9Ykp4rckAXBoMMmt1in4gxh6cET8e4YAWrS8ug89Jbj4g3vlcqc2PU0lzF7teTWwGOsuTTEpPbfKKuap0Flqyc/7IC8LSUqlFE7v9cK6s2JMfShy5QhCCs9fgLYO1hqK7LnyYpfvvkmszvPlZRAbelg3m/SDTpL/4yW3jeBbV8NOrX9cvuHzv28xSQow6w674efGUBcvkYdYrxqYaQwMaSScmBVLl5fMx7HWOprcX+fk24H8NaeZN5raMwtK3SqyuTBLv2y38V5qAKimKCUydgPgwbIGFN9kzNu9hleYLvbJORtwX0YJZd2Zcs+L+UEhxFpVsbzx57snBNa/l1nw96sRDpOpVupizrA2joSa6JJDLlPos5Iw8PjMpDCXKBEtQBf8EQitoZV2wCucvGj8YCh7SgYanHtcPVQINfGOwD5EeXH179jmqjqJrPcPp65DHsSyoBkMpFxZb4Upgiw3c+LeAG4/5z1ETN9RxDg22cfUVONCIVgWstYLW/Tiwg4Q==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: stip-dev

