apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cluster-super-user
data:
    username: ENC[AES256_GCM,data:Cf3+pceVd4a3UsWO,iv:cFBCaRNhYVSx4ptlctineWQ72b3zhQhPC5Lw4wbm/yk=,tag:WwCCmVOhRFocc2W78Toy4g==,type:str]
    password: ENC[AES256_GCM,data:DjCEUxOxf0WIXXOQNzqbPjEL0V7H8EsSR29gi2aef7M=,iv:h7+DZdce+J0TUgSdBj9xxYqwBFV0Vzvd2zbktG6slwI=,tag:JHTGHXnARe49+41dRXqF+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sj5e38qgvwt4zw6xmggs6pgh2s7y6h7nuvpasasfg5adzlkqc4q97arte
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSDh5TGk3aEN0bXE2Vm1w
            aFJsSjZzeExYV01KUnVpQ1FqTEdEU0lVVDNnCjVsNmRXR293Z2VGWlVxUDhpSGND
            TW5CYy9nZVdScHZGaFhBSW55SXZUcm8KLS0tIHBvSDYxcmZNUDhEN3VmaFhHVUw1
            V0lGUjE2cFVuT0pSak8yU3hTL1hDUFUKY53x+6KhYgvDj62x86GTQOjFZJr2krZO
            VT1fxlPjflGxcLn+l3uUNFLBrj9rra0p980X7VT2Urx/atHFcd3H+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T08:40:39Z"
    mac: ENC[AES256_GCM,data:4rMl6X5UWAX60AKg1tErDMIscua4fVPn/DL0p9OTfQBsZES7ZoBYLK1kxl5wN8RAQ6TltmICTUwu06VbaRw9x8tQP/ntOKXbSw8g2dm3l1bKnb8eRn1dXtAVopiV77PkQf5fjlZ3siYj+9qnklLYMl5tG7Tn8nQ/B7QAXo2Gs+w=,iv:kC4ll0Rdo1z96MjqLdPJvnT8Ud2M5AQrwyCxPJUQjqU=,tag:4NmdATVkiyVNFzVZl6XZtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
