apiVersion: v1
kind: Secret
metadata:
    name: cluster-app-user
data:
    username: ENC[AES256_GCM,data:YNpbpybAACc=,iv:D0mEHIIdSwJXELnykirkpL4F48OGwfpDQYZQg8b350s=,tag:Ehm5pkjKwQkFPHtkcJOkjA==,type:str]
    password: ENC[AES256_GCM,data:tm1y8GljeijZSvjoSF6XWt+iQHPHJCSJZhkcyPG2hrSzx1M32w==,iv:tyiITcFpSVunZkfwFJum/Tskx06lPOyYo/1BG9gFzQk=,tag:cc1UFvFeRTOBwpA+zEiU3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sj5e38qgvwt4zw6xmggs6pgh2s7y6h7nuvpasasfg5adzlkqc4q97arte
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXcyYWhlWm9oRDk4dGpy
            NWdjZis2Q2hqZEwxSDliQkx1UWRETjdWaDBVCmFNWlJQc3Z1NzFOMlJjYlduT1Ft
            dkpyYW9FMlRUTXpXajBjSUlzSlJlSTQKLS0tIG9qT1NNOCtUYU1HQWFMUkNvZ0ly
            SzR6amlzVHZkeUhSRFJFN1ZFODJ3R0UKwv+ee5QwRqsXVrR6uGhCsVVkvsSpM482
            kQ9AAe3uC2NFwSkJJDvvW9XDvknv80kX9B5jhHY4yY1TRfIFl0eQog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T14:06:44Z"
    mac: ENC[AES256_GCM,data:+XYiF/AF47igvgofe707/hr4FQBHoDCMB+V3+ShBD+DQdBSs59TWFRw212ADFSOb5Q86RAKnwmAobM/OFYZjg5SCKalhZ5/wCueI4s+t8PznKK4KKoI0Bj4TOhZ5D9tl+Kp8zr61i+ngAc65bkpkqgxuEGeJ8e3ROVMGgbtwsBU=,iv:C6dwZWtOQWyWkH0XLhDg6HL2abDcfLwDuyI13qEARgA=,tag:js8LDlZFaxKd7TlMPievuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
