apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cluster-super-user
data:
    username: ENC[AES256_GCM,data:c5G2iEb3BO/V9EE=,iv:0Q1gTLLrhFMYUyXGeGSVVBe1TyGuUoFQObF+j4lbIxo=,tag:3/U7d8vyQhhbmf0bfnaC3Q==,type:str]
    password: ENC[AES256_GCM,data:rVrNdq5wdv9nb2dQDYyPjxHuT2TJeGTGvdo94KrQCGCnTw==,iv:dB8SxLgjM/m3oCwGkr2tU6Jsq4C9QUn6dOCGPvl+rsg=,tag:2U0MaLN5yPoHod+yDUIzQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15sj5e38qgvwt4zw6xmggs6pgh2s7y6h7nuvpasasfg5adzlkqc4q97arte
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWWQ4aVdhY2p6b0wrS1o5
            Qll1cG55YUhPT1dPSDVhdDNrT2o3OVdRdlZ3Cjg4TFJncFgzc29Ud3hUcXlwcEtS
            bDdKWU5kSnhKOER5NGM5cGJjYmlaSk0KLS0tIDVtVmdRd2N1eGVKYWE5ZlJUMVpr
            K1FPS1VxQ2l5SjlTRzJISE5WUk5nZUUK3n1OrARke582R51v+KcErjIfOfIYVRp3
            FtPXQ+GxdVm6AcQWy37L3SdQRNNAhnG67ffwEmWnm0CVZyCGd+kAgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T09:45:39Z"
    mac: ENC[AES256_GCM,data:Yl3iW2PTUmACGXbIS5LDZvU/yt9/JQoK6D6+scsGArHwNAhWHCKjOAjhesFvBiS1keNkyzjLRpO2OhwZIvDG2xNSBkkjety5PPazerbbVKKQg+aaiBBX7ZlwUBFdnDGJ1s+Ovr3uX6un/B03ICEKLvnCkv/yFeBVXYfE7L9sxjI=,iv:BhyqrRA+KboxSWi0dyoJv5/yr3DEE09hpuwrMagwImA=,tag:nvwDI3yRVhDHAHybPTLf5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
