apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cluster-super-user
  namespace: stip-dev
spec:
  encryptedData:
    password: AgAAIYqCWiPuX0Rlew5qFuJlGXTVdOAgAFHb172J0khmZB1of4njETA9DEuo3Rpp8sazE9lLuj1HoXRZ8vsYLakMWlHPj6M54xHltfEOK5PHtXEwX5hagRp33hZeTfYL7dKQWN5ONAQ/UzCtX+OikpRnPxURKOINRMAIXdsnx5vytXbylzcDpjglYrqTl67DIH+HRBwTxCF0XBHK/dHb4BupnAhyvNWv/M1GBKcZOxrjlScSSBTJgnX9LZKCWsGILWtOLjiGb0NFvUWkAqZMDK1HwnYzn6am0p/VSpv2ZwLQ/zgsuaNz+AL4rbWdlGw0TDzXII9nUdVel7GiiLzIseLneBruHT4HrtS5o+u+0v0zMHf8Z6JMCTNCsPOAoFcMJ5ADu9HuoNqEA8IbkDJg06w/9JK9lcJP8rmD9MzOhk2OEoofhWBW17/mGaH8K4RnPPGy60NSocSpUCZTLCEsgKwfm1DonwLuUHIvcGhqfRVEY5HtS3IlAGXwarxevRNj4CiJhzH2mxPKKZVXByg8xly7Pw11V9hNNwFdXA62bmXej9FB1VdtrKwIEBUIJDD7WZf5cIEWSkuMMJSfYkTS1GBaBAIesLC94wsSyVqM/qEpwydEggaTrivnO0sTvC1X0EBpQxZwQRxFIL5dhLKmi8O0NAuZfzG0UisJ3TTXZfMSzL2So1+5l6Qs9mlgL4gC93Ky5NhjIBnwd87g6whd
    username: AgBEUtO1Jn5NjMS1CS8IjyEoh2gOUd5TfsTn2BQ2p5tOM9boMu/GQZO0yMr1izFh6lF6JbfXjjwrE919Tku5AxG5rZrHAVdDavJiRCRhIGilra9Ua6K0rX3ooImolfbc3p3aKIKXOZO5c5qmdV7kxpKL2djyk2k/HVPlU93vmPYh0nEfblF3pMP/DBYrLLt2jPcoaG1Wt+SQ02tXpXmgRF4o/vAbq8ALBjD5qEyFkdLiQZFt0xEU2BC9gWLoHg/NAy0f+xre8wHKsigyzvXeozQ02c/uMSCiDoXBUP2k+t4zKw2htsQ1AkJ+62ozPf31j90i7TF5/R6LyCsWSjuIh9lzc2pGOy/Ljz56yUB4uWrIZcc9Lb33CFq0IK8cq7drdov+upf9GGqrULR9NHU8kJ+MpKwbZtEb+N+ixOBZg8CFxw/KFegpfKBD4LwjTl/zwz2lt238C11gKoHFGlfTs+Gsb4LBrUGlW2ASZ4hmFhiNoOmsUpweBQCjNXzkUDjOIUwZ3XWIEvb3N3g01NKhtqeUO6LLHmGwhh2oqZcrnrzV3PeLgq3XeSr4XZITaCFVsM54K2KGaZkEeZOrnG4wATLNzKnzD/OZDctZoHhTg93LD0BT7+RVJg0REHGQ6LfhyjzR7HyhH9mBttWiHigBH7CuQSDcEivakgC0rykCni949Nim9ChzF9BxlW7T8dDaPFQ49MZyUni8t7nY
  template:
    metadata:
      name: cluster-super-user
      namespace: stip-dev
    type: Opaque

