apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress-config.yml
  - identity-secrets.yml
  - api-secrets.yml

images:
  - name: api
    newName: docker-registry.public.dvbern.ch/kibon/stip/api
    newTag: 96e18321

configMapGenerator:
  - behavior: merge
    envs:
      - api.env
    name: app-config
  - behavior: merge
    envs:
      - identity.env
    name: identity-config

replacements:
  - source:
      fieldPath: data.host
      kind: ConfigMap
      name: ingress-config
    targets:
      - fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
        select:
          kind: Ingress
          name: api
  - source:
      fieldPath: data.host-sb
      kind: ConfigMap
      name: ingress-config
    targets:
      - fieldPaths:
          - spec.rules.1.host
          - spec.tls.0.hosts.1
        select:
          kind: Ingress
          name: api
  - source:
      fieldPath: data.identityHost
      kind: ConfigMap
      name: ingress-config
    targets:
      - fieldPaths:
          - spec.rules.2.host
          - spec.tls.0.hosts.2
        select:
          kind: Ingress
          name: api
