apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
- ../base

images:
- name: docker-registry.dvbern.ch/kibon/stip/gesuch-app
  newTag: b90e3fec

patches:
- path: route-patch.yml
  target:
    kind: Route
