apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
- ../base
- ingress-config.yml

images:
- name: docker-registry.dvbern.ch/kibon/stip/api
  newTag: 83af160b

replacements:
- source:
    fieldPath: data.host
    kind: ConfigMap
    name: ingress-config
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
      name: www

patches:
- path: cluster-app-user.yml
- path: cluster-super-user.yml
- path: route-patch.yml
  target:
    kind: Route
