apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
- ../base
- ingress-config.yml
- cluster-super-user.yml
- cluster-app-user.yml

images:
- name: docker-registry.dvbern.ch/kibon/stip/api
  newTag: 83af160b

replacements:
- source:
    fieldPath: data.host
    kind: ConfigMap
    name: ingress-config
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
      name: www
- source:
    kind: Secret
    name: cluster-super-user
  targets:
    - select:
        kind: Cluster
        name: cluster
      fieldPaths:
        - spec.superuserSecret.name
- source:
    kind: Secret
    name: cluster-app-user
  targets:
    - select:
        kind: Cluster
        name: cluster
      fieldPaths:
        - spec.bootstrap.initdb.secret.name

patches:
- path: route-patch.yml
  target:
    kind: Route
