apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namePrefix: kibon-stip-
nameSuffix: -dev

resources:
- cluster-app-user.yml
- cluster-super-user.yml
- ../base
- ingress-config.yml

images:
- name: docker-registry.dvbern.ch/kibon/stip/api
  newTag: d44325f9
- name: docker-registry.public.dvbern.ch/kibon/stip/api
  newTag: 93b0cfb2

replacements:
- source:
    fieldPath: data.host
    kind: ConfigMap
    name: ingress-config
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
      name: www
