apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namePrefix: kibon-stip-
nameSuffix: -dev

resources:
- ../base
- ingress-config.yml
- cluster-app-user.yml
- cluster-super-user.yml

images:
- name: docker-registry.dvbern.ch/kibon/stip/api
  newTag: 31f790d5
- name: docker-registry.public.dvbern.ch/kibon/stip/api
  newTag: 93b0cfb2

replacements:
- source:
    fieldPath: data.host
    kind: ConfigMap
    name: ingress-config
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
      name: www
- source:
    kind: Secret
    name: cluster-super-user
  targets:
  - fieldPaths:
    - spec.superuserSecret.name
    select:
      kind: Cluster
      name: cluster
- source:
    kind: Secret
    name: cluster-app-user
  targets:
  - fieldPaths:
    - spec.bootstrap.initdb.secret.name
    select:
      kind: Cluster
      name: cluster
