apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
- ../base
- ingress-config.yml

images:
- name: docker-registry.dvbern.ch/kibon/stip/api
  newTag: a50c65fa

replacements:
- source:
    fieldPath: data.host
    kind: ConfigMap
    name: ingress-config
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
      name: www
- source:
    kind: Secret
    name: cluster-super-user
  targets:
  - fieldPaths:
    - spec.superuserSecret.name
    select:
      kind: Cluster
      name: cluster
- source:
    kind: Secret
    name: cluster-app-user
  targets:
  - fieldPaths:
    - spec.bootstrap.initdb.secret.name
    select:
      kind: Cluster
      name: cluster

patches:
- path: cluster-app-user.yml
- path: cluster-super-user.yml
- path: route-patch.yml
  target:
    kind: Route
