apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: api
          imagePullPolicy: Always
          image: docker-registry.dvbern.ch/kibon/stip/api:latest
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /q/health/live
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /q/health/ready
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: STIP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kibon-stip-cluster-dev-app
                  key: username
            - name: STIP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kibon-stip-cluster-dev-app
                  key: password
          envFrom:
            - configMapRef:
                name: app-config
      imagePullSecrets:
        - name: dvbern-registry
