apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      containers:
        - name: api
          imagePullPolicy: Always
          image: api:latest
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /q/health/live
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /q/health/ready
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: STIP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-app
                  key: username
            - name: STIP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-app
                  key: password
            - name: STIP_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: s3_api_key
            - name: STIP_S3_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: s3_api_secret
          envFrom:
            - configMapRef:
                name: app-config
      imagePullSecrets:
        - name: dvbern-public-registry
