apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: identity
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: identity
          imagePullPolicy: Always
          image: docker-registry.public.dvbern.ch/kibon/stip/identity:latest
          command:
            - 'start'
            - '--optimized'
            - '--import-realm'
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /q/health/live
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /q/health/ready
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: identity-cluster-app
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-cluster-app
                  key: password
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: password
          envFrom:
            - configMapRef:
                name: app-config
      imagePullSecrets:
        - name: dvbern-public-registry
