apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  project: stip

commonAnnotations:
  billing.dvbern.ch/customer: dvbern
  billing.dvbern.ch/project: kibon
  billing.dvbern.ch/category: stip

resources:
  - deployment.yml
  - deployment-sb.yml
  - service.yml
  - service-sb.yml
  - ingress.yml
  # TODO: OpenShift
  # - route.yml

# TODO: OpenShift
# crds:
#  - crds/openshift-route.json
