apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  project: stip
  app: api

commonAnnotations:
  billing.dvbern.ch/customer: dvbern
  billing.dvbern.ch/project: kibon
  billing.dvbern.ch/category: stip

resources:
  - deployment.yml
  - service.yml
  - route.yml
  - cluster.yml
  - config-map.yml
  - ingress.yml


crds:
  - crds/openshift-route.json
