apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kibon-stip-

commonLabels:
  project: stip
  app: api

commonAnnotations:
  billing.dvbern.ch/customer: dvbern
  billing.dvbern.ch/project: kibon
  billing.dvbern.ch/category: stip

resources:
  - deployment.yml
  - service.yml
  - route.yml
  - cluster.yml
  - config-map.yml
  - cluster-super-user.yml
  - cluster-app-user.yml
  - ingress.yml

replacements:
  - source:
      kind: Secret
      name: cluster-super-user
    targets:
      - select:
          kind: Cluster
          name: cluster
        fieldPaths:
          - spec.superuserSecret.name
  - source:
      kind: Secret
      name: cluster-app-user
    targets:
      - select:
          kind: Cluster
          name: cluster
        fieldPaths:
          - spec.bootstrap.initdb.secret.name

crds:
  - crds/openshift-route.json
