apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  billing.dvbern.ch/customer: dvbern
  billing.dvbern.ch/project: kibon
  billing.dvbern.ch/category: stip

resources:
  - api-deployment.yml
  - api-service.yml
  # TODO: OpenShift
  # - route.yml
  - api-cluster.yml
  - ingress.yml
  - identity-cluster.yml
  - identity-deployment.yml
  - identity-service.yml

configMapGenerator:
  - name: app-config
    envs:
      - 'api.env'
  - name: identity-config
    envs:
      - 'identity.env'

crds:
  - crds/openshift-route.json
