apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kibon-stip-

commonLabels:
  project: stip
  app: gesuch-app

commonAnnotations:
  billing.dvbern.ch/customer: dvbern
  billing.dvbern.ch/project: kibon
  billing.dvbern.ch/category: stip

resources:
  - deployment.yml
  - service.yml
  - route.yml

crds:
  - crds/openshift-route.json
