ALTER TABLE gesuchsperiode
	ADD COLUMN bezeichnung_de							VARCHAR(255) 	NOT NULL DEFAULT '',
	ADD COLUMN bezeichnung_fr							VARCHAR(255) 	NOT NULL DEFAULT '',
	ADD COLUMN fiskaljahr								VARCHAR(255) 	NOT NULL DEFAULT '',
	ADD COLUMN gesuchsjahr								INTEGER			NOT NULL DEFAULT 1,
	ADD COLUMN gesuchsperiode_start						DATE 			NOT NULL DEFAULT current_date,
	ADD COLUMN gesuchsperiode_stopp						DATE 			NOT NULL DEFAULT current_date,
	ADD COLUMN aufschalttermin_start					DATE 			NOT NULL DEFAULT current_date,
	ADD COLUMN aufschalttermin_stopp					DATE 			NOT NULL DEFAULT current_date,
	ADD COLUMN einreichefrist_normal					DATE 			NOT NULL DEFAULT current_date,
	ADD COLUMN einreichefrist_reduziert					DATE 			NOT NULL DEFAULT current_date,
	ADD COLUMN ausbKosten_sek_ii						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN ausbKosten_tertiaer						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN freibetrag_vermoegen						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN freibetrag_erwerbseinkommen				INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN einkommensfreibetrag						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN elternbeteiligungssatz					INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN vermoegensfreibetrag					INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN vermogen_satz_angerechnet				INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN integrationszulage						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN limite_ek_freibetrag_integrationszulag	INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN stip_limite_minimalstipendium			INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN person_1									INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN personen_2								INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN personen_3								INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN personen_4								INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN personen_5								INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN personen_6								INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN personen_7								INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN pro_weitere_person						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN kinder_00_18								INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN jugendliche_erwachsene_19_25				INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN erwachsene_26_99							INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_fam_1pers						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_fam_2pers						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_fam_3pers						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_fam_4pers						INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_fam_5pluspers					INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_persoenlich_1pers				INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_persoenlich_2pers				INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_persoenlich_3pers				INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_persoenlich_4pers				INTEGER 		NOT NULL DEFAULT 1,
	ADD COLUMN wohnkosten_persoenlich_5pluspers			INTEGER 		NOT NULL DEFAULT 1;

ALTER TABLE gesuchsperiode
	ALTER COLUMN bezeichnung_de							DROP DEFAULT,
	ALTER COLUMN bezeichnung_fr							DROP DEFAULT,
	ALTER COLUMN fiskaljahr								DROP DEFAULT,
	ALTER COLUMN gesuchsjahr							DROP DEFAULT,
	ALTER COLUMN gesuchsperiode_start					DROP DEFAULT,
	ALTER COLUMN gesuchsperiode_stopp					DROP DEFAULT,
	ALTER COLUMN aufschalttermin_start					DROP DEFAULT,
	ALTER COLUMN aufschalttermin_stopp					DROP DEFAULT,
	ALTER COLUMN einreichefrist_normal					DROP DEFAULT,
	ALTER COLUMN einreichefrist_reduziert				DROP DEFAULT,
	ALTER COLUMN ausbKosten_sek_ii						DROP DEFAULT,
	ALTER COLUMN ausbKosten_tertiaer					DROP DEFAULT,
	ALTER COLUMN freibetrag_vermoegen					DROP DEFAULT,
	ALTER COLUMN freibetrag_erwerbseinkommen			DROP DEFAULT,
	ALTER COLUMN einkommensfreibetrag					DROP DEFAULT,
	ALTER COLUMN elternbeteiligungssatz					DROP DEFAULT,
	ALTER COLUMN vermoegensfreibetrag					DROP DEFAULT,
	ALTER COLUMN vermogen_satz_angerechnet			DROP DEFAULT,
	ALTER COLUMN integrationszulage						DROP DEFAULT,
	ALTER COLUMN limite_ek_freibetrag_integrationszulag	DROP DEFAULT,
	ALTER COLUMN stip_limite_minimalstipendium			DROP DEFAULT,
	ALTER COLUMN person_1								DROP DEFAULT,
	ALTER COLUMN personen_2								DROP DEFAULT,
	ALTER COLUMN personen_3								DROP DEFAULT,
	ALTER COLUMN personen_4								DROP DEFAULT,
	ALTER COLUMN personen_5								DROP DEFAULT,
	ALTER COLUMN personen_6								DROP DEFAULT,
	ALTER COLUMN personen_7								DROP DEFAULT,
	ALTER COLUMN pro_weitere_person						DROP DEFAULT,
	ALTER COLUMN kinder_00_18							DROP DEFAULT,
	ALTER COLUMN jugendliche_erwachsene_19_25			DROP DEFAULT,
	ALTER COLUMN erwachsene_26_99						DROP DEFAULT,
	ALTER COLUMN wohnkosten_fam_1pers					DROP DEFAULT,
	ALTER COLUMN wohnkosten_fam_2pers					DROP DEFAULT,
	ALTER COLUMN wohnkosten_fam_3pers					DROP DEFAULT,
	ALTER COLUMN wohnkosten_fam_4pers					DROP DEFAULT,
	ALTER COLUMN wohnkosten_fam_5pluspers				DROP DEFAULT,
	ALTER COLUMN wohnkosten_persoenlich_1pers			DROP DEFAULT,
	ALTER COLUMN wohnkosten_persoenlich_2pers			DROP DEFAULT,
	ALTER COLUMN wohnkosten_persoenlich_3pers			DROP DEFAULT,
	ALTER COLUMN wohnkosten_persoenlich_4pers			DROP DEFAULT,
	ALTER COLUMN wohnkosten_persoenlich_5pluspers		DROP DEFAULT;

ALTER TABLE gesuchsperiode_aud
	ADD COLUMN bezeichnung_de							VARCHAR(255),
	ADD COLUMN bezeichnung_fr							VARCHAR(255),
	ADD COLUMN fiskaljahr								VARCHAR(255),
	ADD COLUMN gesuchsjahr								INTEGER,
	ADD COLUMN gesuchsperiode_start						DATE,
	ADD COLUMN gesuchsperiode_stopp						DATE,
	ADD COLUMN aufschalttermin_start					DATE,
	ADD COLUMN aufschalttermin_stopp					DATE,
	ADD COLUMN einreichefrist_normal					DATE,
	ADD COLUMN einreichefrist_reduziert					DATE,
	ADD COLUMN ausbKosten_sek_ii						INTEGER,
	ADD COLUMN ausbKosten_tertiaer						INTEGER,
	ADD COLUMN freibetrag_vermoegen						INTEGER,
	ADD COLUMN freibetrag_erwerbseinkommen				INTEGER,
	ADD COLUMN einkommensfreibetrag						INTEGER,
	ADD COLUMN elternbeteiligungssatz					INTEGER,
	ADD COLUMN vermoegensfreibetrag					INTEGER,
	ADD COLUMN vermogen_satz_angerechnet				INTEGER,
	ADD COLUMN integrationszulage						INTEGER,
	ADD COLUMN limite_ek_freibetrag_integrationszulag	INTEGER,
	ADD COLUMN stip_limite_minimalstipendium			INTEGER,
	ADD COLUMN person_1									INTEGER,
	ADD COLUMN personen_2								INTEGER,
	ADD COLUMN personen_3								INTEGER,
	ADD COLUMN personen_4								INTEGER,
	ADD COLUMN personen_5								INTEGER,
	ADD COLUMN personen_6								INTEGER,
	ADD COLUMN personen_7								INTEGER,
	ADD COLUMN pro_weitere_person						INTEGER,
	ADD COLUMN kinder_00_18								INTEGER,
	ADD COLUMN jugendliche_erwachsene_19_25				INTEGER,
	ADD COLUMN erwachsene_26_99							INTEGER,
	ADD COLUMN wohnkosten_fam_1pers						INTEGER,
	ADD COLUMN wohnkosten_fam_2pers						INTEGER,
	ADD COLUMN wohnkosten_fam_3pers						INTEGER,
	ADD COLUMN wohnkosten_fam_4pers						INTEGER,
	ADD COLUMN wohnkosten_fam_5pluspers					INTEGER,
	ADD COLUMN wohnkosten_persoenlich_1pers				INTEGER,
	ADD COLUMN wohnkosten_persoenlich_2pers				INTEGER,
	ADD COLUMN wohnkosten_persoenlich_3pers				INTEGER,
	ADD COLUMN wohnkosten_persoenlich_4pers				INTEGER,
	ADD COLUMN wohnkosten_persoenlich_5pluspers			INTEGER;
