-- Delete all Gesuchsperioden created in previous migrations. This shouldn't be here when we correct the migrations
-- and make a new baseline
DELETE
FROM gesuchsperiode;

ALTER TABLE gesuchsperiode
  ADD COLUMN bezeichnung_de                         VARCHAR(255),
  ADD COLUMN bezeichnung_fr                         VARCHAR(255),
  ADD COLUMN fiskaljahr                             VARCHAR(255),
  ADD COLUMN gesuchsjahr_id                         UUID,
  ADD COLUMN gesuchsperiode_start                   DATE,
  ADD COLUMN gesuchsperiode_stopp                   DATE,
  ADD COLUMN aufschalttermin_start                  DATE,
  ADD COLUMN aufschalttermin_stopp                  DATE,
  ADD COLUMN einreichefrist_normal                  DATE,
  ADD COLUMN einreichefrist_reduziert               DATE,
  ADD COLUMN ausbKosten_sek_ii                      INTEGER,
  ADD COLUMN ausbKosten_tertiaer                    INTEGER,
  ADD COLUMN freibetrag_vermoegen                   INTEGER,
  ADD COLUMN freibetrag_erwerbseinkommen            INTEGER,
  ADD COLUMN einkommensfreibetrag                   INTEGER,
  ADD COLUMN elternbeteiligungssatz                 INTEGER,
  ADD COLUMN vermoegensfreibetrag                   INTEGER,
  ADD COLUMN vermogen_satz_angerechnet              INTEGER,
  ADD COLUMN integrationszulage                     INTEGER,
  ADD COLUMN limite_ek_freibetrag_integrationszulag INTEGER,
  ADD COLUMN stip_limite_minimalstipendium          INTEGER,
  ADD COLUMN person_1                               INTEGER,
  ADD COLUMN personen_2                             INTEGER,
  ADD COLUMN personen_3                             INTEGER,
  ADD COLUMN personen_4                             INTEGER,
  ADD COLUMN personen_5                             INTEGER,
  ADD COLUMN personen_6                             INTEGER,
  ADD COLUMN personen_7                             INTEGER,
  ADD COLUMN pro_weitere_person                     INTEGER,
  ADD COLUMN kinder_00_18                           INTEGER,
  ADD COLUMN jugendliche_erwachsene_19_25           INTEGER,
  ADD COLUMN erwachsene_26_99                       INTEGER,
  ADD COLUMN wohnkosten_fam_1pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_2pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_3pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_4pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_5pluspers               INTEGER,
  ADD COLUMN wohnkosten_persoenlich_1pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_2pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_3pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_4pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_5pluspers       INTEGER,
  ADD COLUMN gueltigkeit_status                     VARCHAR(255),
  DROP COLUMN gueltig_ab,
  DROP COLUMN gueltig_bis,
  DROP COLUMN einreichfrist,
  DROP COLUMN aufschaltdatum;

ALTER TABLE gesuchsperiode
  ADD CONSTRAINT FK_gesuchsperiode_gesuchsjahr_id
    FOREIGN KEY (gesuchsjahr_id)
      REFERENCES gesuchsjahr(id);

ALTER TABLE gesuchsperiode_aud
  ADD COLUMN bezeichnung_de                         VARCHAR(255),
  ADD COLUMN bezeichnung_fr                         VARCHAR(255),
  ADD COLUMN fiskaljahr                             VARCHAR(255),
  ADD COLUMN gesuchsjahr_id                         UUID,
  ADD COLUMN gesuchsperiode_start                   DATE,
  ADD COLUMN gesuchsperiode_stopp                   DATE,
  ADD COLUMN aufschalttermin_start                  DATE,
  ADD COLUMN aufschalttermin_stopp                  DATE,
  ADD COLUMN einreichefrist_normal                  DATE,
  ADD COLUMN einreichefrist_reduziert               DATE,
  ADD COLUMN ausbKosten_sek_ii                      INTEGER,
  ADD COLUMN ausbKosten_tertiaer                    INTEGER,
  ADD COLUMN freibetrag_vermoegen                   INTEGER,
  ADD COLUMN freibetrag_erwerbseinkommen            INTEGER,
  ADD COLUMN einkommensfreibetrag                   INTEGER,
  ADD COLUMN elternbeteiligungssatz                 INTEGER,
  ADD COLUMN vermoegensfreibetrag                   INTEGER,
  ADD COLUMN vermogen_satz_angerechnet              INTEGER,
  ADD COLUMN integrationszulage                     INTEGER,
  ADD COLUMN limite_ek_freibetrag_integrationszulag INTEGER,
  ADD COLUMN stip_limite_minimalstipendium          INTEGER,
  ADD COLUMN person_1                               INTEGER,
  ADD COLUMN personen_2                             INTEGER,
  ADD COLUMN personen_3                             INTEGER,
  ADD COLUMN personen_4                             INTEGER,
  ADD COLUMN personen_5                             INTEGER,
  ADD COLUMN personen_6                             INTEGER,
  ADD COLUMN personen_7                             INTEGER,
  ADD COLUMN pro_weitere_person                     INTEGER,
  ADD COLUMN kinder_00_18                           INTEGER,
  ADD COLUMN jugendliche_erwachsene_19_25           INTEGER,
  ADD COLUMN erwachsene_26_99                       INTEGER,
  ADD COLUMN wohnkosten_fam_1pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_2pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_3pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_4pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_5pluspers               INTEGER,
  ADD COLUMN wohnkosten_persoenlich_1pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_2pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_3pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_4pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_5pluspers       INTEGER,
  ADD COLUMN gueltigkeit_status                     VARCHAR(255);

