-- Delete all Gesuchsperioden created in previous migrations. This shouldn't be here when we correct the migrations
-- and make a new baseline

ALTER TABLE gesuchsperiode
  ADD COLUMN bezeichnung_de                         VARCHAR(255),
  ADD COLUMN bezeichnung_fr                         VARCHAR(255),
  ADD COLUMN fiskaljahr                             VARCHAR(255),
  ADD COLUMN gesuchsjahr_id                         UUID,
  ADD COLUMN gesuchsperiode_start                   DATE,
  ADD COLUMN gesuchsperiode_stopp                   DATE,
  ADD COLUMN aufschalttermin_start                  DATE,
  ADD COLUMN aufschalttermin_stopp                  DATE,
  ADD COLUMN einreichefrist_normal                  DATE,
  ADD COLUMN einreichefrist_reduziert               DATE,
  ADD COLUMN ausbKosten_sek_ii                      INTEGER,
  ADD COLUMN ausbKosten_tertiaer                    INTEGER,
  ADD COLUMN freibetrag_vermoegen                   INTEGER,
  ADD COLUMN freibetrag_erwerbseinkommen            INTEGER,
  ADD COLUMN einkommensfreibetrag                   INTEGER,
  ADD COLUMN elternbeteiligungssatz                 INTEGER,
  ADD COLUMN vermoegensfreibetrag                   INTEGER,
  ADD COLUMN vermogen_satz_angerechnet              INTEGER,
  ADD COLUMN integrationszulage                     INTEGER,
  ADD COLUMN limite_ek_freibetrag_integrationszulag INTEGER,
  ADD COLUMN stip_limite_minimalstipendium          INTEGER,
  ADD COLUMN person_1                               INTEGER,
  ADD COLUMN personen_2                             INTEGER,
  ADD COLUMN personen_3                             INTEGER,
  ADD COLUMN personen_4                             INTEGER,
  ADD COLUMN personen_5                             INTEGER,
  ADD COLUMN personen_6                             INTEGER,
  ADD COLUMN personen_7                             INTEGER,
  ADD COLUMN pro_weitere_person                     INTEGER,
  ADD COLUMN kinder_00_18                           INTEGER,
  ADD COLUMN jugendliche_erwachsene_19_25           INTEGER,
  ADD COLUMN erwachsene_26_99                       INTEGER,
  ADD COLUMN wohnkosten_fam_1pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_2pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_3pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_4pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_5pluspers               INTEGER,
  ADD COLUMN wohnkosten_persoenlich_1pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_2pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_3pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_4pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_5pluspers       INTEGER,
  ADD COLUMN gueltigkeit_status                     VARCHAR(255),
  DROP COLUMN gueltig_ab,
  DROP COLUMN gueltig_bis,
  DROP COLUMN einreichfrist,
  DROP COLUMN aufschaltdatum;

ALTER TABLE gesuchsperiode
  ADD CONSTRAINT FK_gesuchsperiode_gesuchsjahr_id
    FOREIGN KEY (gesuchsjahr_id)
      REFERENCES gesuchsjahr(id);

ALTER TABLE gesuchsperiode_aud
  ADD COLUMN bezeichnung_de                         VARCHAR(255),
  ADD COLUMN bezeichnung_fr                         VARCHAR(255),
  ADD COLUMN fiskaljahr                             VARCHAR(255),
  ADD COLUMN gesuchsjahr_id                         UUID,
  ADD COLUMN gesuchsperiode_start                   DATE,
  ADD COLUMN gesuchsperiode_stopp                   DATE,
  ADD COLUMN aufschalttermin_start                  DATE,
  ADD COLUMN aufschalttermin_stopp                  DATE,
  ADD COLUMN einreichefrist_normal                  DATE,
  ADD COLUMN einreichefrist_reduziert               DATE,
  ADD COLUMN ausbKosten_sek_ii                      INTEGER,
  ADD COLUMN ausbKosten_tertiaer                    INTEGER,
  ADD COLUMN freibetrag_vermoegen                   INTEGER,
  ADD COLUMN freibetrag_erwerbseinkommen            INTEGER,
  ADD COLUMN einkommensfreibetrag                   INTEGER,
  ADD COLUMN elternbeteiligungssatz                 INTEGER,
  ADD COLUMN vermoegensfreibetrag                   INTEGER,
  ADD COLUMN vermogen_satz_angerechnet              INTEGER,
  ADD COLUMN integrationszulage                     INTEGER,
  ADD COLUMN limite_ek_freibetrag_integrationszulag INTEGER,
  ADD COLUMN stip_limite_minimalstipendium          INTEGER,
  ADD COLUMN person_1                               INTEGER,
  ADD COLUMN personen_2                             INTEGER,
  ADD COLUMN personen_3                             INTEGER,
  ADD COLUMN personen_4                             INTEGER,
  ADD COLUMN personen_5                             INTEGER,
  ADD COLUMN personen_6                             INTEGER,
  ADD COLUMN personen_7                             INTEGER,
  ADD COLUMN pro_weitere_person                     INTEGER,
  ADD COLUMN kinder_00_18                           INTEGER,
  ADD COLUMN jugendliche_erwachsene_19_25           INTEGER,
  ADD COLUMN erwachsene_26_99                       INTEGER,
  ADD COLUMN wohnkosten_fam_1pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_2pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_3pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_4pers                   INTEGER,
  ADD COLUMN wohnkosten_fam_5pluspers               INTEGER,
  ADD COLUMN wohnkosten_persoenlich_1pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_2pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_3pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_4pers           INTEGER,
  ADD COLUMN wohnkosten_persoenlich_5pluspers       INTEGER,
  ADD COLUMN gueltigkeit_status                     VARCHAR(255);

UPDATE gesuchsperiode
  SET bezeichnung_de = 'Frühling 2023',
      bezeichnung_fr = 'Printemps 2023',
      fiskaljahr = '2022',
      gesuchsjahr_id = '9596bb3e-10ea-4493-8aed-a6ef510f806b',
      gesuchsperiode_start = '2022-08-01',
      gesuchsperiode_stopp = '2023-07-31',
      aufschalttermin_start = '2022-01-01',
      aufschalttermin_stopp = '2022-12-31',
      einreichefrist_normal = '2022-07-31',
      einreichefrist_reduziert = '2022-12-31',
      gueltigkeit_status = 'ARCHIVIERT',
      ausbKosten_sek_ii = 2000,
      ausbKosten_tertiaer = 3000,
      einkommensfreibetrag = 6000,
      vermogen_satz_angerechnet = 15,
      elternbeteiligungssatz = 50,
      freibetrag_erwerbseinkommen = 6000,
      vermoegensfreibetrag = 30000,
      person_1 = 11724,
      personen_2 = 17940,
      personen_3 = 21816,
      personen_4 = 25080,
      personen_5 = 28368,
      personen_6 = 31656,
      personen_7 = 34944,
      pro_weitere_person = 3288,
      integrationszulage = 2400,
      limite_ek_freibetrag_integrationszulag = 13200,
      kinder_00_18 = 1400,
      jugendliche_erwachsene_19_25 = 4600,
      erwachsene_26_99 = 5400,
      stip_limite_minimalstipendium = 500,
      wohnkosten_fam_1pers = 10009,
      wohnkosten_fam_2pers = 13536,
      wohnkosten_fam_3pers = 16260,
      wohnkosten_fam_4pers = 19932,
      wohnkosten_fam_5pluspers = 25260,
      wohnkosten_persoenlich_1pers = 13536,
      wohnkosten_persoenlich_2pers = 16260,
      wohnkosten_persoenlich_3pers = 16260,
      wohnkosten_persoenlich_4pers = 19932,
      wohnkosten_persoenlich_5pluspers = 25260
  WHERE id='3fa85f64-5717-4562-b3fc-2c963f66afa5';
UPDATE gesuchsperiode
  SET bezeichnung_de = 'Herbst 2023/24',
      bezeichnung_fr = 'Automne 2023/24',
      fiskaljahr = '2023',
      gesuchsjahr_id = '9596bb3e-10ea-4493-8aed-a6ef510f806b',
      gesuchsperiode_start = '2023-08-01',
      gesuchsperiode_stopp = '2024-06-30',
      aufschalttermin_start = '2023-01-01',
      aufschalttermin_stopp = '2023-12-31',
      einreichefrist_normal = '2023-07-31',
      einreichefrist_reduziert = '2023-12-31',
      gueltigkeit_status = 'PUBLIZIERT',
      ausbKosten_sek_ii = 2000,
      ausbKosten_tertiaer = 3000,
      einkommensfreibetrag = 6000,
      vermogen_satz_angerechnet = 15,
      elternbeteiligungssatz = 50,
      freibetrag_erwerbseinkommen = 6000,
      vermoegensfreibetrag = 30000,
      person_1 = 11724,
      personen_2 = 17940,
      personen_3 = 21816,
      personen_4 = 25080,
      personen_5 = 28368,
      personen_6 = 31656,
      personen_7 = 34944,
      pro_weitere_person = 3288,
      integrationszulage = 2400,
      limite_ek_freibetrag_integrationszulag = 13200,
      kinder_00_18 = 1400,
      jugendliche_erwachsene_19_25 = 4600,
      erwachsene_26_99 = 5400,
      stip_limite_minimalstipendium = 500,
      wohnkosten_fam_1pers = 10009,
      wohnkosten_fam_2pers = 13536,
      wohnkosten_fam_3pers = 16260,
      wohnkosten_fam_4pers = 19932,
      wohnkosten_fam_5pluspers = 25260,
      wohnkosten_persoenlich_1pers = 13536,
      wohnkosten_persoenlich_2pers = 16260,
      wohnkosten_persoenlich_3pers = 16260,
      wohnkosten_persoenlich_4pers = 19932,
      wohnkosten_persoenlich_5pluspers = 25260
  WHERE id = '3fa85f64-5717-4562-b3fc-2c963f66afa6';
