include:
  - local: '.gitlab/common.gitlab-ci.yml'

stages:
  - build
  - deploy

variables:
  VERSION: $CI_COMMIT_SHORT_SHA

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: $CI_COMMIT_TAG

# {{#each projects}}

build:{{ this }}:
  stage: build
  extends: .base
  script:
    - npx nx build --project {{this}}
  artifacts:
    paths:
      - 'dist/apps/{{ this }}'
    when: on_success
    expire_in: '1 day'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG

build:{{ this }}:image:
  extends: .docker-build
  variables:
    IMAGE_PATH: $DVB_PUBLIC_DOCKER_REGISTRY/$CI_PROJECT_ROOT_NAMESPACE/stip/{{ this }}:$VERSION
    KANIKO_ARGS: '--build-arg APP={{ this }}'
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH
      variables:
        KANIKO_ARGS: '--no-push --build-arg APP={{ this }}'
  needs:
    - job: build:{{ this }}
      artifacts: true

deploy:{{ this }}:
  stage: deploy
  image: '$DVB_DOCKER_REGISTRY/devops/docker/tools/k8s/main'
  tags: ['os:linux', 'type:docker', 'zone:tz']
  variables:
    STAGE: dev
    IMAGE_PATH: $DVB_PUBLIC_DOCKER_REGISTRY/$CI_PROJECT_ROOT_NAMESPACE/stip/{{ this }}:$VERSION
    GIT_STRATEGY: none
  before_script:
    - rm -rf ./*
    - git clone --branch $CI_DEFAULT_BRANCH --single-branch https://deploy:$DEPLOYMENT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git .
    - git checkout $CI_DEFAULT_BRANCH
  script:
    - cd deploy/$STAGE
    - kustomize edit set image $IMAGE_PATH
    - 'git commit --no-verify -a -m "ci($STAGE): deploy image $IMAGE_PATH"'
    - git push -o ci.skip origin HEAD:$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_DEPLOY_FREEZE == null
      variables:
        STAGE: dev
    - if: $CI_COMMIT_TAG
      variables:
        STAGE: uat
  needs:
    - job: build:{{ this }}:image

# {{else}}

build:empty:
  stage: build
  extends: .base
  script:
    - echo 'No apps affected!'
# {{/each}}
