include:
  - project: 'devops/gitlab/templates'
    file:
      - '/docker/docker.gitlab-ci.yml'

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  GIT_DEPTH: 0

.node-cache: &node-cache
  key:
    files:
      - package.json
      - package-lock.json
  paths:
    - node_modules/
  policy: pull-push

.npm-cache: &npm-cache
  key:
    files:
      - package-lock.json
  paths:
    - .npm
  policy: pull-push

.base:
  image: docker-registry.dvbern.ch/devops/docker/buildenvs/node/18
  tags: ['os:linux', 'zone:tz', 'type:docker']
  cache:
    - <<: *node-cache
    - <<: *npm-cache
  before_script:
    - '[ ! -d node_modules ] && npm ci --legacy-peer-deps --cache=".npm" --ignore-scripts ||
      echo "Skipping npm ci because a cached version is available"'
    - NX_HEAD=${NX_HEAD:-$CI_COMMIT_SHA}
    - NX_BASE=f0731bcdddd7e5f20db7519f1916edb3d90ea998
    - echo "NX_HEAD $NX_HEAD"
    - echo "NX_BASE $NX_BASE"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == 'web'
      variables:
        NX_BASE: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
