apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
  - ../../base

images:
  - name: docker-registry.dvbern.ch/kibon/stip-web/gesuch-app
    newTag: test

patches:
  - target:
      kind: Route
    path: route-patch.yml
