package ch.dvbern.stip.api.gesuch.type;

import lombok.Getter;

@Getter
public enum GesuchStatusChangeEvent {
    ABKLAERUNG_DURCH_RECHSTABTEILUNG,
    VERFUEGT,
    VERSANDBEREIT,
    VERSENDET,
    WARTEN_AUF_UNTERSCHRIFTENBLATT,
    IN_BEARBEITUNG_SB,
    IN_FREIGABE,
    IN_BEARBEITUNG_GS,
    ANSPRUCH_MANUELL_PRUEFEN,
    BEREIT_FUER_BEARBEITUNG,
    EINGEREICHT,
    JOUR_FIX,
    FEHLENDE_DOKUMENTE,
    NICHT_ANSPRUCHSBERECHTIGT,
    KEIN_STIPENDIENANSPRUCH,
    NICHT_BEITRAGSBERECHTIGT,
    GESUCH_ABGELEHNT
}
