package ch.dvbern.stip.api.gesuch.type;

import lombok.Getter;

@Getter
public enum GesuchStatusChangeEvent {
    GESUCH_EINGEREICHT,
    BEREIT_FUER_BEARBEITUNG,
    DOKUMENTE_NACHGELIEFERT,
    KEINE_DOKUMENTE_NACHGELIEFERT,
    ABKLAERUNG_DURCH_RECHSTABTEILUNG,
    ANSPRUCH_MANUELL_PRUEFEN,
    NICHT_ANSPRUCHSBERECHTIGT,
    IN_BEARBEITUNG_SB,
    GESUCH_ABGELEHNT,
    NICHT_BEITRAGSBERECHTIGT,
    REVISION_IN_PRUEFUNG,
    JOUR_FIX,
    FEHLENDE_DOKUMENTE,
    IN_FREIGABE,
    VERFUEGT,
    WARTEN_AUF_UNTERSCHRIFTENBLATT,
    VERSANDBEREIT,
    VERSENDET,
    KEIN_STIPENDIEN_ANSPRUCH,
    BEREIT_FUER_AUSZAHLUNG,
    UEBERMITTELT_AN_SAP
}
