package ch.dvbern.stip.lebenslauf.model;

public enum Bildungsart {
    BERUFSVORBEREITENDES_SCHULJAHR_VORLEHRE,
    GYMNASIALE_MATURITAETSSCHULEN,
    SCHULEN_FUER_ALLGEMEINBILDUNG,
    VOLLZEITBERUFSSCHULEN,
    LEHREN_ANLEHREN,
    BERUFSMATURITAET_NACH_LEHRE,
    HOEHERE_BERUFSBILDUNG,
    FACHHOCHSCHULEN,
    UNIVERSITAETEN_ETH;
}
