gesuchId:
  name: gesuchId
  in: path
  required: true
  description: Die ID vom Gesuch
  schema:
    $ref: './common.yaml#/UUID'
gesuchTrancheId:
  name: gesuchTrancheId
  in: path
  required: true
  description: Die ID von der GesuchTranche
  schema:
    $ref: './common.yaml#/UUID'
fallId:
  name: fallId
  in: path
  required: true
  description: Die ID vom Fall
  schema:
    $ref: './common.yaml#/UUID'
fallNummer:
  in: query
  name: fallNummer
  schema:
    type: string
piaVorname:
  in: query
  name: piaVorname
  schema:
    type: string
piaNachname:
  in: query
  name: piaNachname
  schema:
    type: string
piaGeburtsdatum:
  in: query
  name: piaGeburtsdatum
  schema:
    type: string
    format: date
bearbeiter:
  in: query
  name: bearbeiter
  schema:
    type: string
status:
  in: query
  name: status
  schema:
    type: string
page:
  in: query
  name: page
  required: true
  schema:
    type: integer
pageSize:
  in: query
  name: pageSize
  required: true
  schema:
    type: integer
sortOrder:
  in: query
  name: sortOrder
  schema:
    $ref: './common.yaml#/SortOrder'
userErstellt:
  in: query
  name: userErstellt
  schema:
    type: string
timestampErstellt:
  in: query
  name: timestampErstellt
  schema:
    type: string
    format: date
letzteAktivitaetFrom:
  in: query
  name: letzteAktivitaetFrom
  schema:
    type: string
    format: date
letzteAktivitaetTo:
  in: query
  name: letzteAktivitaetTo
  schema:
    type: string
    format: date

sozialdienstId:
  name: sozialdienstId
  schema:
    $ref: './common.yaml#/UUID'
  in: path
  required: true
