apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
data:
  host: "stip.dev.apps.test.kibon.ch"
  host-sb: "stip-sb.dev.apps.test.kibon.ch"
  identityHost: "auth.stip.dev.apps.test.kibon.ch"
