apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: "185.125.165.125"
