import { Signal, computed } from '@angular/core';

import { SharedTranslationKey } from '@dv/shared/assets/i18n';
import {
  CustomDokumentOptions,
  DokumentInfoTranslatable,
  DokumentOptions,
  GenericDokumentOptions,
  SharedModelGenericDokument,
  StandardDokumentOptions,
} from '@dv/shared/model/dokument';
import {
  CustomDokumentTyp,
  DarlehenDokumentType,
  Dokument,
  DokumentTyp,
  FreiwilligDarlehen,
  GesuchDokument,
  UnterschriftenblattDokument,
  UnterschriftenblattDokumentTyp,
} from '@dv/shared/model/gesuch';
import {
  DarlehenPermissionMap,
  PermissionMap,
} from '@dv/shared/model/permission-state';

export const DARLEHEN_DOKUMENT_TYP_TO_DOCUMENT_OPTIONS: {
  readonly [K in DarlehenDokumentType]: SharedTranslationKey;
} & Partial<
  Record<`${DarlehenDokumentType}_DESCRIPTION`, SharedTranslationKey>
> = {
  BETREIBUNGS_AUSZUG: 'shared.form.darlehen.file.BETREIBUNGSREGISTERAUSZUG',
  BETREIBUNGS_AUSZUG_DESCRIPTION:
    'shared.form.darlehen.file.BETREIBUNGSREGISTERAUSZUG_DESCRIPTION',
  AUFSTELLUNG_KOSTEN_ELTERN:
    'shared.form.darlehen.file.AUFSTELLUNG_KOSTEN_ELTERN',
  AUFSTELLUNG_KOSTEN_ELTERN_DESCRIPTION:
    'shared.form.darlehen.file.AUFSTELLUNG_KOSTEN_ELTERN_DESCRIPTION',
  KOPIE_SCHULGELDRECHNUNG: 'shared.form.darlehen.file.SCHULGELDRECHNUNG',
  KOPIE_SCHULGELDRECHNUNG_DESCRIPTION:
    'shared.form.darlehen.file.SCHULGELDRECHNUNG_DESCRIPTION',
  BELEGE_ANSCHAFFUNGEN: 'shared.form.darlehen.file.BELEGE_ANSCHAFFUNGEN',
  BELEGE_ANSCHAFFUNGEN_DESCRIPTION:
    'shared.form.darlehen.file.BELEGE_ANSCHAFFUNGEN_DESCRIPTION',
};

export const DOKUMENT_TYP_TO_DOCUMENT_OPTIONS: {
  readonly [K in DokumentTyp]: SharedTranslationKey;
} & Partial<Record<`${DokumentTyp}_DESCRIPTION`, SharedTranslationKey>> = {
  AUSBILDUNG_BESTAETIGUNG_AUSBILDUNGSSTAETTE:
    'contract.file.AUSBILDUNG_BESTAETIGUNG_AUSBILDUNGSSTAETTE',
  AUSBILDUNG_BESTAETIGUNG_AUSBILDUNGSSTAETTE_DESCRIPTION:
    'contract.file.AUSBILDUNG_BESTAETIGUNG_AUSBILDUNGSSTAETTE_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_SAISONARBEITEND_A:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_SAISONARBEITEND_A',
  PERSON_NIEDERLASSUNGSSTATUS_SAISONARBEITEND_A_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_SAISONARBEITEND_A_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_B: 'contract.file.PERSON_NIEDERLASSUNGSSTATUS_B',
  PERSON_NIEDERLASSUNGSSTATUS_B_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_B_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_C: 'contract.file.PERSON_NIEDERLASSUNGSSTATUS_C',
  PERSON_NIEDERLASSUNGSSTATUS_C_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_C_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_PARTNER_ERWERBSTAETIG_UND_KIND_CI:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_PARTNER_ERWERBSTAETIG_UND_KIND_CI',
  PERSON_NIEDERLASSUNGSSTATUS_PARTNER_ERWERBSTAETIG_UND_KIND_CI_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_PARTNER_ERWERBSTAETIG_UND_KIND_CI_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_OHNE_FLUECHTLINGSSTATUS:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_OHNE_FLUECHTLINGSSTATUS',
  PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_OHNE_FLUECHTLINGSSTATUS_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_OHNE_FLUECHTLINGSSTATUS_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ZUESTAENDIGER_KANTON_TENANT:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ZUESTAENDIGER_KANTON_TENANT',
  PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ZUESTAENDIGER_KANTON_TENANT_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ZUESTAENDIGER_KANTON_TENANT_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ANDERER_ZUESTAENDIGER_KANTON:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ANDERER_ZUESTAENDIGER_KANTON',
  PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ANDERER_ZUESTAENDIGER_KANTON_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_VORLAEUFIG_AUFGENOMMEN_F_ANDERER_ZUESTAENDIGER_KANTON_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_GRENZGAENGIG_G:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_GRENZGAENGIG_G',
  PERSON_NIEDERLASSUNGSSTATUS_GRENZGAENGIG_G_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_GRENZGAENGIG_G_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_KURZAUFENTHALT_L:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_KURZAUFENTHALT_L',
  PERSON_NIEDERLASSUNGSSTATUS_KURZAUFENTHALT_L_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_KURZAUFENTHALT_L_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_ASYLSUCHEND_N:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_ASYLSUCHEND_N',
  PERSON_NIEDERLASSUNGSSTATUS_ASYLSUCHEND_N_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_ASYLSUCHEND_N_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_SCHUTZBEDUERFTIG_S:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_SCHUTZBEDUERFTIG_S',
  PERSON_NIEDERLASSUNGSSTATUS_SCHUTZBEDUERFTIG_S_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_SCHUTZBEDUERFTIG_S_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_MELDEPFLICHTIG:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_MELDEPFLICHTIG',
  PERSON_NIEDERLASSUNGSSTATUS_MELDEPFLICHTIG_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_MELDEPFLICHTIG_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_DIPLOMATISCHE_FUNKTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_DIPLOMATISCHE_FUNKTION',
  PERSON_NIEDERLASSUNGSSTATUS_DIPLOMATISCHE_FUNKTION_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_DIPLOMATISCHE_FUNKTION_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_INTERNATIONALE_FUNKTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_INTERNATIONALE_FUNKTION',
  PERSON_NIEDERLASSUNGSSTATUS_INTERNATIONALE_FUNKTION_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_INTERNATIONALE_FUNKTION_DESCRIPTION',
  PERSON_NIEDERLASSUNGSSTATUS_NICHT_ZUGETEILT:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_NICHT_ZUGETEILT',
  PERSON_NIEDERLASSUNGSSTATUS_NICHT_ZUGETEILT_DESCRIPTION:
    'contract.file.PERSON_NIEDERLASSUNGSSTATUS_NICHT_ZUGETEILT_DESCRIPTION',
  PERSON_BEGRUENDUNGSSCHREIBEN_ALTER_AUSBILDUNGSBEGIN:
    'contract.file.PERSON_BEGRUENDUNGSSCHREIBEN_ALTER_AUSBILDUNGSBEGIN',
  PERSON_BEGRUENDUNGSSCHREIBEN_ALTER_AUSBILDUNGSBEGIN_DESCRIPTION:
    'contract.file.PERSON_BEGRUENDUNGSSCHREIBEN_ALTER_AUSBILDUNGSBEGIN_DESCRIPTION',
  PERSON_KESB_ERNENNUNG: 'contract.file.PERSON_KESB_ERNENNUNG',
  PERSON_EIGENER_HAUSHALT: 'contract.file.PERSON_EIGENER_HAUSHALT',
  PERSON_EIGENER_HAUSHALT_DESCRIPTION:
    'contract.file.PERSON_EIGENER_HAUSHALT_DESCRIPTION',
  PERSON_SOZIALHILFEBUDGET: 'contract.file.PERSON_SOZIALHILFEBUDGET',
  PERSON_TRENNUNG_ODER_UNTERHALTS_BELEG:
    'contract.file.PERSON_TRENNUNG_ODER_UNTERHALTS_BELEG',
  PERSON_AUSWEIS: 'contract.file.PERSON_AUSWEIS',
  FAMILIENSITUATION_GEBURTSSCHEIN:
    'contract.file.FAMILIENSITUATION_GEBURTSSCHEIN',
  FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_VATER:
    'contract.file.FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_VATER',
  FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_VATER_DESCRIPTION:
    'contract.file.FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_DESCRIPTION',
  FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_MUTTER:
    'contract.file.FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_MUTTER',
  FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_MUTTER_DESCRIPTION:
    'contract.file.FAMILIENSITUATION_AUFENTHALT_UNBEKANNT_DESCRIPTION',
  FAMILIENSITUATION_TRENNUNGSKONVENTION:
    'contract.file.FAMILIENSITUATION_TRENNUNGSKONVENTION',
  FAMILIENSITUATION_TRENNUNGSKONVENTION_DESCRIPTION:
    'contract.file.FAMILIENSITUATION_TRENNUNGSKONVENTION_DESCRIPTION',
  ELTERN_SOZIALHILFEBUDGET_VATER:
    'contract.file.ELTERN_SOZIALHILFEBUDGET_VATER',
  ELTERN_SOZIALHILFEBUDGET_VATER_DESCRIPTION:
    'contract.file.ELTERN_SOZIALHILFEBUDGET_VATER_DESCRIPTION',
  ELTERN_SOZIALHILFEBUDGET_MUTTER:
    'contract.file.ELTERN_SOZIALHILFEBUDGET_MUTTER',
  ELTERN_SOZIALHILFEBUDGET_MUTTER_DESCRIPTION:
    'contract.file.ELTERN_SOZIALHILFEBUDGET_MUTTER_DESCRIPTION',
  ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_VATER:
    'contract.file.ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_VATER',
  ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_VATER_DESCRIPTION:
    'contract.file.ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_DESCRIPTION',
  ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_MUTTER:
    'contract.file.ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_MUTTER',
  ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_MUTTER_DESCRIPTION:
    'contract.file.ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_DESCRIPTION',
  ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_FAMILIE:
    'contract.file.ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_FAMILIE',
  ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_FAMILIE_DESCRIPTION:
    'contract.file.ELTERN_MIETVERTRAG_HYPOTEKARZINSABRECHNUNG_DESCRIPTION',
  GESCHWISTER_BESTAETIGUNG_AUSBILDUNGSSTAETTE:
    'contract.file.GESCHWISTER_BESTAETIGUNG_AUSBILDUNGSSTAETTE',
  GESCHWISTER_BESTAETIGUNG_AUSBILDUNGSSTAETTE_DESCRIPTION:
    'contract.file.GESCHWISTER_BESTAETIGUNG_AUSBILDUNGSSTAETTE_DESCRIPTION',
  KINDER_UNTERHALTSVERTRAG_TRENNUNGSKONVENTION:
    'contract.file.KINDER_UNTERHALTSVERTRAG_TRENNUNGSKONVENTION',
  KINDER_ALIMENTENVERORDUNG: 'contract.file.KINDER_ALIMENTENVERORDUNG',
  KINDER_ALIMENTENVERORDUNG_DESCRIPTION:
    'contract.file.KINDER_ALIMENTENVERORDUNG_DESCRIPTION',
  KINDER_ERGAENZUNGSLEISTUNGEN: 'contract.file.KINDER_ERGAENZUNGSLEISTUNGEN',
  KINDER_ERGAENZUNGSLEISTUNGEN_DESCRIPTION:
    'contract.file.KINDER_ERGAENZUNGSLEISTUNGEN_DESCRIPTION',
  KINDER_UND_AUSBILDUNGSZULAGEN: 'contract.file.KINDER_UND_AUSBILDUNGSZULAGEN',
  KINDER_UND_AUSBILDUNGSZULAGEN_DESCRIPTION:
    'contract.file.KINDER_UND_AUSBILDUNGSZULAGEN_DESCRIPTION',
  KINDER_RENTEN: 'contract.file.KINDER_RENTEN',
  KINDER_RENTEN_DESCRIPTION: 'contract.file.KINDER_RENTEN_DESCRIPTION',
  KINDER_ANDERE_EINNAHMEN: 'contract.file.KINDER_ANDERE_EINNAHMEN',
  KINDER_ANDERE_EINNAHMEN_DESCRIPTION:
    'contract.file.KINDER_ANDERE_EINNAHMEN_DESCRIPTION',
  EK_BELEG_UNTERHALTSBEITRAEGE: 'contract.file.EK_BELEG_UNTERHALTSBEITRAEGE',
  EK_BELEG_UNTERHALTSBEITRAEGE_DESCRIPTION:
    'contract.file.EK_BELEG_UNTERHALTSBEITRAEGE_DESCRIPTION',
  EK_BELEG_EINNAHMEN_BGSA: 'contract.file.EK_BELEG_EINNAHMEN_BGSA',
  EK_BELEG_TAGGELDER_AHV_IV: 'contract.file.EK_BELEG_TAGGELDER_AHV_IV',
  EK_BELEG_ANDERE_EINNAHMEN: 'contract.file.EK_BELEG_ANDERE_EINNAHMEN',
  EK_BELEG_ANDERE_EINNAHMEN_DESCRIPTION:
    'contract.file.EK_BELEG_ANDERE_EINNAHMEN_DESCRIPTION',
  EK_BELEG_KINDERZULAGEN: 'contract.file.EK_BELEG_KINDERZULAGEN',
  EK_VERFUEGUNG_GEMEINDE_INSTITUTION:
    'contract.file.EK_VERFUEGUNG_GEMEINDE_INSTITUTION',
  EK_VERFUEGUNG_GEMEINDE_INSTITUTION_DESCRIPTION:
    'contract.file.EK_VERFUEGUNG_GEMEINDE_INSTITUTION_DESCRIPTION',
  EK_BELEG_BEZAHLTE_RENTEN: 'contract.file.EK_BELEG_BEZAHLTE_RENTEN',
  EK_VERFUEGUNG_ERGAENZUNGSLEISTUNGEN:
    'contract.file.EK_VERFUEGUNG_ERGAENZUNGSLEISTUNGEN',
  EK_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO:
    'contract.file.EK_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO',
  EK_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO_DESCRIPTION:
    'contract.file.EK_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO_DESCRIPTION',
  EK_BELEG_OV_ABONNEMENT: 'contract.file.EK_BELEG_OV_ABONNEMENT',
  EK_BELEG_OV_ABONNEMENT_DESCRIPTION:
    'contract.file.EK_BELEG_OV_ABONNEMENT_DESCRIPTION',
  EK_MIETVERTRAG: 'contract.file.EK_MIETVERTRAG',
  EK_BELEG_BETREUUNGSKOSTEN_KINDER:
    'contract.file.EK_BELEG_BETREUUNGSKOSTEN_KINDER',
  EK_BELEG_BETREUUNGSKOSTEN_KINDER_DESCRIPTION:
    'contract.file.EK_BELEG_BETREUUNGSKOSTEN_KINDER_DESCRIPTION',
  EK_LOHNABRECHNUNG: 'contract.file.EK_LOHNABRECHNUNG',
  EK_LOHNABRECHNUNG_DESCRIPTION: 'contract.file.EK_LOHNABRECHNUNG_DESCRIPTION',
  EK_VERMOEGEN: 'contract.file.EK_VERMOEGEN',
  EK_VERMOEGEN_DESCRIPTION: 'contract.file.EK_VERMOEGEN_DESCRIPTION',
  EK_PARTNER_BELEG_UNTERHALTSBEITRAEGE:
    'contract.file.EK_PARTNER_BELEG_UNTERHALTSBEITRAEGE',
  EK_PARTNER_BELEG_UNTERHALTSBEITRAEGE_DESCRIPTION:
    'contract.file.EK_PARTNER_BELEG_UNTERHALTSBEITRAEGE_DESCRIPTION',
  EK_PARTNER_BELEG_EINNAHMEN_BGSA:
    'contract.file.EK_PARTNER_BELEG_EINNAHMEN_BGSA',
  EK_PARTNER_BELEG_TAGGELDER_AHV_IV:
    'contract.file.EK_PARTNER_BELEG_TAGGELDER_AHV_IV',
  EK_PARTNER_BELEG_ANDERE_EINNAHMEN:
    'contract.file.EK_PARTNER_BELEG_ANDERE_EINNAHMEN',
  EK_PARTNER_BELEG_ANDERE_EINNAHMEN_DESCRIPTION:
    'contract.file.EK_PARTNER_BELEG_ANDERE_EINNAHMEN_DESCRIPTION',
  EK_PARTNER_BELEG_KINDERZULAGEN:
    'contract.file.EK_PARTNER_BELEG_KINDERZULAGEN',
  EK_PARTNER_VERFUEGUNG_GEMEINDE_INSTITUTION:
    'contract.file.EK_PARTNER_VERFUEGUNG_GEMEINDE_INSTITUTION',
  EK_PARTNER_VERFUEGUNG_GEMEINDE_INSTITUTION_DESCRIPTION:
    'contract.file.EK_PARTNER_VERFUEGUNG_GEMEINDE_INSTITUTION_DESCRIPTION',
  EK_PARTNER_BELEG_BEZAHLTE_RENTEN:
    'contract.file.EK_PARTNER_BELEG_BEZAHLTE_RENTEN',
  EK_PARTNER_VERFUEGUNG_ERGAENZUNGSLEISTUNGEN:
    'contract.file.EK_PARTNER_VERFUEGUNG_ERGAENZUNGSLEISTUNGEN',
  EK_PARTNER_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO:
    'contract.file.EK_PARTNER_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO',
  EK_PARTNER_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO_DESCRIPTION:
    'contract.file.EK_PARTNER_ENTSCHEID_ERGAENZUNGSLEISTUNGEN_EO_DESCRIPTION',
  EK_PARTNER_BELEG_OV_ABONNEMENT:
    'contract.file.EK_PARTNER_BELEG_OV_ABONNEMENT',
  EK_PARTNER_BELEG_OV_ABONNEMENT_DESCRIPTION:
    'contract.file.EK_PARTNER_BELEG_OV_ABONNEMENT_DESCRIPTION',
  EK_PARTNER_BELEG_BETREUUNGSKOSTEN_KINDER:
    'contract.file.EK_PARTNER_BELEG_BETREUUNGSKOSTEN_KINDER',
  EK_PARTNER_BELEG_BETREUUNGSKOSTEN_KINDER_DESCRIPTION:
    'contract.file.EK_PARTNER_BELEG_BETREUUNGSKOSTEN_KINDER_DESCRIPTION',
  EK_PARTNER_LOHNABRECHNUNG: 'contract.file.EK_PARTNER_LOHNABRECHNUNG',
  EK_PARTNER_VERMOEGEN: 'contract.file.EK_PARTNER_VERMOEGEN',
  EK_PARTNER_VERMOEGEN_DESCRIPTION:
    'contract.file.EK_PARTNER_VERMOEGEN_DESCRIPTION',
  ELTERN_LOHNABRECHNUNG_VERMOEGEN_VATER:
    'contract.file.ELTERN_LOHNABRECHNUNG_VERMOEGEN_VATER',
  ELTERN_LOHNABRECHNUNG_VERMOEGEN_VATER_DESCRIPTION:
    'contract.file.ELTERN_LOHNABRECHNUNG_VERMOEGEN_DESCRIPTION',
  ELTERN_LOHNABRECHNUNG_VERMOEGEN_MUTTER:
    'contract.file.ELTERN_LOHNABRECHNUNG_VERMOEGEN_MUTTER',
  ELTERN_LOHNABRECHNUNG_VERMOEGEN_MUTTER_DESCRIPTION:
    'contract.file.ELTERN_LOHNABRECHNUNG_VERMOEGEN_DESCRIPTION',
  STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_FAMILIE:
    'contract.file.STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_FAMILIE',
  STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_FAMILIE_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_DESCRIPTION_FAMILIE',
  STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_MUTTER:
    'contract.file.STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_MUTTER',
  STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_MUTTER_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_DESCRIPTION_MUTTER',
  STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_VATER:
    'contract.file.STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_VATER',
  STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_VATER_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_AUSBILDUNGSBEITRAEGE_DESCRIPTION_VATER',
  STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_VATER:
    'contract.file.STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_VATER',
  STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_VATER_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_VATER_DESCRIPTION',
  STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_MUTTER:
    'contract.file.STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_MUTTER',
  STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_MUTTER_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_MUTTER_DESCRIPTION',
  STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_FAMILIE:
    'contract.file.STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_FAMILIE',
  STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_FAMILIE_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_UNTERHALTSBEITRAEGE_FAMILIE_DESCRIPTION',
  STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_VATER:
    'contract.file.STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_VATER',
  STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_MUTTER:
    'contract.file.STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_MUTTER',
  STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_FAMILIE:
    'contract.file.STEUERERKLAERUNG_ERGAENZUNGSLEISTUNGEN_FAMILIE',
  STEUERERKLAERUNG_RENTEN_VATER: 'contract.file.STEUERERKLAERUNG_RENTEN_VATER',
  STEUERERKLAERUNG_RENTEN_VATER_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_RENTEN_VATER_DESCRIPTION',
  STEUERERKLAERUNG_RENTEN_MUTTER:
    'contract.file.STEUERERKLAERUNG_RENTEN_MUTTER',
  STEUERERKLAERUNG_RENTEN_MUTTER_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_RENTEN_MUTTER_DESCRIPTION',
  STEUERERKLAERUNG_RENTEN_FAMILIE:
    'contract.file.STEUERERKLAERUNG_RENTEN_FAMILIE',
  STEUERERKLAERUNG_RENTEN_FAMILIE_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_RENTEN_FAMILIE_DESCRIPTION',
  STEUERERKLAERUNG_EINNAHMEN_BGSA_VATER:
    'contract.file.STEUERERKLAERUNG_EINNAHMEN_BGSA_VATER',
  STEUERERKLAERUNG_EINNAHMEN_BGSA_MUTTER:
    'contract.file.STEUERERKLAERUNG_EINNAHMEN_BGSA_MUTTER',
  STEUERERKLAERUNG_EINNAHMEN_BGSA_FAMILIE:
    'contract.file.STEUERERKLAERUNG_EINNAHMEN_BGSA_FAMILIE',
  STEUERERKLAERUNG_ANDERE_EINNAHMEN_VATER:
    'contract.file.STEUERERKLAERUNG_ANDERE_EINNAHMEN_VATER',
  STEUERERKLAERUNG_ANDERE_EINNAHMEN_VATER_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_ANDERE_EINNAHMEN_VATER_DESCRIPTION',
  STEUERERKLAERUNG_ANDERE_EINNAHMEN_MUTTER:
    'contract.file.STEUERERKLAERUNG_ANDERE_EINNAHMEN_MUTTER',
  STEUERERKLAERUNG_ANDERE_EINNAHMEN_MUTTER_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_ANDERE_EINNAHMEN_MUTTER_DESCRIPTION',
  STEUERERKLAERUNG_ANDERE_EINNAHMEN_FAMILIE:
    'contract.file.STEUERERKLAERUNG_ANDERE_EINNAHMEN_FAMILIE',
  STEUERERKLAERUNG_ANDERE_EINNAHMEN_FAMILIE_DESCRIPTION:
    'contract.file.STEUERERKLAERUNG_ANDERE_EINNAHMEN_FAMILIE_DESCRIPTION',
};

/**
 * Factory function to create a computed signal that returns an upload options object for a given view
 *
 * The view should have the following properties:
 * - **gesuchTrancheId**: string | undefined
 * - **allowTypes**:      string | undefined
 * - **readonly**:        boolean
 *
 * @example
 * ```typescript
 * import { selectSharedDataAccessConfigsView } from '@dv/shared/data-access/config';
 *
 * const viewSelector = createSelector(
     selectSharedDataAccessConfigsView, // to obtain the allowTypes
     ...
 * );
 * ...
 * viewSig = this.store.selectSignal(viewSelector);
 *
 * createUploadOptionsSig = createUploadOptionsFactory(this.viewSig);
 * ...
 * wohnsitzBeiDocumentOptionsSig = this.createUploadOptionsSig(() => {
 *   const wohnsitzBei = this.wohnsitzBeiChangedSig();
 *   return wohnsitzBei === Wohnsitz.EIGENER_HAUSHALT
 *     ? DokumentTyp.PERSON_EIGENER_HAUSHALT
 *     : null;
 * });
 * ```
 */
export function createUploadOptionsFactory<
  T extends Signal<{
    trancheId: string | undefined;
    allowTypes: string | undefined;
    permissions: PermissionMap;
  }>,
>(view: T, entryIdSig?: Signal<string>) {
  /**
   * Used to obtain a computed signal which returns an upload options object or `null` if the upload is not required
   *
   * @see {@link createUploadOptionsFactory}
   * @example
   * ```typescript
   * createUploadOptionsSig(() => {
   *   const wohnsitzBei = this.wohnsitzBeiChangedSig();
   *   return wohnsitzBei === Wohnsitz.EIGENER_HAUSHALT
   *     ? DokumentTyp.PERSON_EIGENER_HAUSHALT
   *     : null;
   * });
   * ```
   *
   * @param lazyDokumentTyp - a function that should return the {@link DokumentTyp} or `null | undefined` if the upload is not required
   * @param options - some additional options for the upload.
   *                  If initialDocuments are provided, the the upload component will not try to fetch the documents on initialization,
   *                  but display the provided documents instead. Primarily used for Dokument Table view.
   */
  return (
    lazyDokumentTyp: (view: T) => DokumentTyp | null | undefined,
    options?: { initialDocuments?: Dokument[] },
  ) => {
    return computed<DokumentOptions | null>(() => {
      const { permissions, trancheId, allowTypes } = view();
      const entryId = entryIdSig?.();
      const dokumentTyp = lazyDokumentTyp(view);
      return dokumentTyp && trancheId && allowTypes
        ? {
            allowTypes,
            info: {
              type: 'TRANSLATABLE',
              title: DOKUMENT_TYP_TO_DOCUMENT_OPTIONS[dokumentTyp],
              description:
                DOKUMENT_TYP_TO_DOCUMENT_OPTIONS[`${dokumentTyp}_DESCRIPTION`],
            },
            dokument: {
              permissions,
              trancheId,
              entryId,
              dokumentTyp,
              art: 'GESUCH_DOKUMENT',
            },
            initialDokumente: options?.initialDocuments,
          }
        : null;
    });
  };
}

export function createDarlehenUploadOptionsFactory<
  T extends {
    darlehen: Signal<FreiwilligDarlehen | null | undefined>;
    allowTypes: string | undefined;
    permissions: Signal<DarlehenPermissionMap | undefined>;
  },
>(view: T) {
  return (
    lazyDokumentTyp: (view: T) => DarlehenDokumentType | null | undefined,
  ) => {
    return computed<DokumentOptions | null>(() => {
      const dokumentTyp = lazyDokumentTyp(view);
      const darlehenId = view.darlehen()?.id;
      const permissions = view.permissions();
      const allowTypes = view.allowTypes;
      return dokumentTyp && darlehenId && allowTypes && permissions
        ? {
            allowTypes,
            info: {
              type: 'TRANSLATABLE',
              title: DARLEHEN_DOKUMENT_TYP_TO_DOCUMENT_OPTIONS[dokumentTyp],
              description:
                DARLEHEN_DOKUMENT_TYP_TO_DOCUMENT_OPTIONS[
                  `${dokumentTyp}_DESCRIPTION`
                ],
            },
            dokument: {
              permissions,
              darlehenId,
              dokumentTyp,
              art: 'DARLEHEN_DOKUMENT',
            },
          }
        : null;
    });
  };
}

export function createGesuchDokumentOptions(options: {
  trancheId: string;
  entryId: string | undefined;
  allowTypes: string;
  dokumentTyp: DokumentTyp;
  gesuchDokument?: GesuchDokument;
  initialDocuments?: Dokument[];
  permissions: PermissionMap;
}): StandardDokumentOptions {
  const {
    trancheId,
    entryId,
    allowTypes,
    dokumentTyp,
    gesuchDokument,
    initialDocuments,
    permissions,
  } = options;
  return {
    allowTypes,
    info: {
      type: 'TRANSLATABLE',
      title: DOKUMENT_TYP_TO_DOCUMENT_OPTIONS[dokumentTyp],
      description:
        DOKUMENT_TYP_TO_DOCUMENT_OPTIONS[`${dokumentTyp}_DESCRIPTION`],
    },
    dokument: {
      permissions,
      dokumentTyp,
      trancheId,
      entryId,
      gesuchDokument,
      art: 'GESUCH_DOKUMENT',
    },
    initialDokumente: initialDocuments,
  };
}

export function createAdditionalDokumentOptions(options: {
  gesuchId: string;
  trancheId: string;
  allowTypes: string;
  dokumentTyp: UnterschriftenblattDokumentTyp;
  gesuchDokument?: UnterschriftenblattDokument;
  initialDocuments?: Dokument[];
  permissions: PermissionMap;
}): StandardDokumentOptions {
  const {
    gesuchId,
    trancheId,
    allowTypes,
    dokumentTyp,
    gesuchDokument,
    initialDocuments,
    permissions,
  } = options;
  return {
    allowTypes,
    info: {
      type: 'TRANSLATABLE',
      title: `shared.dokumente.file.unterschriftenblatt.${dokumentTyp}`,
    },
    dokument: {
      permissions,
      dokumentTyp,
      gesuchId,
      trancheId,
      art: 'UNTERSCHRIFTENBLATT',
      gesuchDokument,
    },
    initialDokumente: initialDocuments,
  };
}

export function createCustomDokumentOptions(options: {
  gesuchId: string;
  trancheId: string;
  allowTypes: string;
  dokumentTyp: CustomDokumentTyp;
  gesuchDokument?: GesuchDokument;
  initialDocuments?: Dokument[];
  permissions: PermissionMap;
}): CustomDokumentOptions {
  const {
    gesuchId,
    trancheId,
    allowTypes,
    dokumentTyp,
    gesuchDokument,
    initialDocuments,
    permissions,
  } = options;
  return {
    allowTypes,
    info: {
      type: 'TEXT',
      title: dokumentTyp.type,
      description: dokumentTyp.description,
    },
    dokument: {
      permissions,
      dokumentTyp,
      gesuchId,
      trancheId,
      gesuchDokument,
      art: 'CUSTOM_DOKUMENT',
    },
    initialDokumente: initialDocuments,
  };
}

export function createSimpleDokumentOptions(options: {
  allowTypes: string;
  id: string;
  dokumentTyp: SharedModelGenericDokument['dokumentTyp'];
  initialDokumente: Dokument[];
  info: DokumentInfoTranslatable;
  readonly: boolean;
}): GenericDokumentOptions {
  const { allowTypes, id, initialDokumente, dokumentTyp, info, readonly } =
    options;
  return {
    allowTypes,
    dokument: {
      art: 'GENERIC_DOKUMENT',
      readonly,
      dokumentTyp,
      id,
    },
    info,
    initialDokumente,
  };
}
