openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  /darlehen/{fallId}:
    parameters:
      - name: fallId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          description: Return active darlehen darlehen if exists or else null
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getActiveDarlehen
      summary: Return active darlehen darlehen if exists or else null
    post:
      tags:
        - Darlehen
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: createDarlehen
      summary: Create a new Darlehen

  /darlehen/{darlehenId}/{dokumentTyp}:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/Darlehen'
        in: path
        required: true
      - name: dokumentTyp
        schema:
          $ref: '#/components/schemas/DarlehenDokumnetTyp'
        in: path
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          description: Return Darlehen dokument
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DarlehenDokument'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getDarlehenDokument
      summary: Returns Darlehen dokument
    post:
      tags:
        - Darlehen
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DarlehenDokumentCreate'
      responses:
        '200':
          description: OK
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: createDarlehenDokument
      x-quarkus-response-type: io.smallrye.mutiny.Uni<Response>
  /darlehen/{darlehenId}/eingeben:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenEingeben
      summary: Change darlehen status to eingegeben

  /darlehen/{darlehenId}/freigeben:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenFreigeben
      summary: Change darlehen status to freigegeben

  /darlehen/{darlehenId}/zurueckweisen:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenZurueckweisen
      summary: Change darlehen status to in bearbeitung gs

  /darlehen/{darlehenId}/akzeptieren:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenAkzeptieren
      summary: Change darlehen status to akzeptiert

  /darlehen/{darlehenId}/ablehnen:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenAblehen
      summary: Change darlehen status to abgelehnt

  /darlehen/{darlehenId}/gs:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    patch:
      tags:
        - Darlehen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DarlehenUpdateGs'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenUpdateGs
      summary: Update darlehen as gs

  /darlehen/{darlehenId}/sb:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    patch:
      tags:
        - Darlehen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DarlehenUpdateSb'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenUpdateSb
      summary: Update darlehen as sb

components:
  securitySchemes:
    $ref: './components/security.yaml#/securitySchemes'

  schemas:
    DarlehenStatus:
      enum:
        - IN_BEARBEITUNG_GS
        - EINGEGEBEN
        - IN_FREIGABE
        - AKZEPTIERT
        - ABGELEHNT

    DarlehenDokumnetTyp:
      enum:
        - BETREIBUNGS_AUSZUG
        - AUFSTELLUNG_KOSTEN_ELTERN
        - KOPIE_SCHULGELDRECHNUNG
        - BELEGE_ANSCHAFFUNGEN

    DarlehenUpdateSb:
      type: object
      properties:
        darlehenGewaehren:
          type: boolean
        darlehenBetrag:
          type: integer
          minimum: 0
        kommentar:
          type: string

    DarlehenUpdateGs:
      type: object
      properties:
        darlehenBetragGewuenscht:
          type: integer
          minimum: 0
        schulden:
          type: integer
          minimum: 0
        anzahlBetreibungen:
          type: integer
          minimum: 0
        grund:
          $ref: './components/common.yaml#/DarlehenGrund'

    DarlehenDokument:
      type: object
      required:
        - id
        - dokumentTyp
        - dokumente
      properties:
        id:
          $ref: './components/common.yaml#/UUID'
        dokumentTyp:
          $ref: '#/components/schemas/DarlehenDokumnetTyp'
        dokumente:
          type: array
          items:
            $ref: './components/common.yaml#/Dokument'

    DarlehenDokumentCreate:
      type: object
      required:
        - fileUpload
      properties:
        fileUpload:
          $ref: './components/common.yaml#/FileUpload'


security:
  $ref: './components/security.yaml#/security'
