openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  /darlehen/dashboard/{getDarlehenSbQueryType}:
    parameters:
      - name: getDarlehenSbQueryType
        schema:
          $ref: '#/components/schemas/GetDarlehenSbQueryType'
        in: path
        required: true
      - $ref: './components/parameters.yaml#/fallNummer'
      - $ref: './components/parameters.yaml#/piaNachname'
      - $ref: './components/parameters.yaml#/piaVorname'
      - $ref: './components/parameters.yaml#/piaGeburtsdatum'
      - $ref: './components/parameters.yaml#/status'
      - $ref: './components/parameters.yaml#/bearbeiter'
      - $ref: './components/parameters.yaml#/letzteAktivitaetFrom'
      - $ref: './components/parameters.yaml#/letzteAktivitaetTo'
      - $ref: './components/parameters.yaml#/page'
      - $ref: './components/parameters.yaml#/pageSize'
      - name: sortColumn
        schema:
          $ref: '#/components/schemas/SbDarlehenDashboardColumn'
        in: query
      - $ref: './components/parameters.yaml#/sortOrder'
    get:
      tags:
        - Darlehen
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSbDarlehenDashboard'
          description: Returns gesuche filtered by status and sb
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getDarlehenDashboardSb
      summary: Returns darlehen filtered by status and sb

  /darlehen/{fallId}:
    parameters:
      - name: fallId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: createDarlehen
      summary: Create a new Darlehen

  '/darlehen/dokument/{dokumentId}/token':
    parameters:
      - name: dokumentId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/FileDownloadToken'
          description: Token returned
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
          description: File returned
      operationId: getDarlehenDownloadToken
      summary: get Token to downlaod Darlehen Dokument

  '/darlehen/dokument/download':
    parameters:
      - name: token
        schema:
          type: string
        in: query
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: File returned
      operationId: downloadDarlehenDokument
      summary: Download Darlehen Dokument
      x-quarkus-response-type: org.jboss.resteasy.reactive.RestMulti<io.vertx.mutiny.core.buffer.Buffer>

  '/darlehen/dokument/{dokumentId}':
    parameters:
      - name: dokumentId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    delete:
      tags:
        - Darlehen
      responses:
        '200':
          description: Dokument deleted
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: deleteDarlehenDokument
      summary: deletes a Darlehen Dokument

  /darlehen/dokument/{darlehenId}/{dokumentType}:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
      - name: dokumentType
        schema:
          $ref: '#/components/schemas/DarlehenDokumentType'
        in: path
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          description: Return Darlehen dokument
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NullableDarlehenDokument'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getDarlehenDokument
      summary: Returns Darlehen dokument
    post:
      tags:
        - Darlehen
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DarlehenDokumentCreate'
      responses:
        '200':
          description: OK
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: createDarlehenDokument
      x-quarkus-response-type: io.smallrye.mutiny.Uni<Response>

  /darlehen/{darlehenId}/eingeben:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenEingeben
      summary: Change darlehen status to eingegeben

  /darlehen/{darlehenId}/freigeben:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenFreigeben
      summary: Change darlehen status to freigegeben

  /darlehen/{darlehenId}/zurueckweisen:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/common.yaml#/Kommentar'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenZurueckweisen
      summary: Change darlehen status to in bearbeitung gs

  /darlehen/{darlehenId}/akzeptieren:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenAkzeptieren
      summary: Change darlehen status to akzeptiert

  /darlehen/{darlehenId}/ablehnen:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    post:
      tags:
        - Darlehen
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenAblehen
      summary: Change darlehen status to abgelehnt

  /darlehen/{darlehenId}/gs:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          description: Return active darlehen if exists or else null
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getDarlehenGs
      summary: Return active darlehen darlehen if exists or else null
    patch:
      tags:
        - Darlehen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DarlehenUpdateGs'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenUpdateGs
      summary: Update darlehen as gs
    delete:
      tags:
        - Darlehen
      responses:
        '204':
          description: Darlehen was deleted
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: deleteDarlehenGs
      summary: Deletes a given darlehen by ID

  /darlehen/getAllDarlehenGs/{fallId}:
    parameters:
      - name: fallId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          description: Return all darlehen for a given fallId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DarlehenGsResponse'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getAllDarlehenGs
      summary: Return all darlehen for a given fallId

  /darlehen/getAllDarlehenSb/{gesuchId}:
    parameters:
      - name: gesuchId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          description: Return all darlehen for a given fallId
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getAllDarlehenSb
      summary: Return all darlehen for a given fallId

  /darlehen/{darlehenId}/sb:
    parameters:
      - name: darlehenId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Darlehen
      responses:
        '200':
          description: Return darlehen
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getDarlehenSb
      summary: Return darlehen
    patch:
      tags:
        - Darlehen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DarlehenUpdateSb'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Darlehen'
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: darlehenUpdateSb
      summary: Update darlehen as sb

components:
  securitySchemes:
    $ref: './components/security.yaml#/securitySchemes'

  schemas:
    SbDarlehenDashboardColumn:
      enum:
        - FALLNUMMER
        - PIA_NACHNAME
        - PIA_VORNAME
        - PIA_GEBURTSDATUM
        - STATUS
        - BEARBEITER
        - LETZTE_AKTIVITAET

    GetDarlehenSbQueryType:
      enum:
        - ALLE_DARLEHEN
        - MEINE_DARLEHEN
        - ALLE_BEARBEITBAR
        - MEINE_BEARBEITBAR

    PaginatedSbDarlehenDashboard:
      allOf:
        - $ref: './components/common.yaml#/PaginatedResult'
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/DarlehenDashboard'

    DarlehenDashboard:
      type: object
      required:
        - id
        - fallId
        - relatedGesuchId
        - fallNummer
        - piaVorname
        - piaNachname
        - piaGeburtsdatum
        - status
        - bearbeiter
        - letzteAktivitaet
      properties:
        id:
          $ref: './components/common.yaml#/UUID'
        fallId:
          $ref: './components/common.yaml#/UUID'
        relatedGesuchId:
          $ref: './components/common.yaml#/UUID'
        fallNummer:
          type: string
        piaVorname:
          type: string
        piaNachname:
          type: string
        piaGeburtsdatum:
          type: string
        status:
          $ref: './components/common.yaml#/DarlehenStatus'
        bearbeiter:
          type: string
        letzteAktivitaet:
          type: string
          format: date

    DarlehenDokumentType:
      enum:
        - BETREIBUNGS_AUSZUG
        - AUFSTELLUNG_KOSTEN_ELTERN
        - KOPIE_SCHULGELDRECHNUNG
        - BELEGE_ANSCHAFFUNGEN

    DarlehenUpdateSb:
      type: object
      properties:
        gewaehren:
          type: boolean
        betrag:
          type: integer
          minimum: 0
        kommentar:
          type: string

    DarlehenUpdateGs:
      type: object
      properties:
        betragGewuenscht:
          type: integer
          minimum: 0
        schulden:
          type: integer
          minimum: 0
        anzahlBetreibungen:
          type: integer
          minimum: 0
        gruende:
          type: array
          items:
            $ref: './components/common.yaml#/DarlehenGrund'

    NullableDarlehenDokument:
      type: object
      properties:
        value:
          $ref: '#/components/schemas/DarlehenDokument'

    DarlehenGsResponse:
      type: object
      required:
        - darlehenList
        - canCreateDarlehen
      properties:
        darlehenList:
          type: array
          items:
            $ref: './components/common.yaml#/Darlehen'
        canCreateDarlehen:
          type: boolean

    DarlehenDokument:
      type: object
      required:
        - id
        - dokumentType
        - dokumente
      properties:
        id:
          $ref: './components/common.yaml#/UUID'
        dokumentType:
          $ref: '#/components/schemas/DarlehenDokumentType'
        dokumente:
          type: array
          items:
            $ref: './components/common.yaml#/Dokument'

    DarlehenDokumentCreate:
      type: object
      required:
        - fileUpload
      properties:
        fileUpload:
          $ref: './components/common.yaml#/FileUpload'

security:
  $ref: './components/security.yaml#/security'
