openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  /delegieren/{fallId}/{sozialdienstId}:
    parameters:
      - $ref: './components/parameters.yaml#/fallId'
      - $ref: './components/parameters.yaml#/sozialdienstId'
    post:
      tags:
        - Delegieren
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DelegierungCreate'
      responses:
        204:
          description: Das Gesuch wurde erfolgreich dem Sozialdienst delegiert
        401:
          $ref: './components/responses.yaml#/Unauthorized'
        403:
          $ref: './components/responses.yaml#/Forbidden'
        404:
          $ref: './components/responses.yaml#/NotFound'
        500:
          $ref: './components/responses.yaml#/ServerError'
      operationId: fallDelegieren
  /delegierung/{delegierungId}/mitarbeiterDelegieren:
    parameters:
      - $ref: '#/components/parameters/delegierungId'
    post:
      tags:
        - Delegieren
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DelegierterMitarbeiterAendern'
      responses:
        204:
          description: Der delegierte Mitarbeiter wurde erfolgreich geandert
        401:
          $ref: './components/responses.yaml#/Unauthorized'
        403:
          $ref: './components/responses.yaml#/Forbidden'
        404:
          $ref: './components/responses.yaml#/NotFound'
        500:
          $ref: './components/responses.yaml#/ServerError'
      operationId: delegierterMitarbeiterAendern
  /delegierung/{delegierungId}/ablehnen:
    parameters:
      - $ref: '#/components/parameters/delegierungId'
    delete:
      tags:
        - Delegieren
      responses:
        204:
          description: Die deleguerung wurde erfolgreich geloescht
        401:
          $ref: './components/responses.yaml#/Unauthorized'
        403:
          $ref: './components/responses.yaml#/Forbidden'
        404:
          $ref: './components/responses.yaml#/NotFound'
        500:
          $ref: './components/responses.yaml#/ServerError'
      operationId: delegierungAblehnen
  /delegierung/{delegierungId}/aufloesen:
    parameters:
      - $ref: '#/components/parameters/delegierungId'
    delete:
      tags:
        - Delegieren
      responses:
        204:
          description: Die deleguerung wurde erfolgreich aufgeloest
        401:
          $ref: './components/responses.yaml#/Unauthorized'
        403:
          $ref: './components/responses.yaml#/Forbidden'
        404:
          $ref: './components/responses.yaml#/NotFound'
        500:
          $ref: './components/responses.yaml#/ServerError'
      operationId: delegierungAufloesen
  /delegierung/{getDelegierungSozQueryType}/admin:
    get:
      tags:
        - Delegieren
      parameters:
        - name: getDelegierungSozQueryType
          schema:
            $ref: '#/components/schemas/GetDelegierungSozQueryTypeAdmin'
          in: path
          required: true
        - $ref: '#/components/parameters/fallNummer'
        - $ref: '#/components/parameters/nachname'
        - $ref: '#/components/parameters/vorname'
        - $ref: '#/components/parameters/geburtsdatum'
        - $ref: '#/components/parameters/wohnort'
        - $ref: '#/components/parameters/delegierungAngenommen'
        - $ref: './components/parameters.yaml#/page'
        - $ref: './components/parameters.yaml#/pageSize'
        - name: sortColumn
          schema:
            $ref: '#/components/schemas/SozDashboardColumn'
          in: query
          required: false
        - $ref: './components/parameters.yaml#/sortOrder'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSozDashboard'
          description: Returns FallWithDelegierung
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getDelegierungsOfSozialdienstAdmin
      summary: Returns a list of all Faelle with Delegierung
  /delegierung/{getDelegierungSozQueryType}/ma:
    get:
      tags:
        - Delegieren
      parameters:
        - name: getDelegierungSozQueryType
          schema:
            $ref: '#/components/schemas/GetDelegierungSozQueryTypeMitarbeiter'
          in: path
          required: true
        - $ref: '#/components/parameters/fallNummer'
        - $ref: '#/components/parameters/nachname'
        - $ref: '#/components/parameters/vorname'
        - $ref: '#/components/parameters/geburtsdatum'
        - $ref: '#/components/parameters/wohnort'
        - $ref: './components/parameters.yaml#/page'
        - $ref: './components/parameters.yaml#/pageSize'
        - name: sortColumn
          schema:
            $ref: '#/components/schemas/SozDashboardColumn'
          in: query
          required: false
        - $ref: './components/parameters.yaml#/sortOrder'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSozDashboard'
          description: Returns FallWithDelegierung
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getDelegierungsOfSozialdienstMitarbeiter
      summary: Returns a list of Faelle with Delegierung that are accepted
components:
  parameters:
    fallNummer:
      in: query
      name: fallNummer
      schema:
        type: string
    wohnort:
      in: query
      name: wohnort
      schema:
        type: string
    geburtsdatum:
      in: query
      name: geburtsdatum
      schema:
        type: string
        format: date
    delegierungAngenommen:
      in: query
      name: delegierungAngenommen
      schema:
        type: boolean
    nachname:
      in: query
      name: nachname
      schema:
        type: string
    vorname:
      in: query
      name: vorname
      schema:
        type: string
    delegierungId:
      name: delegierungId
      in: path
      required: true
      description: Die ID der Delegierung
      schema:
        $ref: './components/schemas.yaml#/UUID'
  schemas:
    Delegierung:
      type: object
      required:
        - id
      properties:
        id:
          $ref: './components/schemas.yaml#/UUID'
        sozialdienst:
          $ref: './components/schemas.yaml#/SozialdienstSlim'
        delegierterMitarbeiter:
          $ref: './components/schemas.yaml#/SozialdienstBenutzer'
        delegierungAngenommen:
          type: boolean
        persoenlicheAngaben:
          $ref: './components/schemas.yaml#/PersoenlicheAngaben'
    FallWithDelegierung:
      required:
        - id
        - fallNummer
        - mandant
        - delegierung
      type: object
      properties:
        id:
          $ref: './components/schemas.yaml#/UUID'
        fallNummer:
          type: string
        mandant:
          type: string
        delegierung:
          $ref: '#/components/schemas/Delegierung'
    PaginatedSozDashboard:
      allOf:
        - $ref: './components/schemas.yaml#/PaginatedResult'
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/FallWithDelegierung'
    SozDashboardColumn:
      enum:
        - FALLNUMMER
        - NACHNAME
        - VORNAME
        - GEBURTSDATUM
        - WOHNORT
    GetDelegierungSozQueryTypeMitarbeiter:
      enum:
        - ALLE_BEARBEITBAR_MEINE
        - ALLE
      type: string
    GetDelegierungSozQueryTypeAdmin:
      enum:
        - ALLE_BEARBEITBAR_MEINE
        - OFFEN
        - ALLE
      type: string
    DelegierungCreate:
      required:
        - anrede
        - nachname
        - vorname
        - geburtsdatum
        - email
        - sprache
        - adresse
      type: object
      properties:
        anrede:
          $ref: './components/schemas.yaml#/Anrede'
        nachname:
          type: string
        vorname:
          type: string
        geburtsdatum:
          $ref: './components/schemas.yaml#/LocalDate'
        email:
          type: string
        sprache:
          $ref: './components/schemas.yaml#/Sprache'
        adresse:
          $ref: './components/schemas.yaml#/Adresse'
    DelegierterMitarbeiterAendern:
      required:
        - mitarbeiterId
      type: object
      properties:
        mitarbeiterId:
          $ref: './components/schemas.yaml#/UUID'
security:
  - auth-uat-bern: []
  - auth-dev-bern: []
