openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  /verfuegung/{gesuchId}/verfuegungen:
    parameters:
      - name: gesuchId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Verfuegung
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/common.yaml#/Verfuegung'
          description: Returns a list of all Verfuegungen for a Gesuch
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getVerfuegungen
  /verfuegung/dokument/download:
    parameters:
      - name: token
        schema:
          type: string
        in: query
        required: true
    get:
      tags:
        - Verfuegung
      responses:
        200:
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: Returns a file
      operationId: getVerfuegungDokument
      x-quarkus-response-type: org.jboss.resteasy.reactive.RestMulti<io.vertx.mutiny.core.buffer.Buffer>
  /verfuegung/dokument/{verfuegungDokumentId}/token:
    parameters:
      - name: verfuegungDokumentId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Verfuegung
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/FileDownloadToken'
          description: Returns a download token
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getVerfuegungDokumentDownloadToken
      summary: get Token to downlaod Verfuegung
components:
  securitySchemes:
    $ref: './components/security.yaml#/securitySchemes'
security:
  $ref: './components/security.yaml#/security'
