openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  '/datenschutzbrief/{trancheId}/download':
    parameters:
      - name: trancheId
        schema:
          $ref: './components/schemas.yaml#/UUID'
        in: path
      - name: token
        schema:
          type: string
        in: query
        required: true
    get:
      tags:
        - Datenschutzbrief
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: Datenschutzbrief File returned
      operationId: getDatenschutzbrief
      summary: get Datenschutzbrief
      x-quarkus-response-type: org.jboss.resteasy.reactive.RestMulti<io.vertx.mutiny.core.buffer.Buffer>
  '/datenschutzbrief/{elternId}/token':
    parameters:
      - name: elternId
        schema:
          $ref: './components/schemas.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Datenschutzbrief
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: './components/schemas.yaml#/FileDownloadToken'
          description: Token returned
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
          description: Datenschutzbrief File Download Token returned
      operationId: getDatenschutzbriefDownloadToken
      summary: get Token to downlaod Verfuegung
security:
  - auth-uat-bern: []
  - auth-dev-bern: []
