openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  '/verfuegung/download':
    parameters:
      - name: token
        schema:
          type: string
        in: query
        required: true
    get:
      tags:
        - Verfuegung
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: File returned
      operationId: getVerfuegung
      summary: get Verfuegung
      x-quarkus-response-type: org.jboss.resteasy.reactive.RestMulti<io.vertx.mutiny.core.buffer.Buffer>
  '/verfuegung/{verfuegungsId}/token':
    parameters:
      - name: verfuegungsId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Verfuegung
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/FileDownloadToken'
          description: Token returned
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
          description: File returned
      operationId: getVerfuegungsDownloadToken
      summary: get Token to downlaod Verfuegung
components:
  securitySchemes:
    $ref: './components/security.yaml#/securitySchemes'
security:
  $ref: './components/security.yaml#/security'
