openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  /ausbildung:
    post:
      tags:
        - Ausbildung
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AusbildungUpdate'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AusbildungCreateResponse'
          description: Returns the created Ausbildung
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: createAusbildung
      summary: Returniert die erstellte Ausbildung
  /ausbildung/{ausbildungId}:
    parameters:
      - name: ausbildungId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Ausbildung
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Ausbildung'
          description: Returns the created Ausbildung
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getAusbildung
      summary: Returniert die Ausbildung
    patch:
      tags:
        - Ausbildung
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AusbildungUpdate'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/Ausbildung'
          description: Returns the created Ausbildung
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: updateAusbildung
      summary: Returniert die Ausbildung
  /ausbildung/unterbruch-limits/{ausbildungId}:
    parameters:
      - $ref: '#/components/parameters/ausbildungId'
    get:
      tags:
        - Ausbildung
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AusbildungUnterbruchLimits'
          description: unterbruch date limits for given Ausbildung
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getAusbildungUnterbruchLimits
      summary: get unterbruch date limits for given Ausbildung
  /ausbildung/create-unterbruch/{ausbildungId}/gs:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateAusbildungUnterbruchAntragGS'
      parameters:
        - $ref: '#/components/parameters/ausbildungId'
      tags:
        - Ausbildung
      responses:
        '200':
          description: OK
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: createAusbildungUnterbruchAntragGs
      summary: AusbildungUnterbruchAntrag erstellen
      x-quarkus-response-type: io.smallrye.mutiny.Uni<Response>
  /ausbildung/create-unterbruch/{ausbildungId}/sb:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateAusbildungUnterbruchSB'
      parameters:
        - $ref: '#/components/parameters/ausbildungId'
      tags:
        - Ausbildung
      responses:
        '200':
          description: OK
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: createAusbildungUnterbruchSb
      summary: AusbildungUnterbruch erstellen und direkt abschliessen
      x-quarkus-response-type: io.smallrye.mutiny.Uni<Response>
  /ausbildung/unterbruch/{ausbildungUnterbruchAntragId}/sb:
    parameters:
      - $ref: '#/components/parameters/ausbildungUnterbruchAntragId'
    patch:
      tags:
        - Ausbildung
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAusbildungUnterbruchAntragSB'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AusbildungUnterbruchAntragSB'
          description: Returns the created Ausbildung
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: updateAusbildungUnterbruchAntragSB
      summary: AusbildungUnterbruchAntrag abschliessen
  /ausbildung/unterbruch/{gesuchId}/all:
    parameters:
      - $ref: './components/parameters.yaml#/gesuchId'
    get:
      tags:
        - Ausbildung
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AusbildungUnterbruchDashboardSB'
          description: returniert alle AusbildungUnterbruchAntrag des Falls des Gesuchs
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getAusbildungUnterbruchAntragsByGesuchId
      summary: returniert alle AusbildungUnterbruchAntrag des Falls des Gesuchs
  /ausbildung/unterbruch/dokument/{dokumentId}:
    parameters:
      - name: dokumentId
        schema:
          $ref: './components/common.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - Ausbildung
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: './components/common.yaml#/FileDownloadToken'
          description: Token returned
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getAusbildungUnterbruchAntragDokumentDownloadToken
      summary: get Token to downlaod AusbildungUnterbruchAntrag Dokument
  /ausbildung/unterbruch/dokument/download:
    parameters:
      - name: token
        schema:
          type: string
        in: query
        required: true
    get:
      tags:
        - Ausbildung
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: File returned
      operationId: downloadAusbildungUnterbruchAntragDokument
      summary: Download AusbildungUnterbruchAntrag Dokument
      x-quarkus-response-type: org.jboss.resteasy.reactive.RestMulti<io.vertx.mutiny.core.buffer.Buffer>

components:
  securitySchemes:
    $ref: './components/security.yaml#/securitySchemes'
  parameters:
    ausbildungId:
      name: ausbildungId
      in: path
      schema:
        $ref: './components/common.yaml#/UUID'
      required: true
    ausbildungUnterbruchAntragId:
      name: ausbildungUnterbruchAntragId
      in: path
      schema:
        $ref: './components/common.yaml#/UUID'
      required: true
  schemas:
    AusbildungBase:
      required:
        - fallId
        - ausbildungBegin
        - ausbildungEnd
        - pensum
      type: object
      properties:
        id:
          $ref: './components/common.yaml#/UUID'
        fallId:
          $ref: './components/common.yaml#/UUID'
        fachrichtungBerufsbezeichnung:
          type: string
        ausbildungNichtGefunden:
          type: boolean
        ausbildungBegin:
          description: Datum im Format mm.YYYY
          type: string
        ausbildungEnd:
          description: Datum im Format mm.YYYY
          type: string
        besuchtBMS:
          description: Required wenn Abschluss.askForBerufsmaturitaet = true
          type: boolean
        pensum:
          $ref: './components/common.yaml#/AusbildungsPensum'
        alternativeAusbildungsstaette:
          description: Required wenn andere ausbildungNichtGefunden = true
          type: string
        alternativeAusbildungsgang:
          description: Required wenn andere ausbildungNichtGefunden = true
          type: string
        ausbildungsortPLZ:
          description: Not required if isAusbildungAusland = true
          type: string
        ausbildungsort:
          description: Not required if isAusbildungAusland = true
          type: string
        isAusbildungAusland:
          type: boolean
        landId:
          description: Required if isAusbildungAusland = true
          $ref: './components/common.yaml#/UUID'
    AusbildungCreateResponse:
      properties:
        ausbildung:
          $ref: './components/common.yaml#/Ausbildung'
        gesuchId:
          $ref: './components/common.yaml#/UUID'
        gesuchTrancheId:
          $ref: './components/common.yaml#/UUID'
        error:
          $ref: './components/common.yaml#/GesuchsperiodeSelectError'
    AusbildungUpdate:
      type: object
      properties:
        ausbildungsgangId:
          $ref: './components/common.yaml#/UUID'
          description: |
            Required wenn andere ausbildungNichtGefunden = false
      allOf:
        - $ref: '#/components/schemas/AusbildungBase'
    AusbildungUnterbruchLimits:
      required:
        - unterbruchLatestEndDate
        - unterbruchEarliestStartDate
      type: object
      properties:
        unterbruchLatestEndDate:
          format: date
          type: string
        unterbruchEarliestStartDate:
          format: date
          type: string
    CreateAusbildungUnterbruchAntragGS:
      type: object
      required:
        - kommentarGS
        - fileUpload
        - startDate
        - endDate
      properties:
        kommentarGS:
          type: string
        fileUpload:
          $ref: './components/common.yaml#/FileUpload'
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    AusbildungUnterbruchAntragStatus:
      enum:
        - EINGEGEBEN
        - AKZEPTIERT
        - ABGELEHNT
    UpdateAusbildungUnterbruchAntragSB:
      type: object
      required:
        - status
        - kommentarSB
        - startDate
        - endDate
      properties:
        status:
          $ref: '#/components/schemas/AusbildungUnterbruchAntragStatus'
        kommentarSB:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        monateOhneAnspruch:
          type: integer
    CreateAusbildungUnterbruchSB:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateAusbildungUnterbruchAntragGS'
        - $ref: '#/components/schemas/UpdateAusbildungUnterbruchAntragSB'
    AusbildungUnterbruchDashboardSB:
      required:
        - canCreateAusbildungUnterbruch
        - ausbildungUnterbruchs
      type: object
      properties:
        canCreateAusbildungUnterbruch:
          type: boolean
        ausbildungUnterbruchs:
          type: array
          items:
            $ref: '#/components/schemas/AusbildungUnterbruchAntragSB'
    AusbildungUnterbruchAntragSB:
      type: object
      required:
        - id
        - timestampErstellt
        - userErstellt
        - canAntragAkzeptieren
        - unterbruchLatestEndDate
        - unterbruchEarliestStartDate
        - dokuments
        - gesuchId
        - status
      allOf:
        - $ref: '#/components/schemas/CreateAusbildungUnterbruchAntragGS'
      properties:
        id:
          $ref: './components/common.yaml#/UUID'
        timestampErstellt:
          type: string
          format: date-time
        userErstellt:
          type: string
        canAntragAkzeptieren:
          type: boolean
        unterbruchLatestEndDate:
          format: date
          type: string
        unterbruchEarliestStartDate:
          format: date
          type: string
        dokuments:
          type: array
          items:
            $ref: './components/common.yaml#/Dokument'
        gesuchId:
          $ref: './components/common.yaml#/UUID'
        status:
          $ref: '#/components/schemas/AusbildungUnterbruchAntragStatus'
        kommentarSB:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        monateOhneAnspruch:
          type: integer

security:
  $ref: './components/security.yaml#/security'
