openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  '/gesuch/{gesuchId}/notiz/all':
    parameters:
      - name: gesuchId
        schema:
          $ref: './components/schemas.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - GesuchNotiz
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GesuchNotiz'
          description: all notizen of a fall from given gesuch
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getNotizen
      summary: Get all notizen of a fall from given gesuch
  '/gesuch/notiz/create':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GesuchNotizCreate'
        required: true
      tags:
        - GesuchNotiz
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GesuchNotiz'
          description: new notiz is created
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: createNotiz
      summary: Creates a new Notiz for an existing gesuch
  '/gesuch/notiz':
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GesuchNotizUpdate'
        required: true
      tags:
        - GesuchNotiz
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GesuchNotiz'
          description: Notiz aktualisiert
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: updateNotiz
      summary: Updates the Notiz of a Gesuch with the given Notiz-Id
  '/gesuch/notiz/juristischeAbklaerung/{notizId}':
    parameters:
      - name: notizId
        schema:
          $ref: './components/schemas.yaml#/UUID'
        in: path
        required: true
    patch:
      tags:
        - GesuchNotiz
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JuristischeAbklaerungNotizAntwort'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GesuchNotiz'
          description: Juristische Abklaerung Notiz Antwort posted
        '400':
          $ref: './components/responses.yaml#/BadRequest'
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: answerJuristischeAbklaerungNotiz
      summary: Sets the Answer of a Juristische Abklaerung Notiz Antwort
  '/gesuch/notiz/{notizId}':
    parameters:
      - name: notizId
        schema:
          $ref: './components/schemas.yaml#/UUID'
        in: path
        required: true
    get:
      tags:
        - GesuchNotiz
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GesuchNotiz'
          description: |
            get a single notiz
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: getNotiz
      summary: get a single Notiz of a Gesuch with the given Notiz-Id
    delete:
      tags:
        - GesuchNotiz
      responses:
        '204':
          description: |
            Notiz deleted
        '401':
          $ref: './components/responses.yaml#/Unauthorized'
        '403':
          $ref: './components/responses.yaml#/Forbidden'
        '404':
          $ref: './components/responses.yaml#/NotFound'
        '500':
          $ref: './components/responses.yaml#/ServerError'
      operationId: deleteNotiz
      summary: delete a Notiz of a Gesuch with the given Notiz-Id
components:
  schemas:
    GesuchNotizTyp:
      enum:
        - PENDENZ_NOTIZ
        - GESUCH_NOTIZ
        - JURISTISCHE_NOTIZ
    JuristischeAbklaerungNotizAntwort:
      type: object
      required:
        - antwort
      properties:
        antwort:
          type: string
    GesuchNotizCreate:
      type: object
      required:
        - gesuchId
        - betreff
        - text
        - notizTyp
      properties:
        gesuchId:
          $ref: './components/schemas.yaml#/UUID'
        betreff:
          maximum: 100
          type: string
        text:
          type: string
        notizTyp:
          $ref: '#/components/schemas/GesuchNotizTyp'
    GesuchNotizUpdate:
      type: object
      required:
        - id
        - betreff
        - text
      properties:
        id:
          $ref: './components/schemas.yaml#/UUID'
        betreff:
          maximum: 100
          type: string
        text:
          type: string
        pendenzAbgeschlossen:
          type: boolean
    GesuchNotiz:
      required:
        - userErstellt
        - timestampErstellt
        - notizTyp
        - gesuchNummer
        - id
      type: object
      properties:
        userErstellt:
          type: string
        timestampErstellt:
          $ref: './components/schemas.yaml#/LocalDate'
        userMutiert:
          type: string
        timestampMutiert:
          $ref: './components/schemas.yaml#/LocalDate'
        notizTyp:
          $ref: '#/components/schemas/GesuchNotizTyp'
        gesuchNummer:
          type: string
        antwort:
          type: string
        pendenzAbgeschlossen:
          type: boolean
      allOf:
        - type: object
        - $ref: '#/components/schemas/GesuchNotizUpdate'
security:
  - auth-uat-bern: []
  - auth-dev-bern: []
