openapi: 3.0.3
info:
  title: STIP API
  version: '1.0'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl.txt'
servers:
  - url: 'http://localhost:{port}/api/v1'
    variables:
      port:
        default: '8080'
paths:
  /userconsent:
    get:
      tags:
        - UserConsent
      summary: Get user consent by user ID
      operationId: getUserConsent
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConsent'
        '404':
          description: User consent not found
    post:
      tags:
        - UserConsent
      summary: Create user consent
      operationId: createUserConsent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserConsent'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConsent'
        '400':
          description: Invalid input

  # Your Path definitions go here

components:
  securitySchemes:
    $ref: './components/security.yaml#/securitySchemes'
  schemas:
    CreateUserConsent:
      type: object
      properties:
        consentGiven:
          type: boolean
      required:
        - consentGiven
    UserConsent:
      type: object
      properties:
        consentGiven:
          type: boolean
        timestampErstellt:
          type: string
          format: date-time
      required:
        - consentGiven
        - timestampErstellt

  # Schema definitions that are only relevant for this file
  # Definitions accessible by other files should be in components/common.yaml | components/{type}.yaml

security:
  $ref: './components/security.yaml#/security'
