apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: identity-cluster
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi

  bootstrap:
    initdb:
      database: keycloak
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"