export * from './ausbildungsgang.service';
// import { AusbildungsgangService } from './ausbildungsgang.service';
export * from './ausbildungsstaette.service';
// import { AusbildungsstaetteService } from './ausbildungsstaette.service';
export * from './benutzer.service';
// import { BenutzerService } from './benutzer.service';
export * from './bildungsart.service';
// import { BildungsartService } from './bildungsart.service';
export * from './configuration.service';
// import { ConfigurationService } from './configuration.service';
export * from './dokument.service';
// import { DokumentService } from './dokument.service';
export * from './fall.service';
// import { FallService } from './fall.service';
export * from './gesuch.service';
// import { GesuchService } from './gesuch.service';
export * from './gesuchAenderung.service';
// import { GesuchAenderungService } from './gesuchAenderung.service';
export * from './gesuchsjahr.service';
// import { GesuchsjahrService } from './gesuchsjahr.service';
export * from './gesuchsperiode.service';
// import { GesuchsperiodeService } from './gesuchsperiode.service';
export * from './mail.service';
// import { MailService } from './mail.service';
export * from './plz.service';
// import { PlzService } from './plz.service';
export * from './stammdaten.service';
// import { StammdatenService } from './stammdaten.service';
export * from './tenant.service';
// import { TenantService } from './tenant.service';
// Do not generate the constant as accidental use of this prevents tree-shaking.
// export const APIS = [AusbildungsgangService, AusbildungsstaetteService, BenutzerService, BildungsartService, ConfigurationService, DokumentService, FallService, GesuchService, GesuchAenderungService, GesuchsjahrService, GesuchsperiodeService, MailService, PlzService, StammdatenService, TenantService];
