export * from './ausbildung.service';
// import { AusbildungService } from './ausbildung.service';
export * from './ausbildungsgang.service';
// import { AusbildungsgangService } from './ausbildungsgang.service';
export * from './ausbildungsstaette.service';
// import { AusbildungsstaetteService } from './ausbildungsstaette.service';
export * from './benutzer.service';
// import { BenutzerService } from './benutzer.service';
export * from './bildungskategorie.service';
// import { BildungskategorieService } from './bildungskategorie.service';
export * from './configuration.service';
// import { ConfigurationService } from './configuration.service';
export * from './dokument.service';
// import { DokumentService } from './dokument.service';
export * from './fall.service';
// import { FallService } from './fall.service';
export * from './gesuch.service';
// import { GesuchService } from './gesuch.service';
export * from './gesuchTranche.service';
// import { GesuchTrancheService } from './gesuchTranche.service';
export * from './gesuchsjahr.service';
// import { GesuchsjahrService } from './gesuchsjahr.service';
export * from './gesuchsperiode.service';
// import { GesuchsperiodeService } from './gesuchsperiode.service';
export * from './mail.service';
// import { MailService } from './mail.service';
export * from './notification.service';
// import { NotificationService } from './notification.service';
export * from './plz.service';
// import { PlzService } from './plz.service';
export * from './stammdaten.service';
// import { StammdatenService } from './stammdaten.service';
export * from './tenant.service';
// import { TenantService } from './tenant.service';
// Do not generate the constant as accidental use of this prevents tree-shaking.
// export const APIS = [AusbildungService, AusbildungsgangService, AusbildungsstaetteService, BenutzerService, BildungskategorieService, ConfigurationService, DokumentService, FallService, GesuchService, GesuchTrancheService, GesuchsjahrService, GesuchsperiodeService, MailService, NotificationService, PlzService, StammdatenService, TenantService];
