export * from './ausbildung.service';
// import { AusbildungService } from './ausbildung.service';
export * from './ausbildungsgang.service';
// import { AusbildungsgangService } from './ausbildungsgang.service';
export * from './ausbildungsstaette.service';
// import { AusbildungsstaetteService } from './ausbildungsstaette.service';
export * from './auszahlung.service';
// import { AuszahlungService } from './auszahlung.service';
export * from './benutzer.service';
// import { BenutzerService } from './benutzer.service';
export * from './bildungskategorie.service';
// import { BildungskategorieService } from './bildungskategorie.service';
export * from './buchhaltung.service';
// import { BuchhaltungService } from './buchhaltung.service';
export * from './configuration.service';
// import { ConfigurationService } from './configuration.service';
export * from './delegieren.service';
// import { DelegierenService } from './delegieren.service';
export * from './dokument.service';
// import { DokumentService } from './dokument.service';
export * from './fall.service';
// import { FallService } from './fall.service';
export * from './gesuch.service';
// import { GesuchService } from './gesuch.service';
export * from './gesuchNotiz.service';
// import { GesuchNotizService } from './gesuchNotiz.service';
export * from './gesuchTranche.service';
// import { GesuchTrancheService } from './gesuchTranche.service';
export * from './gesuchsjahr.service';
// import { GesuchsjahrService } from './gesuchsjahr.service';
export * from './gesuchsperiode.service';
// import { GesuchsperiodeService } from './gesuchsperiode.service';
export * from './mail.service';
// import { MailService } from './mail.service';
export * from './notification.service';
// import { NotificationService } from './notification.service';
export * from './plz.service';
// import { PlzService } from './plz.service';
export * from './sozialdienst.service';
// import { SozialdienstService } from './sozialdienst.service';
export * from './stammdaten.service';
// import { StammdatenService } from './stammdaten.service';
export * from './steuerdaten.service';
// import { SteuerdatenService } from './steuerdaten.service';
export * from './stipDecision.service';
// import { StipDecisionService } from './stipDecision.service';
export * from './tenant.service';
// import { TenantService } from './tenant.service';
export * from './verfuegung.service';
// import { VerfuegungService } from './verfuegung.service';
// Do not generate the constant as accidental use of this prevents tree-shaking.
// export const APIS = [AusbildungService, AusbildungsgangService, AusbildungsstaetteService, AuszahlungService, BenutzerService, BildungskategorieService, BuchhaltungService, ConfigurationService, DelegierenService, DokumentService, FallService, GesuchService, GesuchNotizService, GesuchTrancheService, GesuchsjahrService, GesuchsperiodeService, MailService, NotificationService, PlzService, SozialdienstService, StammdatenService, SteuerdatenService, StipDecisionService, TenantService, VerfuegungService];
