/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { NeskoGetSteuerdatenRequest } from '../model/neskoGetSteuerdatenRequest';
import { Steuerdaten } from '../model/steuerdaten';
import { ValidationReport } from '../model/validationReport';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


export interface SteuerdatenServiceGetSteuerdatenRequestParams {
    gesuchTrancheId: string;
}

export interface SteuerdatenServiceUpdateSteuerdatenRequestParams {
    gesuchTrancheId: string;
    steuerdaten: Array<Steuerdaten>;
}

export interface SteuerdatenServiceUpdateSteuerdatenFromNeskoRequestParams {
    gesuchTrancheId: string;
    neskoGetSteuerdatenRequest: NeskoGetSteuerdatenRequest;
}


@Injectable({
  providedIn: 'root'
})
export class SteuerdatenService {

    protected basePath = '/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string|string[], @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (Array.isArray(basePath) && basePath.length > 0) {
                basePath = basePath[0];
            }

            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    public getSteuerdatenPath = (requestParameters: SteuerdatenServiceGetSteuerdatenRequestParams) => {
        const gesuchTrancheId = requestParameters.gesuchTrancheId;
        if (gesuchTrancheId === null || gesuchTrancheId === undefined) {
            throw new Error('Required parameter gesuchTrancheId was null or undefined when calling getSteuerdaten$.');
        }
        let path = `/api/v1/steuerdaten/${this.configuration.encodeParam({name: "gesuchTrancheId", value: gesuchTrancheId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;

        // Query Params
        let queryParams = new URLSearchParams();
        const queryParamsString = queryParams.toString();
        if (queryParamsString) {
            return `${path}?${queryParamsString}`;
        }
        return `${path}`;
    }

    /**
     * Returniert die Steuerdaten der gegebenen gesuchTrancheId.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
     public getSteuerdaten$(requestParameters: SteuerdatenServiceGetSteuerdatenRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<Array<Steuerdaten>>;
     public getSteuerdaten$(requestParameters: SteuerdatenServiceGetSteuerdatenRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<HttpResponse<Array<Steuerdaten>>>;
     public getSteuerdaten$(requestParameters: SteuerdatenServiceGetSteuerdatenRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<HttpEvent<Array<Steuerdaten>>>;
     public getSteuerdaten$(requestParameters: SteuerdatenServiceGetSteuerdatenRequestParams, observe: 'body' | 'response' | 'events' = 'body', reportProgress = false, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<any> {
        const gesuchTrancheId = requestParameters.gesuchTrancheId;
        if (gesuchTrancheId === null || gesuchTrancheId === undefined) {
            throw new Error('Required parameter gesuchTrancheId was null or undefined when calling getSteuerdaten$.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (auth-uat-bern) required
        localVarCredential = this.configuration.lookupCredential('auth-uat-bern');
        if (localVarCredential) {
            // using credentials
        }

        // authentication (auth-dev-bern) required
        localVarCredential = this.configuration.lookupCredential('auth-dev-bern');
        if (localVarCredential) {
            // using credentials
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/plain'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        const localVarPath = `/steuerdaten/${this.configuration.encodeParam({name: "gesuchTrancheId", value: gesuchTrancheId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        return this.httpClient.request<Array<Steuerdaten>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: <any>observe,
                reportProgress: reportProgress
            }
        );
    }

    public updateSteuerdatenPath = (requestParameters: SteuerdatenServiceUpdateSteuerdatenRequestParams) => {
        const gesuchTrancheId = requestParameters.gesuchTrancheId;
        if (gesuchTrancheId === null || gesuchTrancheId === undefined) {
            throw new Error('Required parameter gesuchTrancheId was null or undefined when calling updateSteuerdaten$.');
        }
        const steuerdaten = requestParameters.steuerdaten;
        if (steuerdaten === null || steuerdaten === undefined) {
            throw new Error('Required parameter steuerdaten was null or undefined when calling updateSteuerdaten$.');
        }
        let path = `/api/v1/steuerdaten/${this.configuration.encodeParam({name: "gesuchTrancheId", value: gesuchTrancheId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;

        // Query Params
        let queryParams = new URLSearchParams();
        const queryParamsString = queryParams.toString();
        if (queryParamsString) {
            return `${path}?${queryParamsString}`;
        }
        return `${path}`;
    }

    /**
     * Updates the Steuerdaten of the given gesuchTrancheId
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
     public updateSteuerdaten$(requestParameters: SteuerdatenServiceUpdateSteuerdatenRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<Array<Steuerdaten>>;
     public updateSteuerdaten$(requestParameters: SteuerdatenServiceUpdateSteuerdatenRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<HttpResponse<Array<Steuerdaten>>>;
     public updateSteuerdaten$(requestParameters: SteuerdatenServiceUpdateSteuerdatenRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<HttpEvent<Array<Steuerdaten>>>;
     public updateSteuerdaten$(requestParameters: SteuerdatenServiceUpdateSteuerdatenRequestParams, observe: 'body' | 'response' | 'events' = 'body', reportProgress = false, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<any> {
        const gesuchTrancheId = requestParameters.gesuchTrancheId;
        if (gesuchTrancheId === null || gesuchTrancheId === undefined) {
            throw new Error('Required parameter gesuchTrancheId was null or undefined when calling updateSteuerdaten$.');
        }
        const steuerdaten = requestParameters.steuerdaten;
        if (steuerdaten === null || steuerdaten === undefined) {
            throw new Error('Required parameter steuerdaten was null or undefined when calling updateSteuerdaten$.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (auth-uat-bern) required
        localVarCredential = this.configuration.lookupCredential('auth-uat-bern');
        if (localVarCredential) {
            // using credentials
        }

        // authentication (auth-dev-bern) required
        localVarCredential = this.configuration.lookupCredential('auth-dev-bern');
        if (localVarCredential) {
            // using credentials
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/plain'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        const localVarPath = `/steuerdaten/${this.configuration.encodeParam({name: "gesuchTrancheId", value: gesuchTrancheId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        return this.httpClient.request<Array<Steuerdaten>>('patch', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: steuerdaten,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: <any>observe,
                reportProgress: reportProgress
            }
        );
    }

    public updateSteuerdatenFromNeskoPath = (requestParameters: SteuerdatenServiceUpdateSteuerdatenFromNeskoRequestParams) => {
        const gesuchTrancheId = requestParameters.gesuchTrancheId;
        if (gesuchTrancheId === null || gesuchTrancheId === undefined) {
            throw new Error('Required parameter gesuchTrancheId was null or undefined when calling updateSteuerdatenFromNesko$.');
        }
        const neskoGetSteuerdatenRequest = requestParameters.neskoGetSteuerdatenRequest;
        if (neskoGetSteuerdatenRequest === null || neskoGetSteuerdatenRequest === undefined) {
            throw new Error('Required parameter neskoGetSteuerdatenRequest was null or undefined when calling updateSteuerdatenFromNesko$.');
        }
        let path = `/api/v1/steuerdaten/nesko/${this.configuration.encodeParam({name: "gesuchTrancheId", value: gesuchTrancheId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;

        // Query Params
        let queryParams = new URLSearchParams();
        const queryParamsString = queryParams.toString();
        if (queryParamsString) {
            return `${path}?${queryParamsString}`;
        }
        return `${path}`;
    }

    /**
     * Updates the Steuerdaten from Nesko
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
     public updateSteuerdatenFromNesko$(requestParameters: SteuerdatenServiceUpdateSteuerdatenFromNeskoRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<Array<Steuerdaten>>;
     public updateSteuerdatenFromNesko$(requestParameters: SteuerdatenServiceUpdateSteuerdatenFromNeskoRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<HttpResponse<Array<Steuerdaten>>>;
     public updateSteuerdatenFromNesko$(requestParameters: SteuerdatenServiceUpdateSteuerdatenFromNeskoRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<HttpEvent<Array<Steuerdaten>>>;
     public updateSteuerdatenFromNesko$(requestParameters: SteuerdatenServiceUpdateSteuerdatenFromNeskoRequestParams, observe: 'body' | 'response' | 'events' = 'body', reportProgress = false, options?: {httpHeaderAccept?: 'application/json' | 'text/plain', context?: HttpContext}): Observable<any> {
        const gesuchTrancheId = requestParameters.gesuchTrancheId;
        if (gesuchTrancheId === null || gesuchTrancheId === undefined) {
            throw new Error('Required parameter gesuchTrancheId was null or undefined when calling updateSteuerdatenFromNesko$.');
        }
        const neskoGetSteuerdatenRequest = requestParameters.neskoGetSteuerdatenRequest;
        if (neskoGetSteuerdatenRequest === null || neskoGetSteuerdatenRequest === undefined) {
            throw new Error('Required parameter neskoGetSteuerdatenRequest was null or undefined when calling updateSteuerdatenFromNesko$.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (auth-uat-bern) required
        localVarCredential = this.configuration.lookupCredential('auth-uat-bern');
        if (localVarCredential) {
            // using credentials
        }

        // authentication (auth-dev-bern) required
        localVarCredential = this.configuration.lookupCredential('auth-dev-bern');
        if (localVarCredential) {
            // using credentials
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'text/plain'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        const localVarPath = `/steuerdaten/nesko/${this.configuration.encodeParam({name: "gesuchTrancheId", value: gesuchTrancheId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        return this.httpClient.request<Array<Steuerdaten>>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: neskoGetSteuerdatenRequest,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: <any>observe,
                reportProgress: reportProgress
            }
        );
    }

}
