package ch.dvbern.stip.api.lebenslauf.type;

public enum LebenslaufAusbildungsArt {
	BERUFSVORBEREITENDES_SCHULJAHR,
	VORLEHRE,
	GESTALTERISCHE_VORKURSE,
	EIDGENOESSISCHES_BERUFSATTEST,
	EIDGENOESSISCHES_FAEHIGKEITSZEUGNIS,
	BERUFSMATURITAET_NACH_LEHRE,
	FACHMATURITAET,
	GYMNASIALE_MATURITAETSSCHULEN,
	EIDGENOESSISCHES_DIPLOM,
	EIDGENOESSISCHER_FACHAUSWEIS,
	DIPLOM_HOEHERE_FACHSCHULE,
	BACHELOR_HOCHSCHULE_UNI,
	BACHELOR_FACHHOCHSCHULE,
	MASTER,
	ANDERER_BILDUNGSABSCHLUSS
}
